/* Generated by Nim Compiler v1.2.6 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -pthread -I/home/runner/work/nim-waku/nim-waku/vendor/nim-libbacktrace -I/home/runner/work/nim-waku/nim-waku/vendor/nim-libbacktrace/install/usr/include -I/home/runner/work/nim-waku/nim-waku/vendor/nim-secp256k1/secp256k1_wrapper -I/home/runner/work/nim-waku/nim-waku/vendor/nim-secp256k1/secp256k1_wrapper/secp256k1 -I/home/runner/work/nim-waku/nim-waku/vendor/nim-secp256k1/secp256k1_wrapper/secp256k1/src -DHAVE_CONFIG_H -DHAVE_BUILTIN_EXPECT -I/home/runner/work/nim-waku/nim-waku/vendor/nim-bearssl/bearssl/csources/src -I/home/runner/work/nim-waku/nim-waku/vendor/nim-bearssl/bearssl/csources/inc -I/home/runner/work/nim-waku/nim-waku/vendor/nim-bearssl/bearssl/csources/tools -DBR_USE_UNIX_TIME=1 -DBR_USE_URANDOM=1 -DBR_LE_UNALIGNED=1 -DBR_64=1  -DBR_amd64=1 -DBR_INT128=1 -I/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/vendor/miniupnp/miniupnpc -I/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/vendor/libnatpmp-upstream -DENABLE_STRNATPMPERR -march=native -g3 -Og -O3 -fno-strict-aliasing -fno-ident  -I/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib -I/home/runner/work/nim-waku/nim-waku/waku/common -o nimcache/release/wakubridge/@m..@s..@svendor@snim-nat-traversal@snat_traversal@sminiupnpc.nim.c.o nimcache/release/wakubridge/@m..@s..@svendor@snim-nat-traversal@snat_traversal@sminiupnpc.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include "miniupnpc.h"
#include "igd_desc_parse.h"
#include "upnpdev.h"
#include <string.h>
#include "upnperrors.h"
#include <sys/types.h>
                          #include <pthread.h>
#include "upnpcommands.h"
#include <setjmp.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_MiniupnpcolonObjectType___ZfgtTEK0E380MDBW1PU9cXw tyObject_MiniupnpcolonObjectType___ZfgtTEK0E380MDBW1PU9cXw;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_Result__pZorf3I302ZEhkhn6lPgmg tyObject_Result__pZorf3I302ZEhkhn6lPgmg;
typedef struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack__7fytPA5bBsob6See21YMRA tyObject_GcStack__7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyTuple__ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw;
typedef struct tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg;
typedef struct tyObject_Result__2tk2I019cjBvNsi9aKg47acQ tyObject_Result__2tk2I019cjBvNsi9aKg47acQ;
typedef struct tyObject_Result__ilFFiS4FzkKdKwqy8wvy9cQ tyObject_Result__ilFFiS4FzkKdKwqy8wvy9cQ;
typedef struct tyObject_Result__9bn3q9cf2t0jbXRYPFofJMAQ tyObject_Result__9bn3q9cf2t0jbXRYPFofJMAQ;
typedef struct tyObject_PortMappingRes__HAKwlWP34w7w9bH9bs3Ehk1A tyObject_PortMappingRes__HAKwlWP34w7w9bH9bs3Ehk1A;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct TSafePoint TSafePoint;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
typedef NIM_CHAR tyArray__Zi76kwLs40ycIpfYa0tP7Q[128];
struct TGenericSeq {NI len;
NI reserved;
};
struct NimStringDesc {  TGenericSeq Sup;NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_MiniupnpcolonObjectType___ZfgtTEK0E380MDBW1PU9cXw {struct UPNPDev* devList;
struct UPNPUrls urls;
struct IGDdatas data;
int discoverDelay;
NimStringDesc* multicastIF;
NimStringDesc* miniSsdpdSocket;
int localPort;
int ipv6;
unsigned char ttl;
int error;
NimStringDesc* lanAddr;
};
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {NI size;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
NCSTRING name;
TNimType* nextType;
NI instances;
NI sizes;
};
typedef NIM_CHAR tyArray__KzYsGdAcGnUxHpbjbCVtbQ[3];
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Result__pZorf3I302ZEhkhn6lPgmg {NIM_BOOL o;
union{
struct {NCSTRING e;
} _o_1;
struct {NI v;
} _o_2;
};
};
typedef NU8 tyEnum_SelectIGDResult__a0pEH6gyEmfVM45vvbAaQw;
struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g {NI refcount;
TNimType* typ;
};
struct tyObject_GcStack__7fytPA5bBsob6See21YMRA {void* bottom;
};
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w {NI len;
NI cap;
tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ* tyArray__SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* tyArray__N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray__N1u1nqOgmuJN9cSZrnMHgOQ tyArray__B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw* tyArray__lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA {tyArray__lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* tyArray__0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw {tyArray__0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyArray__LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg {NI len;
tyArray__LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg {NI minLargeObj;
NI maxLargeObj;
tyArray__SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray__B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
NI allocCounter;
NI deallocCounter;
};
struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg {NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ {NI counter;
NI max;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg** data;
};
typedef long tyArray__xDUyu9aScDpt0JZLU6q9aEZQ[5];
struct tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw {tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg* head;
tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg* tail;
pthread_mutex_t lock;
};
struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ {tyObject_GcStack__7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w additionalRoots;
tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw toDispose;
NI gcThreadId;
};
struct tyObject_Result__2tk2I019cjBvNsi9aKg47acQ {NIM_BOOL o;
union{
struct {NCSTRING e;
} _o_1;
struct {NimStringDesc* v;
} _o_2;
};
};
struct tyObject_Result__ilFFiS4FzkKdKwqy8wvy9cQ {NIM_BOOL o;
union{
struct {NCSTRING e;
} _o_1;
struct {NIM_BOOL v;
} _o_2;
};
};
typedef NU8 tyEnum_UPNPProtocol__KRPLdnmctmfcFCiWnVJqLw;
struct tyObject_PortMappingRes__HAKwlWP34w7w9bH9bs3Ehk1A {NimStringDesc* externalPort;
NimStringDesc* internalClient;
NimStringDesc* internalPort;
tyEnum_UPNPProtocol__KRPLdnmctmfcFCiWnVJqLw protocol;
NimStringDesc* description;
NIM_BOOL enabled;
NimStringDesc* remoteHost;
NU64 leaseDuration;
};
struct RootObj {TNimType* m_type;};
struct Exception {  RootObj Sup;Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence__uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
typedef long tyArray__TcvIiMAJvcwzNLsZkfnFnQ[25];
struct TSafePoint {TSafePoint* prev;
NI status;
jmp_buf context;
};
struct tyObject_Result__9bn3q9cf2t0jbXRYPFofJMAQ {NIM_BOOL o;
union{
struct {NCSTRING e;
} _o_1;
struct {tyObject_PortMappingRes__HAKwlWP34w7w9bH9bs3Ehk1A v;
} _o_2;
};
};
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {  TGenericSeq Sup;  tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];};N_LIB_PRIVATE N_NIMCALL(tyObject_MiniupnpcolonObjectType___ZfgtTEK0E380MDBW1PU9cXw*, eqdeepCopy___KCCVaHQ9bOwoHZKFNWPsmEQ)(tyObject_MiniupnpcolonObjectType___ZfgtTEK0E380MDBW1PU9cXw* x_0);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A)(NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef__9aELMDPtAVkfnKCx8AU54Kg)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, chckNil)(void* p);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef__AT1eRuflKWyTTBdLjEDZbg_3system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, pluspercent___dgYAo7RfdUVVpvkfKDym8wsystem)(NI x, NI y);
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem)(void* usr);
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8w_2system)(NI x, NI y);
static N_INLINE(void, decRef__AT1eRuflKWyTTBdLjEDZbgsystem)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NIM_BOOL, ltpercent___hPljn3JCDQ00ua1R07X9bxQsystem)(NI x, NI y);
static N_INLINE(void, rtlAddZCT__AT1eRuflKWyTTBdLjEDZbg_2system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__Y66tOYFjgwJ0k4aLz4bc0Q)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(void, trimString__MU9c9bW9a4guA5eApxkZIsPsQ)(NimStringDesc** s_0);
static N_INLINE(NI, nimCStrLen)(NCSTRING a);
N_LIB_PRIVATE N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, reprEnum)(NI e, TNimType* typ);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
N_LIB_PRIVATE N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s_0);
static N_INLINE(void, popSafePoint)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isObj)(TNimType* obj, TNimType* subclass);
static N_INLINE(Exception*, nimBorrowCurrentException)(void);
static N_INLINE(void, popCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, reraiseException)(void);
N_LIB_PRIVATE N_NIMCALL(NU64, nsuParseBiggestUInt)(NimStringDesc* s_0);
N_LIB_PRIVATE N_NIMCALL(void, genericAssign)(void* dest, void* src, TNimType* mt);
N_LIB_PRIVATE TNimType NTI__ZfgtTEK0E380MDBW1PU9cXw_;
N_LIB_PRIVATE TNimType NTI__tvfSgzlA9aG9aeo6fCNw9bCMA_;
N_LIB_PRIVATE TNimType NTI__PbuwXN9cgq8yGJnIU9agTTuQ_;
N_LIB_PRIVATE TNimType NTI__9boSe1qwO6bN9bkqJidA0B1Q_;
N_LIB_PRIVATE TNimType NTI__3sRdAXq0yC3Bmz39avLPKNA_;
extern TNimType NTI__nlCscttRCss70IBTyuBqnA_;
extern TNimType NTI__77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTI__aai9cIdjrwazYp9aHakMchqw_;
STRING_LITERAL(TM__XQYS3he3QszP5orM2CZQnw_3, "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/na"
"t_traversal/miniupnpc.nim(547, 11) `false` not implemented", 121);
N_LIB_PRIVATE TNimType NTI__9aELMDPtAVkfnKCx8AU54Kg_;
N_LIB_PRIVATE TNimType NTI__KRPLdnmctmfcFCiWnVJqLw_;
extern TNimType NTI__yoNlBGx0D2tRizIdhQuENw_;
N_LIB_PRIVATE TNimType NTI__HAKwlWP34w7w9bH9bs3Ehk1A_;
extern TNimType NTI__VaVACK0bpYmqIQ0mKcHfQQ_;
extern TNimType NTI__wMtfD88jmrPZwfzTH9c8e9cA_;
N_LIB_PRIVATE NCSTRING MINIUPNPC_VERSION__lfnjdZerCuHsF9aL1knji9aA;
N_LIB_PRIVATE int MINIUPNPC_API_VERSION__5N6HtfEkbAUMBBvHSrCbMA;
extern TNimType* nimTypeRoot;
extern NIM_THREADVAR tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ gch__IcYaEuuWivYAS86vFMTS3Q;
extern NIM_THREADVAR TSafePoint* excHandler__rqLlY5bs9atDw2OXYqJEn5g;
extern NIM_THREADVAR TSafePoint* excHandler__rqLlY5bs9atDw2OXYqJEn5g;
extern NIM_THREADVAR TSafePoint* excHandler__rqLlY5bs9atDw2OXYqJEn5g;
extern NIM_THREADVAR TSafePoint* excHandler__rqLlY5bs9atDw2OXYqJEn5g;
extern NIM_THREADVAR Exception* currException__9bVPeDJlYTi9bQApZpfH8wjg;
extern NIM_THREADVAR Exception* currException__9bVPeDJlYTi9bQApZpfH8wjg;
extern NIM_THREADVAR Exception* currException__9bVPeDJlYTi9bQApZpfH8wjg;

#line 546 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_MiniupnpcolonObjectType___ZfgtTEK0E380MDBW1PU9cXw*, eqdeepCopy___KCCVaHQ9bOwoHZKFNWPsmEQ)(tyObject_MiniupnpcolonObjectType___ZfgtTEK0E380MDBW1PU9cXw* x_0) {	tyObject_MiniupnpcolonObjectType___ZfgtTEK0E380MDBW1PU9cXw* result;	result = (tyObject_MiniupnpcolonObjectType___ZfgtTEK0E380MDBW1PU9cXw*)0;
#line 547 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
	{		if (!NIM_TRUE) goto LA3_;

#line 547 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 547 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
		failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(((NimStringDesc*) &TM__XQYS3he3QszP5orM2CZQnw_3));
	}
	LA3_: ;
	return result;}
static N_NIMCALL(void, Marker_tyRef__9aELMDPtAVkfnKCx8AU54Kg)(void* p, NI op) {
	tyObject_MiniupnpcolonObjectType___ZfgtTEK0E380MDBW1PU9cXw* a;
	NI T1_;	NI T2_;	NI T3_;	NI T4_;	NI T5_;	NI T6_;	NI T7_;	NI T8_;	NI T9_;	NI T10_;	NI T11_;	NI T12_;	NI T13_;	NI T14_;	NI T15_;	NI T16_;	NI T17_;	NI T18_;	NI T19_;	NI T20_;	NI T21_;	NI T22_;	NI T23_;	a = (tyObject_MiniupnpcolonObjectType___ZfgtTEK0E380MDBW1PU9cXw*)p;
	T1_ = (NI)0;	T2_ = (NI)0;	T3_ = (NI)0;	T4_ = (NI)0;	T5_ = (NI)0;	T6_ = (NI)0;	T7_ = (NI)0;	T8_ = (NI)0;	T9_ = (NI)0;	T10_ = (NI)0;	T11_ = (NI)0;	T12_ = (NI)0;	T13_ = (NI)0;	T14_ = (NI)0;	T15_ = (NI)0;	T16_ = (NI)0;	T17_ = (NI)0;	T18_ = (NI)0;	T19_ = (NI)0;	T20_ = (NI)0;	T21_ = (NI)0;	T22_ = (NI)0;	T23_ = (NI)0;	nimGCvisit((void*)(*a).multicastIF, op);	nimGCvisit((void*)(*a).miniSsdpdSocket, op);	nimGCvisit((void*)(*a).lanAddr, op);}

#line 542 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_MiniupnpcolonObjectType___ZfgtTEK0E380MDBW1PU9cXw*, newMiniupnp__ANEb8jK9bX9a0bLJkvSCIc9bQ)(void) {	tyObject_MiniupnpcolonObjectType___ZfgtTEK0E380MDBW1PU9cXw* result;	result = (tyObject_MiniupnpcolonObjectType___ZfgtTEK0E380MDBW1PU9cXw*)0;
#line 543 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
	result = (tyObject_MiniupnpcolonObjectType___ZfgtTEK0E380MDBW1PU9cXw*) newObj((&NTI__9aELMDPtAVkfnKCx8AU54Kg_), sizeof(tyObject_MiniupnpcolonObjectType___ZfgtTEK0E380MDBW1PU9cXw));
#line 544 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
	(*result).ttl = 2;	return result;}

#line 22 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size) {	void* T1_;
#line 24 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"

#line 24 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memset(a, v, ((size_t) (size)));}

#line 33 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
#line 34 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"

#line 34 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"
	nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory(p, ((int) 0), size);
}

#line 85 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/sysstr.nim"
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s) {	NCSTRING result;	result = (NCSTRING)0;
#line 86 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/sysstr.nim"
	{		NIM_BOOL T3_;
#line 86 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/sysstr.nim"
		T3_ = (NIM_BOOL)0;
#line 86 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/sysstr.nim"
		T3_ = (s == NIM_NIL);		if (T3_) goto LA4_;

#line 86 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/sysstr.nim"
		T3_ = ((*s).Sup.len == ((NI) 0));		LA4_: ;
		if (!T3_) goto LA5_;

#line 86 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/sysstr.nim"
		result = "";	}
	goto LA1_;
	LA5_: ;
	{
#line 87 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/sysstr.nim"
		result = ((NCSTRING) ((*s).data));	}
	LA1_: ;
	return result;}

#line 554 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_Result__pZorf3I302ZEhkhn6lPgmg, discover__q5OIsUzEm9aNs73Z4nlTu9aQ)(tyObject_MiniupnpcolonObjectType___ZfgtTEK0E380MDBW1PU9cXw* self) {	tyObject_Result__pZorf3I302ZEhkhn6lPgmg result;	NCSTRING multicastIF;	NCSTRING miniSsdpdSocket;	struct UPNPDev* dev;	NI i;	nimZeroMem((void*)(&result), sizeof(tyObject_Result__pZorf3I302ZEhkhn6lPgmg));
#line 555 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
	{
#line 555 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 555 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
		if (!!(((*self).devList == NIM_NIL))) goto LA3_;

#line 556 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 556 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
		freeUPNPDevlist((*self).devList);
	}
	LA3_: ;

#line 557 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
	(*self).error = ((int) 0);
#line 559 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 559 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
	{
#line 559 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 559 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
		if (!(((NI) 0) < ((*self).multicastIF ? (*self).multicastIF->Sup.len : 0))) goto LA7_;
		multicastIF = nimToCStringConv((*self).multicastIF);	}
	goto LA5_;
	LA7_: ;
	{		multicastIF = NIM_NIL;	}
	LA5_: ;

#line 560 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 560 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
	{
#line 560 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 560 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
		if (!(((NI) 0) < ((*self).miniSsdpdSocket ? (*self).miniSsdpdSocket->Sup.len : 0))) goto LA12_;
		miniSsdpdSocket = nimToCStringConv((*self).miniSsdpdSocket);	}
	goto LA10_;
	LA12_: ;
	{		miniSsdpdSocket = NIM_NIL;	}
	LA10_: ;

#line 561 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 561 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
	(*self).devList = upnpDiscover((*self).discoverDelay, multicastIF, miniSsdpdSocket, (*self).localPort, (*self).ipv6, (*self).ttl, (&(*self).error));
#line 569 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
	dev = (*self).devList;
#line 570 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
	i = ((NI) 0);	{
#line 572 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
		while (1) {			NI TM__XQYS3he3QszP5orM2CZQnw_4;
#line 572 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 572 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
			if (!!((dev == NIM_NIL))) goto LA16;

#line 573 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
			if (nimAddInt(i, ((NI) 1), &TM__XQYS3he3QszP5orM2CZQnw_4)) { raiseOverflow(); };			i = (NI)(TM__XQYS3he3QszP5orM2CZQnw_4);
#line 574 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
			dev = (*dev).pNext;		} LA16: ;
	}

#line 576 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
	{
#line 576 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
		if (!((*self).error == ((NI32) 0))) goto LA19_;

#line 300 "/home/runner/work/nim-waku/nim-waku/vendor/nim-stew/stew/results.nim"
		chckNil((void*)(&result));		nimZeroMem((void*)(&result), sizeof(tyObject_Result__pZorf3I302ZEhkhn6lPgmg));		result.o = NIM_TRUE;		result._o_2.v = i;	}
	goto LA17_;
	LA19_: ;
	{
#line 319 "/home/runner/work/nim-waku/nim-waku/vendor/nim-stew/stew/results.nim"
		chckNil((void*)(&result));		nimZeroMem((void*)(&result), sizeof(tyObject_Result__pZorf3I302ZEhkhn6lPgmg));		result.o = NIM_FALSE;
#line 579 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 579 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
		result._o_1.e = strupnperror((*self).error);	}
	LA17_: ;
	return result;}

#line 425 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/arithmetics.nim"
static N_INLINE(NI, pluspercent___dgYAo7RfdUVVpvkfKDym8wsystem)(NI x, NI y) {	NI result;	result = (NI)0;
#line 426 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/arithmetics.nim"

#line 430 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/arithmetics.nim"
	result = ((NI) ((NU)((NU64)(((NU) (x))) + (NU64)(((NU) (y))))));	return result;}

#line 182 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
static N_INLINE(void, incRef__AT1eRuflKWyTTBdLjEDZbg_3system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
#line 184 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 184 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
	(*c).refcount = pluspercent___dgYAo7RfdUVVpvkfKDym8wsystem((*c).refcount, ((NI) 8));}

#line 436 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/arithmetics.nim"
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8w_2system)(NI x, NI y) {	NI result;	result = (NI)0;
#line 437 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/arithmetics.nim"

#line 441 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/arithmetics.nim"
	result = ((NI) ((NU)((NU64)(((NU) (x))) - (NU64)(((NU) (y))))));	return result;}

#line 128 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem)(void* usr) {	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* result;	NI T1_;	result = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
#line 130 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 130 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 130 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
	T1_ = (NI)0;	T1_ = minuspercent___dgYAo7RfdUVVpvkfKDym8w_2system(((NI) (ptrdiff_t) (usr)), ((NI) 16));	result = ((tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*) (T1_));	return result;}

#line 187 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/comparisons.nim"
static N_INLINE(NIM_BOOL, ltpercent___hPljn3JCDQ00ua1R07X9bxQsystem)(NI x, NI y) {	NIM_BOOL result;	result = (NIM_BOOL)0;
#line 188 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/comparisons.nim"

#line 190 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/comparisons.nim"
	result = ((NU64)(((NU) (x))) < (NU64)(((NU) (y))));	return result;}

#line 194 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
static N_INLINE(void, rtlAddZCT__AT1eRuflKWyTTBdLjEDZbg_2system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
#line 196 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 196 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
	addZCT__Y66tOYFjgwJ0k4aLz4bc0Q((&gch__IcYaEuuWivYAS86vFMTS3Q.zct), c);
}

#line 198 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
static N_INLINE(void, decRef__AT1eRuflKWyTTBdLjEDZbgsystem)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
#line 201 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 201 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
	(*c).refcount = minuspercent___dgYAo7RfdUVVpvkfKDym8w_2system((*c).refcount, ((NI) 8));
#line 202 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
	{		NIM_BOOL T3_;
#line 202 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 202 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
		T3_ = (NIM_BOOL)0;		T3_ = ltpercent___hPljn3JCDQ00ua1R07X9bxQsystem((*c).refcount, ((NI) 8));		if (!T3_) goto LA4_;

#line 203 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 203 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
		rtlAddZCT__AT1eRuflKWyTTBdLjEDZbg_2system(c);
	}
	LA4_: ;
}

#line 235 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
static N_INLINE(void, asgnRef)(void** dest, void* src) {
#line 239 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
	{		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T5_;
#line 239 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 239 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
		if (!!((src == NIM_NIL))) goto LA3_;

#line 239 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 239 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 239 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
		T5_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;		T5_ = usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem(src);
#line 239 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
		incRef__AT1eRuflKWyTTBdLjEDZbg_3system(T5_);
	}
	LA3_: ;

#line 240 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
	{		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T10_;
#line 240 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 240 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
		if (!!(((*dest) == NIM_NIL))) goto LA8_;

#line 240 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 240 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 240 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
		T10_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;		T10_ = usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem((*dest));
#line 240 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
		decRef__AT1eRuflKWyTTBdLjEDZbgsystem(T10_);
	}
	LA8_: ;

#line 241 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
	(*dest) = src;}

#line 48 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"
static N_INLINE(NI, nimCStrLen)(NCSTRING a) {	NI result;	size_t T1_;	result = (NI)0;
#line 50 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"

#line 50 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"

#line 50 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"
	T1_ = (size_t)0;	T1_ = strlen(a);	result = ((NI) (T1_));	return result;}

#line 550 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
N_LIB_PRIVATE N_NIMCALL(void, trimString__MU9c9bW9a4guA5eApxkZIsPsQ)(NimStringDesc** s_0) {
#line 551 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 551 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
	if (((nimToCStringConv((*s_0)) ? nimCStrLen(nimToCStringConv((*s_0))) : 0)) < ((NI) 0) || ((nimToCStringConv((*s_0)) ? nimCStrLen(nimToCStringConv((*s_0))) : 0)) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI((nimToCStringConv((*s_0)) ? nimCStrLen(nimToCStringConv((*s_0))) : 0), ((NI) 0), ((NI) IL64(9223372036854775807))); }	unsureAsgnRef((void**) (&(*s_0)), setLengthStr((*s_0), ((NI) ((nimToCStringConv((*s_0)) ? nimCStrLen(nimToCStringConv((*s_0))) : 0)))));}

#line 587 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
N_LIB_PRIVATE N_NIMCALL(tyEnum_SelectIGDResult__a0pEH6gyEmfVM45vvbAaQw, selectIGD__9ceZ2eNfGqpolu2muX5ZGFA)(tyObject_MiniupnpcolonObjectType___ZfgtTEK0E380MDBW1PU9cXw* self) {	tyEnum_SelectIGDResult__a0pEH6gyEmfVM45vvbAaQw result;	int lanaddrlen;	int T1_;	result = (tyEnum_SelectIGDResult__a0pEH6gyEmfVM45vvbAaQw)0;
#line 588 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
	lanaddrlen = ((int) 40);
#line 589 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
	asgnRef((void**) (&(*self).lanAddr), setLengthStr((*self).lanAddr, ((NI) 40)));
#line 594 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 590 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 590 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
	T1_ = (int)0;	T1_ = UPNP_GetValidIGD((*self).devList, (&(*self).urls), (&(*self).data), nimToCStringConv((*self).lanAddr), lanaddrlen);	if ((T1_) < ((tyEnum_SelectIGDResult__a0pEH6gyEmfVM45vvbAaQw) 0) || (T1_) > ((tyEnum_SelectIGDResult__a0pEH6gyEmfVM45vvbAaQw) 3)){ raiseRangeErrorI(T1_, ((tyEnum_SelectIGDResult__a0pEH6gyEmfVM45vvbAaQw) 0), ((tyEnum_SelectIGDResult__a0pEH6gyEmfVM45vvbAaQw) 3)); }	result = ((tyEnum_SelectIGDResult__a0pEH6gyEmfVM45vvbAaQw) (T1_));
#line 595 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 595 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
	trimString__MU9c9bW9a4guA5eApxkZIsPsQ((&(*self).lanAddr));
	return result;}

#line 659 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
N_LIB_PRIVATE N_NIMCALL(void, externalIPAddress__tm3COvFEKLwn5s7hNUeAiQ)(tyObject_MiniupnpcolonObjectType___ZfgtTEK0E380MDBW1PU9cXw* self, tyObject_Result__2tk2I019cjBvNsi9aKg47acQ* Result) {	NimStringDesc* externalIP;	int res;	chckNil((void*)Result);	switch ((*Result).o) {
	case NIM_FALSE:
	(*Result)._o_1.e = NIM_NIL;	break;
	case NIM_TRUE:
	unsureAsgnRef((void**)&(*Result)._o_2.v, NIM_NIL);	break;
	} 
	(*Result).o = 0;
#line 660 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 660 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 660 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
	externalIP = mnewString(((NI) 40));
#line 661 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 661 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
	res = UPNP_GetExternalIPAddress((*self).urls.controlURL, ((NCSTRING) ((*self).data.first.servicetype)), nimToCStringConv(externalIP));
#line 664 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
	{
#line 664 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
		if (!(res == ((int) 0))) goto LA3_;

#line 665 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 665 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
		trimString__MU9c9bW9a4guA5eApxkZIsPsQ((&externalIP));

#line 300 "/home/runner/work/nim-waku/nim-waku/vendor/nim-stew/stew/results.nim"
		chckNil((void*)Result);		switch ((*Result).o) {
		case NIM_FALSE:
		(*Result)._o_1.e = NIM_NIL;		break;
		case NIM_TRUE:
		unsureAsgnRef((void**)&(*Result)._o_2.v, NIM_NIL);		break;
		} 
		(*Result).o = 0;		(*Result).o = NIM_TRUE;		unsureAsgnRef((void**) (&(*Result)._o_2.v), copyString(externalIP));	}
	goto LA1_;
	LA3_: ;
	{
#line 319 "/home/runner/work/nim-waku/nim-waku/vendor/nim-stew/stew/results.nim"
		chckNil((void*)Result);		switch ((*Result).o) {
		case NIM_FALSE:
		(*Result)._o_1.e = NIM_NIL;		break;
		case NIM_TRUE:
		unsureAsgnRef((void**)&(*Result)._o_2.v, NIM_NIL);		break;
		} 
		(*Result).o = 0;		(*Result).o = NIM_FALSE;
#line 668 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 668 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
		(*Result)._o_1.e = strupnperror(res);	}
	LA1_: ;
}

#line 674 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_Result__ilFFiS4FzkKdKwqy8wvy9cQ, addPortMapping__zFlNC9cpw7a1Ru4SVofxGvA)(tyObject_MiniupnpcolonObjectType___ZfgtTEK0E380MDBW1PU9cXw* self, NimStringDesc* externalPort_0, tyEnum_UPNPProtocol__KRPLdnmctmfcFCiWnVJqLw protocol_0, NimStringDesc* internalHost, NimStringDesc* internalPort_0, NimStringDesc* desc_0, NI leaseDuration, NimStringDesc* externalIP) {	tyObject_Result__ilFFiS4FzkKdKwqy8wvy9cQ result;	NCSTRING extIP;	int res;	NimStringDesc* T5_;	nimZeroMem((void*)(&result), sizeof(tyObject_Result__ilFFiS4FzkKdKwqy8wvy9cQ));
#line 682 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
	extIP = nimToCStringConv(externalIP);
#line 683 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
	{
#line 683 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
		if (!((externalIP ? externalIP->Sup.len : 0) == 0)) goto LA3_;

#line 687 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
		extIP = NIM_NIL;	}
	LA3_: ;

#line 688 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 694 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 696 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
	T5_ = (NimStringDesc*)0;	T5_ = nimIntToStr(leaseDuration);
#line 688 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
	res = UPNP_AddPortMapping((*self).urls.controlURL, ((NCSTRING) ((*self).data.first.servicetype)), nimToCStringConv(externalPort_0), nimToCStringConv(internalPort_0), nimToCStringConv(internalHost), nimToCStringConv(desc_0), nimToCStringConv(reprEnum((NI)protocol_0, (&NTI__KRPLdnmctmfcFCiWnVJqLw_))), extIP, nimToCStringConv(T5_));
#line 697 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
	{
#line 697 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
		if (!(res == ((int) 0))) goto LA8_;

#line 300 "/home/runner/work/nim-waku/nim-waku/vendor/nim-stew/stew/results.nim"
		chckNil((void*)(&result));		nimZeroMem((void*)(&result), sizeof(tyObject_Result__ilFFiS4FzkKdKwqy8wvy9cQ));		result.o = NIM_TRUE;		result._o_2.v = NIM_TRUE;	}
	goto LA6_;
	LA8_: ;
	{
#line 319 "/home/runner/work/nim-waku/nim-waku/vendor/nim-stew/stew/results.nim"
		chckNil((void*)(&result));		nimZeroMem((void*)(&result), sizeof(tyObject_Result__ilFFiS4FzkKdKwqy8wvy9cQ));		result.o = NIM_FALSE;
#line 700 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 700 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
		result._o_1.e = strupnperror(res);	}
	LA6_: ;
	return result;}

#line 107 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/excpt.nim"
static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
#line 108 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/excpt.nim"
	(*s).prev = excHandler__rqLlY5bs9atDw2OXYqJEn5g;
#line 109 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/excpt.nim"
	excHandler__rqLlY5bs9atDw2OXYqJEn5g = s;}

#line 111 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/excpt.nim"
static N_INLINE(void, popSafePoint)(void) {
#line 112 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/excpt.nim"
	excHandler__rqLlY5bs9atDw2OXYqJEn5g = (*excHandler__rqLlY5bs9atDw2OXYqJEn5g).prev;}

#line 2292 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system.nim"
static N_INLINE(Exception*, nimBorrowCurrentException)(void) {	Exception* result;	result = (Exception*)0;
#line 2295 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system.nim"
	result = currException__9bVPeDJlYTi9bQApZpfH8wjg;	return result;}

#line 119 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/excpt.nim"
static N_INLINE(void, popCurrentException)(void) {
#line 120 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/excpt.nim"
	asgnRef((void**) (&currException__9bVPeDJlYTi9bQApZpfH8wjg), (*currException__9bVPeDJlYTi9bQApZpfH8wjg).up);}

#line 787 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
N_LIB_PRIVATE N_NIMCALL(void, getSpecificPortMapping__QXaIFvOGyyO74C5o05CCfQ)(tyObject_MiniupnpcolonObjectType___ZfgtTEK0E380MDBW1PU9cXw* self, NimStringDesc* externalPort_0, tyEnum_UPNPProtocol__KRPLdnmctmfcFCiWnVJqLw protocol_0, NimStringDesc* remoteHost_0, tyObject_Result__9bn3q9cf2t0jbXRYPFofJMAQ* Result) {	tyObject_PortMappingRes__HAKwlWP34w7w9bH9bs3Ehk1A portMapping;	NimStringDesc* enabledStr;	NimStringDesc* leaseDurationStr;	NCSTRING remHost;	int res;{	chckNil((void*)Result);	switch ((*Result).o) {
	case NIM_FALSE:
	(*Result)._o_1.e = NIM_NIL;	break;
	case NIM_TRUE:
	unsureAsgnRef((void**)&(*Result)._o_2.v.externalPort, NIM_NIL);	unsureAsgnRef((void**)&(*Result)._o_2.v.internalClient, NIM_NIL);	unsureAsgnRef((void**)&(*Result)._o_2.v.internalPort, NIM_NIL);	(*Result)._o_2.v.protocol = 0;	unsureAsgnRef((void**)&(*Result)._o_2.v.description, NIM_NIL);	(*Result)._o_2.v.enabled = 0;	unsureAsgnRef((void**)&(*Result)._o_2.v.remoteHost, NIM_NIL);	(*Result)._o_2.v.leaseDuration = 0;	break;
	} 
	(*Result).o = 0;	nimZeroMem((void*)(&portMapping), sizeof(tyObject_PortMappingRes__HAKwlWP34w7w9bH9bs3Ehk1A));
#line 792 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
	chckNil((void*)(&portMapping));	nimZeroMem((void*)(&portMapping), sizeof(tyObject_PortMappingRes__HAKwlWP34w7w9bH9bs3Ehk1A));	portMapping.externalPort = copyString(externalPort_0);	portMapping.protocol = protocol_0;	portMapping.remoteHost = copyString(remoteHost_0);
#line 795 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 795 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 795 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
	enabledStr = mnewString(((NI) 4));
#line 796 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 796 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 796 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
	leaseDurationStr = mnewString(((NI) 16));
#line 798 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
	portMapping.internalClient = setLengthStr(portMapping.internalClient, ((NI) 40));
#line 799 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
	portMapping.internalPort = setLengthStr(portMapping.internalPort, ((NI) 6));
#line 800 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
	portMapping.description = setLengthStr(portMapping.description, ((NI) 80));
#line 801 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
	remHost = nimToCStringConv(remoteHost_0);
#line 802 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
	{
#line 802 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
		if (!((remoteHost_0 ? remoteHost_0->Sup.len : 0) == 0)) goto LA3_;

#line 803 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
		remHost = NIM_NIL;	}
	LA3_: ;

#line 804 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 807 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 804 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
	res = UPNP_GetSpecificPortMappingEntry((*self).urls.controlURL, ((NCSTRING) ((*self).data.first.servicetype)), nimToCStringConv(externalPort_0), nimToCStringConv(reprEnum((NI)protocol_0, (&NTI__KRPLdnmctmfcFCiWnVJqLw_))), remHost, nimToCStringConv(portMapping.internalClient), nimToCStringConv(portMapping.internalPort), nimToCStringConv(portMapping.description), nimToCStringConv(enabledStr), nimToCStringConv(leaseDurationStr));
#line 814 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
	{		TSafePoint TM__XQYS3he3QszP5orM2CZQnw_8;		TSafePoint TM__XQYS3he3QszP5orM2CZQnw_9;
#line 814 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
		if (!(res == ((int) 0))) goto LA7_;

#line 815 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 815 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
		trimString__MU9c9bW9a4guA5eApxkZIsPsQ((&portMapping.internalClient));

#line 816 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 816 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
		trimString__MU9c9bW9a4guA5eApxkZIsPsQ((&portMapping.internalPort));

#line 817 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 817 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
		trimString__MU9c9bW9a4guA5eApxkZIsPsQ((&portMapping.description));

#line 818 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 818 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
		trimString__MU9c9bW9a4guA5eApxkZIsPsQ((&enabledStr));

#line 819 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 819 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
		pushSafePoint(&TM__XQYS3he3QszP5orM2CZQnw_8);		TM__XQYS3he3QszP5orM2CZQnw_8.status = setjmp(TM__XQYS3he3QszP5orM2CZQnw_8.context);		if (TM__XQYS3he3QszP5orM2CZQnw_8.status == 0) {			NI T10_;
#line 820 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 820 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
			T10_ = (NI)0;			T10_ = nsuParseInt(enabledStr);			portMapping.enabled = ((T10_) != 0);			popSafePoint();		}
		else {			popSafePoint();			if (isObj(nimBorrowCurrentException()->Sup.m_type, (&NTI__yoNlBGx0D2tRizIdhQuENw_))) {				TM__XQYS3he3QszP5orM2CZQnw_8.status = 0;				portMapping.enabled = NIM_FALSE;				popCurrentException();			}
		}
		if (TM__XQYS3he3QszP5orM2CZQnw_8.status != 0) reraiseException();
#line 823 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 823 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
		trimString__MU9c9bW9a4guA5eApxkZIsPsQ((&leaseDurationStr));

#line 825 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 825 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
		pushSafePoint(&TM__XQYS3he3QszP5orM2CZQnw_9);		TM__XQYS3he3QszP5orM2CZQnw_9.status = setjmp(TM__XQYS3he3QszP5orM2CZQnw_9.context);		if (TM__XQYS3he3QszP5orM2CZQnw_9.status == 0) {
#line 826 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 826 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
			portMapping.leaseDuration = nsuParseBiggestUInt(leaseDurationStr);			popSafePoint();		}
		else {			popSafePoint();			if (isObj(nimBorrowCurrentException()->Sup.m_type, (&NTI__yoNlBGx0D2tRizIdhQuENw_))) {				TM__XQYS3he3QszP5orM2CZQnw_9.status = 0;
#line 828 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 828 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
				chckNil((void*)Result);				switch ((*Result).o) {
				case NIM_FALSE:
				(*Result)._o_1.e = NIM_NIL;				break;
				case NIM_TRUE:
				unsureAsgnRef((void**)&(*Result)._o_2.v.externalPort, NIM_NIL);				unsureAsgnRef((void**)&(*Result)._o_2.v.internalClient, NIM_NIL);				unsureAsgnRef((void**)&(*Result)._o_2.v.internalPort, NIM_NIL);				(*Result)._o_2.v.protocol = 0;				unsureAsgnRef((void**)&(*Result)._o_2.v.description, NIM_NIL);				(*Result)._o_2.v.enabled = 0;				unsureAsgnRef((void**)&(*Result)._o_2.v.remoteHost, NIM_NIL);				(*Result)._o_2.v.leaseDuration = 0;				break;
				} 
				(*Result).o = 0;				(*Result).o = NIM_FALSE;				(*Result)._o_1.e = "upnp: cannot parsse lease duration";				popCurrentException();				goto BeforeRet_;
				popCurrentException();			}
		}
		if (TM__XQYS3he3QszP5orM2CZQnw_9.status != 0) reraiseException();
#line 300 "/home/runner/work/nim-waku/nim-waku/vendor/nim-stew/stew/results.nim"
		chckNil((void*)Result);		switch ((*Result).o) {
		case NIM_FALSE:
		(*Result)._o_1.e = NIM_NIL;		break;
		case NIM_TRUE:
		unsureAsgnRef((void**)&(*Result)._o_2.v.externalPort, NIM_NIL);		unsureAsgnRef((void**)&(*Result)._o_2.v.internalClient, NIM_NIL);		unsureAsgnRef((void**)&(*Result)._o_2.v.internalPort, NIM_NIL);		(*Result)._o_2.v.protocol = 0;		unsureAsgnRef((void**)&(*Result)._o_2.v.description, NIM_NIL);		(*Result)._o_2.v.enabled = 0;		unsureAsgnRef((void**)&(*Result)._o_2.v.remoteHost, NIM_NIL);		(*Result)._o_2.v.leaseDuration = 0;		break;
		} 
		(*Result).o = 0;		(*Result).o = NIM_TRUE;		genericAssign((void*)(&(*Result)._o_2.v), (void*)(&portMapping), (&NTI__HAKwlWP34w7w9bH9bs3Ehk1A_));	}
	goto LA5_;
	LA7_: ;
	{
#line 319 "/home/runner/work/nim-waku/nim-waku/vendor/nim-stew/stew/results.nim"
		chckNil((void*)Result);		switch ((*Result).o) {
		case NIM_FALSE:
		(*Result)._o_1.e = NIM_NIL;		break;
		case NIM_TRUE:
		unsureAsgnRef((void**)&(*Result)._o_2.v.externalPort, NIM_NIL);		unsureAsgnRef((void**)&(*Result)._o_2.v.internalClient, NIM_NIL);		unsureAsgnRef((void**)&(*Result)._o_2.v.internalPort, NIM_NIL);		(*Result)._o_2.v.protocol = 0;		unsureAsgnRef((void**)&(*Result)._o_2.v.description, NIM_NIL);		(*Result)._o_2.v.enabled = 0;		unsureAsgnRef((void**)&(*Result)._o_2.v.remoteHost, NIM_NIL);		(*Result)._o_2.v.leaseDuration = 0;		break;
		} 
		(*Result).o = 0;		(*Result).o = NIM_FALSE;
#line 831 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 831 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
		(*Result)._o_1.e = strupnperror(res);	}
	LA5_: ;
	}BeforeRet_: ;
}

#line 733 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_Result__ilFFiS4FzkKdKwqy8wvy9cQ, deletePortMapping__V0VrzQWk5TFfdMYrUuoREA)(tyObject_MiniupnpcolonObjectType___ZfgtTEK0E380MDBW1PU9cXw* self, NimStringDesc* externalPort_0, tyEnum_UPNPProtocol__KRPLdnmctmfcFCiWnVJqLw protocol_0, NimStringDesc* remoteHost_0) {	tyObject_Result__ilFFiS4FzkKdKwqy8wvy9cQ result;	NCSTRING remHost;	int res;	nimZeroMem((void*)(&result), sizeof(tyObject_Result__ilFFiS4FzkKdKwqy8wvy9cQ));
#line 737 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
	remHost = nimToCStringConv(remoteHost_0);
#line 738 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
	{
#line 738 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
		if (!((remoteHost_0 ? remoteHost_0->Sup.len : 0) == 0)) goto LA3_;

#line 739 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
		remHost = NIM_NIL;	}
	LA3_: ;

#line 740 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 743 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 740 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
	res = UPNP_DeletePortMapping((*self).urls.controlURL, ((NCSTRING) ((*self).data.first.servicetype)), nimToCStringConv(externalPort_0), nimToCStringConv(reprEnum((NI)protocol_0, (&NTI__KRPLdnmctmfcFCiWnVJqLw_))), remHost);
#line 745 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
	{
#line 745 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
		if (!(res == ((int) 0))) goto LA7_;

#line 300 "/home/runner/work/nim-waku/nim-waku/vendor/nim-stew/stew/results.nim"
		chckNil((void*)(&result));		nimZeroMem((void*)(&result), sizeof(tyObject_Result__ilFFiS4FzkKdKwqy8wvy9cQ));		result.o = NIM_TRUE;		result._o_2.v = NIM_TRUE;	}
	goto LA5_;
	LA7_: ;
	{
#line 319 "/home/runner/work/nim-waku/nim-waku/vendor/nim-stew/stew/results.nim"
		chckNil((void*)(&result));		nimZeroMem((void*)(&result), sizeof(tyObject_Result__ilFFiS4FzkKdKwqy8wvy9cQ));		result.o = NIM_FALSE;
#line 748 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"

#line 748 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/miniupnpc.nim"
		result._o_1.e = strupnperror(res);	}
	LA5_: ;
	return result;}
N_LIB_PRIVATE N_NIMCALL(void, nat_traversal_miniupnpcInit000)(void) {

#line 999999 "generated_not_to_break_here"
{

#line 24 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/utils.nim"
	MINIUPNPC_VERSION__lfnjdZerCuHsF9aL1knji9aA = MINIUPNPC_VERSION;
#line 24 "/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/nat_traversal/utils.nim"
	MINIUPNPC_API_VERSION__5N6HtfEkbAUMBBvHSrCbMA = MINIUPNPC_API_VERSION;}
}

N_LIB_PRIVATE N_NIMCALL(void, nat_traversal_miniupnpcDatInit000)(void) {

#line 999999 "generated_not_to_break_here"
static TNimNode* TM__XQYS3he3QszP5orM2CZQnw_2_11[11];
static TNimNode* TM__XQYS3he3QszP5orM2CZQnw_5_2[2];
NI TM__XQYS3he3QszP5orM2CZQnw_7;
static char* NIM_CONST TM__XQYS3he3QszP5orM2CZQnw_6[2] = {
"TCP", 
"UDP"};
static TNimNode* TM__XQYS3he3QszP5orM2CZQnw_10_8[8];
static TNimNode TM__XQYS3he3QszP5orM2CZQnw_0[27];NTI__ZfgtTEK0E380MDBW1PU9cXw_.size = sizeof(tyObject_MiniupnpcolonObjectType___ZfgtTEK0E380MDBW1PU9cXw);
NTI__ZfgtTEK0E380MDBW1PU9cXw_.kind = 18;
NTI__ZfgtTEK0E380MDBW1PU9cXw_.base = 0;
NTI__ZfgtTEK0E380MDBW1PU9cXw_.flags = 2;
NTI__ZfgtTEK0E380MDBW1PU9cXw_.name = "Miniupnp:ObjectType";
NTI__ZfgtTEK0E380MDBW1PU9cXw_.nextType = nimTypeRoot; nimTypeRoot=&NTI__ZfgtTEK0E380MDBW1PU9cXw_;
TM__XQYS3he3QszP5orM2CZQnw_2_11[0] = &TM__XQYS3he3QszP5orM2CZQnw_0[1];
NTI__tvfSgzlA9aG9aeo6fCNw9bCMA_.size = sizeof(struct UPNPDev);
NTI__tvfSgzlA9aG9aeo6fCNw9bCMA_.kind = 18;
NTI__tvfSgzlA9aG9aeo6fCNw9bCMA_.base = 0;
NTI__tvfSgzlA9aG9aeo6fCNw9bCMA_.flags = 3;
NTI__tvfSgzlA9aG9aeo6fCNw9bCMA_.name = "UPNPDev";
NTI__tvfSgzlA9aG9aeo6fCNw9bCMA_.nextType = nimTypeRoot; nimTypeRoot=&NTI__tvfSgzlA9aG9aeo6fCNw9bCMA_;
NTI__tvfSgzlA9aG9aeo6fCNw9bCMA_.node = &TM__XQYS3he3QszP5orM2CZQnw_0[2];
NTI__PbuwXN9cgq8yGJnIU9agTTuQ_.size = sizeof(struct UPNPDev*);
NTI__PbuwXN9cgq8yGJnIU9agTTuQ_.kind = 21;
NTI__PbuwXN9cgq8yGJnIU9agTTuQ_.base = (&NTI__tvfSgzlA9aG9aeo6fCNw9bCMA_);
NTI__PbuwXN9cgq8yGJnIU9agTTuQ_.flags = 3;
NTI__PbuwXN9cgq8yGJnIU9agTTuQ_.name = "ptr UPNPDev";
NTI__PbuwXN9cgq8yGJnIU9agTTuQ_.nextType = nimTypeRoot; nimTypeRoot=&NTI__PbuwXN9cgq8yGJnIU9agTTuQ_;
TM__XQYS3he3QszP5orM2CZQnw_0[1].kind = 1;
TM__XQYS3he3QszP5orM2CZQnw_0[1].offset = offsetof(tyObject_MiniupnpcolonObjectType___ZfgtTEK0E380MDBW1PU9cXw, devList);
TM__XQYS3he3QszP5orM2CZQnw_0[1].typ = (&NTI__PbuwXN9cgq8yGJnIU9agTTuQ_);
TM__XQYS3he3QszP5orM2CZQnw_0[1].name = "devList";
TM__XQYS3he3QszP5orM2CZQnw_2_11[1] = &TM__XQYS3he3QszP5orM2CZQnw_0[3];
NTI__9boSe1qwO6bN9bkqJidA0B1Q_.size = sizeof(struct UPNPUrls);
NTI__9boSe1qwO6bN9bkqJidA0B1Q_.kind = 18;
NTI__9boSe1qwO6bN9bkqJidA0B1Q_.base = 0;
NTI__9boSe1qwO6bN9bkqJidA0B1Q_.flags = 3;
NTI__9boSe1qwO6bN9bkqJidA0B1Q_.name = "UPNPUrls";
NTI__9boSe1qwO6bN9bkqJidA0B1Q_.nextType = nimTypeRoot; nimTypeRoot=&NTI__9boSe1qwO6bN9bkqJidA0B1Q_;
NTI__9boSe1qwO6bN9bkqJidA0B1Q_.node = &TM__XQYS3he3QszP5orM2CZQnw_0[4];
TM__XQYS3he3QszP5orM2CZQnw_0[3].kind = 1;
TM__XQYS3he3QszP5orM2CZQnw_0[3].offset = offsetof(tyObject_MiniupnpcolonObjectType___ZfgtTEK0E380MDBW1PU9cXw, urls);
TM__XQYS3he3QszP5orM2CZQnw_0[3].typ = (&NTI__9boSe1qwO6bN9bkqJidA0B1Q_);
TM__XQYS3he3QszP5orM2CZQnw_0[3].name = "urls";
TM__XQYS3he3QszP5orM2CZQnw_2_11[2] = &TM__XQYS3he3QszP5orM2CZQnw_0[5];
NTI__3sRdAXq0yC3Bmz39avLPKNA_.size = sizeof(struct IGDdatas);
NTI__3sRdAXq0yC3Bmz39avLPKNA_.kind = 18;
NTI__3sRdAXq0yC3Bmz39avLPKNA_.base = 0;
NTI__3sRdAXq0yC3Bmz39avLPKNA_.flags = 3;
NTI__3sRdAXq0yC3Bmz39avLPKNA_.name = "IGDdatas";
NTI__3sRdAXq0yC3Bmz39avLPKNA_.nextType = nimTypeRoot; nimTypeRoot=&NTI__3sRdAXq0yC3Bmz39avLPKNA_;
NTI__3sRdAXq0yC3Bmz39avLPKNA_.node = &TM__XQYS3he3QszP5orM2CZQnw_0[6];
TM__XQYS3he3QszP5orM2CZQnw_0[5].kind = 1;
TM__XQYS3he3QszP5orM2CZQnw_0[5].offset = offsetof(tyObject_MiniupnpcolonObjectType___ZfgtTEK0E380MDBW1PU9cXw, data);
TM__XQYS3he3QszP5orM2CZQnw_0[5].typ = (&NTI__3sRdAXq0yC3Bmz39avLPKNA_);
TM__XQYS3he3QszP5orM2CZQnw_0[5].name = "data";
TM__XQYS3he3QszP5orM2CZQnw_2_11[3] = &TM__XQYS3he3QszP5orM2CZQnw_0[7];
TM__XQYS3he3QszP5orM2CZQnw_0[7].kind = 1;
TM__XQYS3he3QszP5orM2CZQnw_0[7].offset = offsetof(tyObject_MiniupnpcolonObjectType___ZfgtTEK0E380MDBW1PU9cXw, discoverDelay);
TM__XQYS3he3QszP5orM2CZQnw_0[7].typ = (&NTI__nlCscttRCss70IBTyuBqnA_);
TM__XQYS3he3QszP5orM2CZQnw_0[7].name = "discoverDelay";
TM__XQYS3he3QszP5orM2CZQnw_2_11[4] = &TM__XQYS3he3QszP5orM2CZQnw_0[8];
TM__XQYS3he3QszP5orM2CZQnw_0[8].kind = 1;
TM__XQYS3he3QszP5orM2CZQnw_0[8].offset = offsetof(tyObject_MiniupnpcolonObjectType___ZfgtTEK0E380MDBW1PU9cXw, multicastIF);
TM__XQYS3he3QszP5orM2CZQnw_0[8].typ = (&NTI__77mFvmsOLKik79ci2hXkHEg_);
TM__XQYS3he3QszP5orM2CZQnw_0[8].name = "multicastIF";
TM__XQYS3he3QszP5orM2CZQnw_2_11[5] = &TM__XQYS3he3QszP5orM2CZQnw_0[9];
TM__XQYS3he3QszP5orM2CZQnw_0[9].kind = 1;
TM__XQYS3he3QszP5orM2CZQnw_0[9].offset = offsetof(tyObject_MiniupnpcolonObjectType___ZfgtTEK0E380MDBW1PU9cXw, miniSsdpdSocket);
TM__XQYS3he3QszP5orM2CZQnw_0[9].typ = (&NTI__77mFvmsOLKik79ci2hXkHEg_);
TM__XQYS3he3QszP5orM2CZQnw_0[9].name = "miniSsdpdSocket";
TM__XQYS3he3QszP5orM2CZQnw_2_11[6] = &TM__XQYS3he3QszP5orM2CZQnw_0[10];
TM__XQYS3he3QszP5orM2CZQnw_0[10].kind = 1;
TM__XQYS3he3QszP5orM2CZQnw_0[10].offset = offsetof(tyObject_MiniupnpcolonObjectType___ZfgtTEK0E380MDBW1PU9cXw, localPort);
TM__XQYS3he3QszP5orM2CZQnw_0[10].typ = (&NTI__nlCscttRCss70IBTyuBqnA_);
TM__XQYS3he3QszP5orM2CZQnw_0[10].name = "localPort";
TM__XQYS3he3QszP5orM2CZQnw_2_11[7] = &TM__XQYS3he3QszP5orM2CZQnw_0[11];
TM__XQYS3he3QszP5orM2CZQnw_0[11].kind = 1;
TM__XQYS3he3QszP5orM2CZQnw_0[11].offset = offsetof(tyObject_MiniupnpcolonObjectType___ZfgtTEK0E380MDBW1PU9cXw, ipv6);
TM__XQYS3he3QszP5orM2CZQnw_0[11].typ = (&NTI__nlCscttRCss70IBTyuBqnA_);
TM__XQYS3he3QszP5orM2CZQnw_0[11].name = "ipv6";
TM__XQYS3he3QszP5orM2CZQnw_2_11[8] = &TM__XQYS3he3QszP5orM2CZQnw_0[12];
TM__XQYS3he3QszP5orM2CZQnw_0[12].kind = 1;
TM__XQYS3he3QszP5orM2CZQnw_0[12].offset = offsetof(tyObject_MiniupnpcolonObjectType___ZfgtTEK0E380MDBW1PU9cXw, ttl);
TM__XQYS3he3QszP5orM2CZQnw_0[12].typ = (&NTI__aai9cIdjrwazYp9aHakMchqw_);
TM__XQYS3he3QszP5orM2CZQnw_0[12].name = "ttl";
TM__XQYS3he3QszP5orM2CZQnw_2_11[9] = &TM__XQYS3he3QszP5orM2CZQnw_0[13];
TM__XQYS3he3QszP5orM2CZQnw_0[13].kind = 1;
TM__XQYS3he3QszP5orM2CZQnw_0[13].offset = offsetof(tyObject_MiniupnpcolonObjectType___ZfgtTEK0E380MDBW1PU9cXw, error);
TM__XQYS3he3QszP5orM2CZQnw_0[13].typ = (&NTI__nlCscttRCss70IBTyuBqnA_);
TM__XQYS3he3QszP5orM2CZQnw_0[13].name = "error";
TM__XQYS3he3QszP5orM2CZQnw_2_11[10] = &TM__XQYS3he3QszP5orM2CZQnw_0[14];
TM__XQYS3he3QszP5orM2CZQnw_0[14].kind = 1;
TM__XQYS3he3QszP5orM2CZQnw_0[14].offset = offsetof(tyObject_MiniupnpcolonObjectType___ZfgtTEK0E380MDBW1PU9cXw, lanAddr);
TM__XQYS3he3QszP5orM2CZQnw_0[14].typ = (&NTI__77mFvmsOLKik79ci2hXkHEg_);
TM__XQYS3he3QszP5orM2CZQnw_0[14].name = "lanAddr";
TM__XQYS3he3QszP5orM2CZQnw_0[0].len = 11; TM__XQYS3he3QszP5orM2CZQnw_0[0].kind = 2; TM__XQYS3he3QszP5orM2CZQnw_0[0].sons = &TM__XQYS3he3QszP5orM2CZQnw_2_11[0];
NTI__ZfgtTEK0E380MDBW1PU9cXw_.node = &TM__XQYS3he3QszP5orM2CZQnw_0[0];
NTI__ZfgtTEK0E380MDBW1PU9cXw_.deepcopy =(void* (N_RAW_NIMCALL*)(void*))eqdeepCopy___KCCVaHQ9bOwoHZKFNWPsmEQ;
NTI__9aELMDPtAVkfnKCx8AU54Kg_.size = sizeof(tyObject_MiniupnpcolonObjectType___ZfgtTEK0E380MDBW1PU9cXw*);
NTI__9aELMDPtAVkfnKCx8AU54Kg_.kind = 22;
NTI__9aELMDPtAVkfnKCx8AU54Kg_.base = (&NTI__ZfgtTEK0E380MDBW1PU9cXw_);
NTI__9aELMDPtAVkfnKCx8AU54Kg_.flags = 2;
NTI__9aELMDPtAVkfnKCx8AU54Kg_.name = "Miniupnp";
NTI__9aELMDPtAVkfnKCx8AU54Kg_.nextType = nimTypeRoot; nimTypeRoot=&NTI__9aELMDPtAVkfnKCx8AU54Kg_;
NTI__9aELMDPtAVkfnKCx8AU54Kg_.marker = Marker_tyRef__9aELMDPtAVkfnKCx8AU54Kg;
NTI__KRPLdnmctmfcFCiWnVJqLw_.size = sizeof(tyEnum_UPNPProtocol__KRPLdnmctmfcFCiWnVJqLw);
NTI__KRPLdnmctmfcFCiWnVJqLw_.kind = 14;
NTI__KRPLdnmctmfcFCiWnVJqLw_.base = 0;
NTI__KRPLdnmctmfcFCiWnVJqLw_.flags = 3;
NTI__KRPLdnmctmfcFCiWnVJqLw_.name = "UPNPProtocol";
NTI__KRPLdnmctmfcFCiWnVJqLw_.nextType = nimTypeRoot; nimTypeRoot=&NTI__KRPLdnmctmfcFCiWnVJqLw_;
for (TM__XQYS3he3QszP5orM2CZQnw_7 = 0; TM__XQYS3he3QszP5orM2CZQnw_7 < 2; TM__XQYS3he3QszP5orM2CZQnw_7++) {
TM__XQYS3he3QszP5orM2CZQnw_0[TM__XQYS3he3QszP5orM2CZQnw_7+15].kind = 1;
TM__XQYS3he3QszP5orM2CZQnw_0[TM__XQYS3he3QszP5orM2CZQnw_7+15].offset = TM__XQYS3he3QszP5orM2CZQnw_7;
TM__XQYS3he3QszP5orM2CZQnw_0[TM__XQYS3he3QszP5orM2CZQnw_7+15].name = TM__XQYS3he3QszP5orM2CZQnw_6[TM__XQYS3he3QszP5orM2CZQnw_7];
TM__XQYS3he3QszP5orM2CZQnw_5_2[TM__XQYS3he3QszP5orM2CZQnw_7] = &TM__XQYS3he3QszP5orM2CZQnw_0[TM__XQYS3he3QszP5orM2CZQnw_7+15];
}
TM__XQYS3he3QszP5orM2CZQnw_0[17].len = 2; TM__XQYS3he3QszP5orM2CZQnw_0[17].kind = 2; TM__XQYS3he3QszP5orM2CZQnw_0[17].sons = &TM__XQYS3he3QszP5orM2CZQnw_5_2[0];
NTI__KRPLdnmctmfcFCiWnVJqLw_.node = &TM__XQYS3he3QszP5orM2CZQnw_0[17];
NTI__HAKwlWP34w7w9bH9bs3Ehk1A_.size = sizeof(tyObject_PortMappingRes__HAKwlWP34w7w9bH9bs3Ehk1A);
NTI__HAKwlWP34w7w9bH9bs3Ehk1A_.kind = 18;
NTI__HAKwlWP34w7w9bH9bs3Ehk1A_.base = 0;
NTI__HAKwlWP34w7w9bH9bs3Ehk1A_.flags = 2;
NTI__HAKwlWP34w7w9bH9bs3Ehk1A_.name = "PortMappingRes";
NTI__HAKwlWP34w7w9bH9bs3Ehk1A_.nextType = nimTypeRoot; nimTypeRoot=&NTI__HAKwlWP34w7w9bH9bs3Ehk1A_;
TM__XQYS3he3QszP5orM2CZQnw_10_8[0] = &TM__XQYS3he3QszP5orM2CZQnw_0[19];
TM__XQYS3he3QszP5orM2CZQnw_0[19].kind = 1;
TM__XQYS3he3QszP5orM2CZQnw_0[19].offset = offsetof(tyObject_PortMappingRes__HAKwlWP34w7w9bH9bs3Ehk1A, externalPort);
TM__XQYS3he3QszP5orM2CZQnw_0[19].typ = (&NTI__77mFvmsOLKik79ci2hXkHEg_);
TM__XQYS3he3QszP5orM2CZQnw_0[19].name = "externalPort";
TM__XQYS3he3QszP5orM2CZQnw_10_8[1] = &TM__XQYS3he3QszP5orM2CZQnw_0[20];
TM__XQYS3he3QszP5orM2CZQnw_0[20].kind = 1;
TM__XQYS3he3QszP5orM2CZQnw_0[20].offset = offsetof(tyObject_PortMappingRes__HAKwlWP34w7w9bH9bs3Ehk1A, internalClient);
TM__XQYS3he3QszP5orM2CZQnw_0[20].typ = (&NTI__77mFvmsOLKik79ci2hXkHEg_);
TM__XQYS3he3QszP5orM2CZQnw_0[20].name = "internalClient";
TM__XQYS3he3QszP5orM2CZQnw_10_8[2] = &TM__XQYS3he3QszP5orM2CZQnw_0[21];
TM__XQYS3he3QszP5orM2CZQnw_0[21].kind = 1;
TM__XQYS3he3QszP5orM2CZQnw_0[21].offset = offsetof(tyObject_PortMappingRes__HAKwlWP34w7w9bH9bs3Ehk1A, internalPort);
TM__XQYS3he3QszP5orM2CZQnw_0[21].typ = (&NTI__77mFvmsOLKik79ci2hXkHEg_);
TM__XQYS3he3QszP5orM2CZQnw_0[21].name = "internalPort";
TM__XQYS3he3QszP5orM2CZQnw_10_8[3] = &TM__XQYS3he3QszP5orM2CZQnw_0[22];
TM__XQYS3he3QszP5orM2CZQnw_0[22].kind = 1;
TM__XQYS3he3QszP5orM2CZQnw_0[22].offset = offsetof(tyObject_PortMappingRes__HAKwlWP34w7w9bH9bs3Ehk1A, protocol);
TM__XQYS3he3QszP5orM2CZQnw_0[22].typ = (&NTI__KRPLdnmctmfcFCiWnVJqLw_);
TM__XQYS3he3QszP5orM2CZQnw_0[22].name = "protocol";
TM__XQYS3he3QszP5orM2CZQnw_10_8[4] = &TM__XQYS3he3QszP5orM2CZQnw_0[23];
TM__XQYS3he3QszP5orM2CZQnw_0[23].kind = 1;
TM__XQYS3he3QszP5orM2CZQnw_0[23].offset = offsetof(tyObject_PortMappingRes__HAKwlWP34w7w9bH9bs3Ehk1A, description);
TM__XQYS3he3QszP5orM2CZQnw_0[23].typ = (&NTI__77mFvmsOLKik79ci2hXkHEg_);
TM__XQYS3he3QszP5orM2CZQnw_0[23].name = "description";
TM__XQYS3he3QszP5orM2CZQnw_10_8[5] = &TM__XQYS3he3QszP5orM2CZQnw_0[24];
TM__XQYS3he3QszP5orM2CZQnw_0[24].kind = 1;
TM__XQYS3he3QszP5orM2CZQnw_0[24].offset = offsetof(tyObject_PortMappingRes__HAKwlWP34w7w9bH9bs3Ehk1A, enabled);
TM__XQYS3he3QszP5orM2CZQnw_0[24].typ = (&NTI__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__XQYS3he3QszP5orM2CZQnw_0[24].name = "enabled";
TM__XQYS3he3QszP5orM2CZQnw_10_8[6] = &TM__XQYS3he3QszP5orM2CZQnw_0[25];
TM__XQYS3he3QszP5orM2CZQnw_0[25].kind = 1;
TM__XQYS3he3QszP5orM2CZQnw_0[25].offset = offsetof(tyObject_PortMappingRes__HAKwlWP34w7w9bH9bs3Ehk1A, remoteHost);
TM__XQYS3he3QszP5orM2CZQnw_0[25].typ = (&NTI__77mFvmsOLKik79ci2hXkHEg_);
TM__XQYS3he3QszP5orM2CZQnw_0[25].name = "remoteHost";
TM__XQYS3he3QszP5orM2CZQnw_10_8[7] = &TM__XQYS3he3QszP5orM2CZQnw_0[26];
TM__XQYS3he3QszP5orM2CZQnw_0[26].kind = 1;
TM__XQYS3he3QszP5orM2CZQnw_0[26].offset = offsetof(tyObject_PortMappingRes__HAKwlWP34w7w9bH9bs3Ehk1A, leaseDuration);
TM__XQYS3he3QszP5orM2CZQnw_0[26].typ = (&NTI__wMtfD88jmrPZwfzTH9c8e9cA_);
TM__XQYS3he3QszP5orM2CZQnw_0[26].name = "leaseDuration";
TM__XQYS3he3QszP5orM2CZQnw_0[18].len = 8; TM__XQYS3he3QszP5orM2CZQnw_0[18].kind = 2; TM__XQYS3he3QszP5orM2CZQnw_0[18].sons = &TM__XQYS3he3QszP5orM2CZQnw_10_8[0];
NTI__HAKwlWP34w7w9bH9bs3Ehk1A_.node = &TM__XQYS3he3QszP5orM2CZQnw_0[18];
}

