/* Generated by Nim Compiler v1.2.6 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -pthread -I/home/runner/work/nim-waku/nim-waku/vendor/nim-libbacktrace -I/home/runner/work/nim-waku/nim-waku/vendor/nim-libbacktrace/install/usr/include -I/home/runner/work/nim-waku/nim-waku/vendor/nim-secp256k1/secp256k1_wrapper -I/home/runner/work/nim-waku/nim-waku/vendor/nim-secp256k1/secp256k1_wrapper/secp256k1 -I/home/runner/work/nim-waku/nim-waku/vendor/nim-secp256k1/secp256k1_wrapper/secp256k1/src -DHAVE_CONFIG_H -DHAVE_BUILTIN_EXPECT -I/home/runner/work/nim-waku/nim-waku/vendor/nim-bearssl/bearssl/csources/src -I/home/runner/work/nim-waku/nim-waku/vendor/nim-bearssl/bearssl/csources/inc -I/home/runner/work/nim-waku/nim-waku/vendor/nim-bearssl/bearssl/csources/tools -DBR_USE_UNIX_TIME=1 -DBR_USE_URANDOM=1 -DBR_LE_UNALIGNED=1 -DBR_64=1  -DBR_amd64=1 -DBR_INT128=1 -I/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/vendor/miniupnp/miniupnpc -I/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/vendor/libnatpmp-upstream -DENABLE_STRNATPMPERR -I/home/runner/work/nim-waku/nim-waku/vendor/nim-bearssl/bearssl/certs -march=native -g3 -Og -O3 -fno-strict-aliasing -fno-ident  -I/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib -I/home/runner/work/nim-waku/nim-waku/waku/common -o nimcache/release/wakubridge/stdlib_wordwrap.nim.c.o nimcache/release/wakubridge/stdlib_wordwrap.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct TGenericSeq {NI len;
NI reserved;
};
struct NimStringDesc {  TGenericSeq Sup;NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(NI, olen__0dw7gZET9cKXvkxNm43MHRA)(NimStringDesc* s_0, NI start, NI lastExclusive);
N_LIB_PRIVATE N_NIMCALL(NI, graphemeLen__PLnPtAcI9ac8BvVcA3e5o7w)(NimStringDesc* s_0, NI i);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem__i80o3k0SgEI5gTRCzYdyWAsystem)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);

#line 14 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
N_LIB_PRIVATE N_NIMCALL(NI, olen__0dw7gZET9cKXvkxNm43MHRA)(NimStringDesc* s_0, NI start, NI lastExclusive) {	NI result;	NI i;	result = (NI)0;
#line 15 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
	i = start;
#line 16 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
	result = ((NI) 0);	{
#line 17 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
		while (1) {			NI TM__IobAM6Jeru9cnaKaai8r4Ug_6;			NI L;			NI TM__IobAM6Jeru9cnaKaai8r4Ug_7;
#line 17 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
			if (!(i < lastExclusive)) goto LA2;

#line 18 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
			if (nimAddInt(result, ((NI) 1), &TM__IobAM6Jeru9cnaKaai8r4Ug_6)) { raiseOverflow(); };			result = (NI)(TM__IobAM6Jeru9cnaKaai8r4Ug_6);
#line 19 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
			if ((i) < ((NI) 0) || (i) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(i, ((NI) 0), ((NI) IL64(9223372036854775807))); }
#line 19 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
			L = graphemeLen__PLnPtAcI9ac8BvVcA3e5o7w(s_0, ((NI) (i)));
#line 20 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
			if (nimAddInt(i, ((NI) (L)), &TM__IobAM6Jeru9cnaKaai8r4Ug_7)) { raiseOverflow(); };			i = (NI)(TM__IobAM6Jeru9cnaKaai8r4Ug_7);		} LA2: ;
	}
	return result;}

#line 11 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {	void* T1_;
#line 13 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"

#line 13 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memcpy(dest, source, ((size_t) (size)));}

#line 2112 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system.nim"
static N_INLINE(void, copyMem__i80o3k0SgEI5gTRCzYdyWAsystem)(void* dest, void* source, NI size) {
#line 2113 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system.nim"

#line 2113 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system.nim"
	nimCopyMem(dest, source, size);
}

#line 217 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/sysstr.nim"
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
#line 218 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/sysstr.nim"
	{
#line 218 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/sysstr.nim"

#line 218 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/sysstr.nim"
		if (!!((src == NIM_NIL))) goto LA3_;

#line 219 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/sysstr.nim"

#line 219 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/sysstr.nim"

#line 219 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/sysstr.nim"
		copyMem__i80o3k0SgEI5gTRCzYdyWAsystem(((void*) ((&(*dest).data[(*dest).Sup.len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));

#line 220 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/sysstr.nim"
		(*dest).Sup.len += (*src).Sup.len;	}
	LA3_: ;
}

#line 22 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, wrapWords__T8gYSir9ao1V9bYDExwUzAPg)(NimStringDesc* s_0, NI maxLineWidth, NIM_BOOL splitLongWords, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw seps, NimStringDesc* newLine) {	NimStringDesc* result;	NI TM__IobAM6Jeru9cnaKaai8r4Ug_2;	NI spaceLeft;	NimStringDesc* lastSep;	NI i;	result = (NimStringDesc*)0;
#line 32 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"

#line 32 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"

#line 32 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"

#line 32 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"

#line 32 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"

#line 32 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
	if (nimAddInt((s_0 ? s_0->Sup.len : 0), (NI)((NI64)((s_0 ? s_0->Sup.len : 0)) >> (NU64)(((NI) 6))), &TM__IobAM6Jeru9cnaKaai8r4Ug_2)) { raiseOverflow(); };	if (((NI)(TM__IobAM6Jeru9cnaKaai8r4Ug_2)) < ((NI) 0) || ((NI)(TM__IobAM6Jeru9cnaKaai8r4Ug_2)) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__IobAM6Jeru9cnaKaai8r4Ug_2), ((NI) 0), ((NI) IL64(9223372036854775807))); }
#line 32 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
	result = rawNewString(((NI) ((NI)(TM__IobAM6Jeru9cnaKaai8r4Ug_2))));
#line 33 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
	spaceLeft = maxLineWidth;
#line 34 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
	lastSep = ((NimStringDesc*) NIM_NIL);
#line 36 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
	i = ((NI) 0);	{
#line 37 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
		while (1) {			NI j;			NIM_BOOL isSep;			NIM_BOOL T3_;
#line 38 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
			j = i;
#line 39 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"

#line 39 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
			T3_ = (NIM_BOOL)0;
#line 39 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"

#line 39 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
			T3_ = (j < (s_0 ? s_0->Sup.len : 0));			if (!(T3_)) goto LA4_;

#line 39 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
			if ((NU)(j) >= (NU)(s_0 ? s_0->Sup.len : 0)){ raiseIndexError2(j,(s_0 ? s_0->Sup.len : 0)-1); }			T3_ = ((seps[(NU)(((NU8)(s_0->data[j])))>>3] &(1U<<((NU)(((NU8)(s_0->data[j])))&7U)))!=0);			LA4_: ;
			isSep = T3_;			{
#line 40 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
				while (1) {					NIM_BOOL T7_;					NI TM__IobAM6Jeru9cnaKaai8r4Ug_3;
#line 40 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
					T7_ = (NIM_BOOL)0;
#line 40 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"

#line 40 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
					T7_ = (j < (s_0 ? s_0->Sup.len : 0));					if (!(T7_)) goto LA8_;

#line 40 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"

#line 40 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
					if ((NU)(j) >= (NU)(s_0 ? s_0->Sup.len : 0)){ raiseIndexError2(j,(s_0 ? s_0->Sup.len : 0)-1); }					T7_ = (((seps[(NU)(((NU8)(s_0->data[j])))>>3] &(1U<<((NU)(((NU8)(s_0->data[j])))&7U)))!=0) == isSep);					LA8_: ;
					if (!T7_) goto LA6;

#line 40 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
					if (nimAddInt(j, ((NI) 1), &TM__IobAM6Jeru9cnaKaai8r4Ug_3)) { raiseOverflow(); };					j = (NI)(TM__IobAM6Jeru9cnaKaai8r4Ug_3);				} LA6: ;
			}

#line 41 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
			{
#line 41 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
				if (!(j <= i)) goto LA11_;

#line 41 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
				goto LA1;
			}
			LA11_: ;

#line 43 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
			{				if (!isSep) goto LA15_;

#line 44 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
				lastSep = setLengthStr(lastSep, ((NI) 0));				{					NI k;					NI i_2;					k = (NI)0;
#line 106 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators_1.nim"
					i_2 = i;					{
#line 107 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators_1.nim"
						while (1) {							NI TM__IobAM6Jeru9cnaKaai8r4Ug_4;
#line 107 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators_1.nim"
							if (!(i_2 < j)) goto LA19;

#line 45 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
							k = i_2;
#line 46 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
							{
#line 46 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"

#line 46 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
								if ((NU)(k) >= (NU)(s_0 ? s_0->Sup.len : 0)){ raiseIndexError2(k,(s_0 ? s_0->Sup.len : 0)-1); }								if (!!((((NU8)(s_0->data[k])) == ((NU8)(10)) || ((NU8)(s_0->data[k])) == ((NU8)(13))))) goto LA22_;

#line 46 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
								if ((NU)(k) >= (NU)(s_0 ? s_0->Sup.len : 0)){ raiseIndexError2(k,(s_0 ? s_0->Sup.len : 0)-1); }								lastSep = addChar(lastSep, s_0->data[k]);							}
							LA22_: ;

#line 109 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators_1.nim"
							if (nimAddInt(i_2, ((NI) 1), &TM__IobAM6Jeru9cnaKaai8r4Ug_4)) { raiseOverflow(); };							i_2 = (NI)(TM__IobAM6Jeru9cnaKaai8r4Ug_4);						} LA19: ;
					}
				}

#line 47 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
				{					NI TM__IobAM6Jeru9cnaKaai8r4Ug_5;
#line 47 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"

#line 47 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
					if (!((lastSep ? lastSep->Sup.len : 0) == ((NI) 0))) goto LA26_;

#line 48 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
					lastSep = addChar(lastSep, 32);
#line 49 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
					if (nimSubInt(spaceLeft, ((NI) 1), &TM__IobAM6Jeru9cnaKaai8r4Ug_5)) { raiseOverflow(); };					spaceLeft = (NI)(TM__IobAM6Jeru9cnaKaai8r4Ug_5);				}
				goto LA24_;
				LA26_: ;
				{					NI T29_;					NI TM__IobAM6Jeru9cnaKaai8r4Ug_8;
#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"

#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"

#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"

#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"

#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
					T29_ = (NI)0;					T29_ = olen__0dw7gZET9cKXvkxNm43MHRA(lastSep, ((NI) 0), (lastSep ? lastSep->Sup.len : 0));					if (nimSubInt(spaceLeft, T29_, &TM__IobAM6Jeru9cnaKaai8r4Ug_8)) { raiseOverflow(); };					spaceLeft = (NI)(TM__IobAM6Jeru9cnaKaai8r4Ug_8);				}
				LA24_: ;
			}
			goto LA13_;
			LA15_: ;
			{				NI wlen;
#line 53 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"

#line 53 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
				wlen = olen__0dw7gZET9cKXvkxNm43MHRA(s_0, i, j);
#line 54 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
				{
#line 54 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
					if (!(spaceLeft < wlen)) goto LA33_;

#line 55 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
					{						NIM_BOOL T37_;						NI k_2;
#line 55 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
						T37_ = (NIM_BOOL)0;						T37_ = splitLongWords;						if (!(T37_)) goto LA38_;

#line 55 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
						T37_ = (maxLineWidth < wlen);						LA38_: ;
						if (!T37_) goto LA39_;

#line 56 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
						k_2 = ((NI) 0);						{
#line 57 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
							while (1) {								NI TM__IobAM6Jeru9cnaKaai8r4Ug_9;								NI TM__IobAM6Jeru9cnaKaai8r4Ug_10;								NI L;								NI TM__IobAM6Jeru9cnaKaai8r4Ug_11;								NI TM__IobAM6Jeru9cnaKaai8r4Ug_15;
#line 57 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"

#line 57 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
								if (nimSubInt(j, i, &TM__IobAM6Jeru9cnaKaai8r4Ug_9)) { raiseOverflow(); };								if (!(k_2 < (NI)(TM__IobAM6Jeru9cnaKaai8r4Ug_9))) goto LA42;

#line 58 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
								{
#line 58 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
									if (!(spaceLeft <= ((NI) 0))) goto LA45_;

#line 59 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
									spaceLeft = maxLineWidth;
#line 60 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
									result = resizeString(result, (newLine ? newLine->Sup.len : 0) + 0);appendString(result, newLine);								}
								LA45_: ;

#line 61 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
								if (nimSubInt(spaceLeft, ((NI) 1), &TM__IobAM6Jeru9cnaKaai8r4Ug_10)) { raiseOverflow(); };								spaceLeft = (NI)(TM__IobAM6Jeru9cnaKaai8r4Ug_10);
#line 62 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"

#line 62 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
								if (nimAddInt(k_2, i, &TM__IobAM6Jeru9cnaKaai8r4Ug_11)) { raiseOverflow(); };								if (((NI)(TM__IobAM6Jeru9cnaKaai8r4Ug_11)) < ((NI) 0) || ((NI)(TM__IobAM6Jeru9cnaKaai8r4Ug_11)) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__IobAM6Jeru9cnaKaai8r4Ug_11), ((NI) 0), ((NI) IL64(9223372036854775807))); }
#line 62 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
								L = graphemeLen__PLnPtAcI9ac8BvVcA3e5o7w(s_0, ((NI) ((NI)(TM__IobAM6Jeru9cnaKaai8r4Ug_11))));								{									NI m;									NI colontmp_;									NI i_3;									m = (NI)0;									colontmp_ = (NI)0;
#line 63 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
									colontmp_ = ((NI) (L));
#line 106 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators_1.nim"
									i_3 = ((NI) 0);									{
#line 107 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators_1.nim"
										while (1) {											NI TM__IobAM6Jeru9cnaKaai8r4Ug_12;											NI TM__IobAM6Jeru9cnaKaai8r4Ug_13;											NI TM__IobAM6Jeru9cnaKaai8r4Ug_14;
#line 107 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators_1.nim"
											if (!(i_3 < colontmp_)) goto LA49;

#line 63 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
											m = i_3;
#line 63 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"

#line 63 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"

#line 63 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
											if (nimAddInt(i, k_2, &TM__IobAM6Jeru9cnaKaai8r4Ug_12)) { raiseOverflow(); };											if (nimAddInt((NI)(TM__IobAM6Jeru9cnaKaai8r4Ug_12), m, &TM__IobAM6Jeru9cnaKaai8r4Ug_13)) { raiseOverflow(); };											if ((NU)((NI)(TM__IobAM6Jeru9cnaKaai8r4Ug_13)) >= (NU)(s_0 ? s_0->Sup.len : 0)){ raiseIndexError2((NI)(TM__IobAM6Jeru9cnaKaai8r4Ug_13),(s_0 ? s_0->Sup.len : 0)-1); }											result = addChar(result, s_0->data[(NI)(TM__IobAM6Jeru9cnaKaai8r4Ug_13)]);
#line 109 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators_1.nim"
											if (nimAddInt(i_3, ((NI) 1), &TM__IobAM6Jeru9cnaKaai8r4Ug_14)) { raiseOverflow(); };											i_3 = (NI)(TM__IobAM6Jeru9cnaKaai8r4Ug_14);										} LA49: ;
									}
								}

#line 64 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
								if (nimAddInt(k_2, ((NI) (L)), &TM__IobAM6Jeru9cnaKaai8r4Ug_15)) { raiseOverflow(); };								k_2 = (NI)(TM__IobAM6Jeru9cnaKaai8r4Ug_15);							} LA42: ;
						}
					}
					goto LA35_;
					LA39_: ;
					{						NI TM__IobAM6Jeru9cnaKaai8r4Ug_16;
#line 66 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"

#line 66 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
						if (nimSubInt(maxLineWidth, wlen, &TM__IobAM6Jeru9cnaKaai8r4Ug_16)) { raiseOverflow(); };						spaceLeft = (NI)(TM__IobAM6Jeru9cnaKaai8r4Ug_16);
#line 67 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
						result = resizeString(result, (newLine ? newLine->Sup.len : 0) + 0);appendString(result, newLine);						{							NI k_3;							NI i_4;							k_3 = (NI)0;
#line 106 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators_1.nim"
							i_4 = i;							{
#line 107 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators_1.nim"
								while (1) {									NI TM__IobAM6Jeru9cnaKaai8r4Ug_17;
#line 107 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators_1.nim"
									if (!(i_4 < j)) goto LA53;

#line 68 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
									k_3 = i_4;
#line 68 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
									if ((NU)(k_3) >= (NU)(s_0 ? s_0->Sup.len : 0)){ raiseIndexError2(k_3,(s_0 ? s_0->Sup.len : 0)-1); }									result = addChar(result, s_0->data[k_3]);
#line 109 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators_1.nim"
									if (nimAddInt(i_4, ((NI) 1), &TM__IobAM6Jeru9cnaKaai8r4Ug_17)) { raiseOverflow(); };									i_4 = (NI)(TM__IobAM6Jeru9cnaKaai8r4Ug_17);								} LA53: ;
							}
						}
					}
					LA35_: ;
				}
				goto LA31_;
				LA33_: ;
				{					NI TM__IobAM6Jeru9cnaKaai8r4Ug_18;
#line 70 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"

#line 70 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
					if (nimSubInt(spaceLeft, wlen, &TM__IobAM6Jeru9cnaKaai8r4Ug_18)) { raiseOverflow(); };					spaceLeft = (NI)(TM__IobAM6Jeru9cnaKaai8r4Ug_18);
#line 71 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
					result = resizeString(result, (lastSep ? lastSep->Sup.len : 0) + 0);appendString(result, lastSep);					{						NI k_4;						NI i_5;						k_4 = (NI)0;
#line 106 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators_1.nim"
						i_5 = i;						{
#line 107 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators_1.nim"
							while (1) {								NI TM__IobAM6Jeru9cnaKaai8r4Ug_19;
#line 107 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators_1.nim"
								if (!(i_5 < j)) goto LA57;

#line 72 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
								k_4 = i_5;
#line 72 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
								if ((NU)(k_4) >= (NU)(s_0 ? s_0->Sup.len : 0)){ raiseIndexError2(k_4,(s_0 ? s_0->Sup.len : 0)-1); }								result = addChar(result, s_0->data[k_4]);
#line 109 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators_1.nim"
								if (nimAddInt(i_5, ((NI) 1), &TM__IobAM6Jeru9cnaKaai8r4Ug_19)) { raiseOverflow(); };								i_5 = (NI)(TM__IobAM6Jeru9cnaKaai8r4Ug_19);							} LA57: ;
						}
					}
				}
				LA31_: ;
			}
			LA13_: ;

#line 74 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/std/wordwrap.nim"
			i = j;		}
	} LA1: ;
	return result;}
