/* Generated by Nim Compiler v1.2.6 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -pthread -I/home/runner/work/nim-waku/nim-waku/vendor/nim-libbacktrace -I/home/runner/work/nim-waku/nim-waku/vendor/nim-libbacktrace/install/usr/include -I/home/runner/work/nim-waku/nim-waku/vendor/nim-secp256k1/secp256k1_wrapper -I/home/runner/work/nim-waku/nim-waku/vendor/nim-secp256k1/secp256k1_wrapper/secp256k1 -I/home/runner/work/nim-waku/nim-waku/vendor/nim-secp256k1/secp256k1_wrapper/secp256k1/src -DHAVE_CONFIG_H -DHAVE_BUILTIN_EXPECT -I/home/runner/work/nim-waku/nim-waku/vendor/nim-bearssl/bearssl/csources/src -I/home/runner/work/nim-waku/nim-waku/vendor/nim-bearssl/bearssl/csources/inc -I/home/runner/work/nim-waku/nim-waku/vendor/nim-bearssl/bearssl/csources/tools -DBR_USE_UNIX_TIME=1 -DBR_USE_URANDOM=1 -DBR_LE_UNALIGNED=1 -DBR_64=1  -DBR_amd64=1 -DBR_INT128=1 -I/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/vendor/miniupnp/miniupnpc -I/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/vendor/libnatpmp-upstream -DENABLE_STRNATPMPERR -march=native -g3 -Og -O3 -fno-strict-aliasing -fno-ident  -I/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib -I/home/runner/work/nim-waku/nim-waku/waku/v1/node -o nimcache/release/wakunode1/@m..@s..@s..@svendor@snim-chronicles@schronicles.nim.c.o nimcache/release/wakunode1/@m..@s..@s..@svendor@snim-chronicles@schronicles.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef NU8 tyEnum_TopicState__ah9cbicZo9clzGWtgai40l6g;
typedef NU8 tyEnum_LogLevel__9bciZEQ8iC1G2PermjsuXmA;
struct tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ {tyEnum_TopicState__ah9cbicZo9clzGWtgai40l6g state;
tyEnum_LogLevel__9bciZEQ8iC1G2PermjsuXmA logLevel;
};
struct TGenericSeq {NI len;
NI reserved;
};
struct NimStringDesc {  TGenericSeq Sup;NIM_CHAR data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(NI, getThreadId__hrQB9bN29c1nR1E9cHqYcNcDA_2)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ*, registerTopic__QRTEPyLUyONbnmZmExdRdg)(NimStringDesc* name_0, tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ* topic);
STRING_LITERAL(TM__3nvRSfcPoTpjFt9ams46ATA_2, "rlpx", 4);
STRING_LITERAL(TM__3nvRSfcPoTpjFt9ams46ATA_3, "whisper", 7);
STRING_LITERAL(TM__3nvRSfcPoTpjFt9ams46ATA_4, "whisper_types", 13);
STRING_LITERAL(TM__3nvRSfcPoTpjFt9ams46ATA_5, "waku", 4);
STRING_LITERAL(TM__3nvRSfcPoTpjFt9ams46ATA_6, "nat", 3);
STRING_LITERAL(TM__3nvRSfcPoTpjFt9ams46ATA_7, "discovery", 9);
STRING_LITERAL(TM__3nvRSfcPoTpjFt9ams46ATA_8, "kademlia", 8);
STRING_LITERAL(TM__3nvRSfcPoTpjFt9ams46ATA_9, "JSONRPC-HTTP-SERVER", 19);
N_LIB_PRIVATE tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ topic__o7qRjehDzHk49aKpNCVhDgw = {((tyEnum_TopicState__ah9cbicZo9clzGWtgai40l6g) 0), ((tyEnum_LogLevel__9bciZEQ8iC1G2PermjsuXmA) 0)}
;
N_LIB_PRIVATE tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ* dummy__dy7JA2cVyMqri1Htk7uBOQ;
N_LIB_PRIVATE tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ topic__o7qRjehDzHk49aKpNCVhDgw_2 = {((tyEnum_TopicState__ah9cbicZo9clzGWtgai40l6g) 0), ((tyEnum_LogLevel__9bciZEQ8iC1G2PermjsuXmA) 0)}
;
N_LIB_PRIVATE tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ* dummy__dy7JA2cVyMqri1Htk7uBOQ_2;
N_LIB_PRIVATE tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ topic__o7qRjehDzHk49aKpNCVhDgw_3 = {((tyEnum_TopicState__ah9cbicZo9clzGWtgai40l6g) 0), ((tyEnum_LogLevel__9bciZEQ8iC1G2PermjsuXmA) 0)}
;
N_LIB_PRIVATE tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ* dummy__dy7JA2cVyMqri1Htk7uBOQ_3;
N_LIB_PRIVATE tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ topic__o7qRjehDzHk49aKpNCVhDgw_4 = {((tyEnum_TopicState__ah9cbicZo9clzGWtgai40l6g) 0), ((tyEnum_LogLevel__9bciZEQ8iC1G2PermjsuXmA) 0)}
;
N_LIB_PRIVATE tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ* dummy__dy7JA2cVyMqri1Htk7uBOQ_4;
N_LIB_PRIVATE tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ topic__o7qRjehDzHk49aKpNCVhDgw_5 = {((tyEnum_TopicState__ah9cbicZo9clzGWtgai40l6g) 0), ((tyEnum_LogLevel__9bciZEQ8iC1G2PermjsuXmA) 0)}
;
N_LIB_PRIVATE tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ* dummy__dy7JA2cVyMqri1Htk7uBOQ_5;
N_LIB_PRIVATE tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ topic__o7qRjehDzHk49aKpNCVhDgw_6 = {((tyEnum_TopicState__ah9cbicZo9clzGWtgai40l6g) 0), ((tyEnum_LogLevel__9bciZEQ8iC1G2PermjsuXmA) 0)}
;
N_LIB_PRIVATE tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ* dummy__dy7JA2cVyMqri1Htk7uBOQ_6;
N_LIB_PRIVATE tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ topic__o7qRjehDzHk49aKpNCVhDgw_7 = {((tyEnum_TopicState__ah9cbicZo9clzGWtgai40l6g) 0), ((tyEnum_LogLevel__9bciZEQ8iC1G2PermjsuXmA) 0)}
;
N_LIB_PRIVATE tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ* dummy__dy7JA2cVyMqri1Htk7uBOQ_7;
N_LIB_PRIVATE tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ topic__o7qRjehDzHk49aKpNCVhDgw_8 = {((tyEnum_TopicState__ah9cbicZo9clzGWtgai40l6g) 0), ((tyEnum_LogLevel__9bciZEQ8iC1G2PermjsuXmA) 0)}
;
N_LIB_PRIVATE tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ* dummy__dy7JA2cVyMqri1Htk7uBOQ_8;

#line 147 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"
N_LIB_PRIVATE N_NIMCALL(NI, getLogThreadId__MquaZIXVsrxU5lCSpmC3Jw)(void) {	NI result;	result = (NI)0;
#line 147 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"

#line 147 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"
	result = getThreadId__hrQB9bN29c1nR1E9cHqYcNcDA_2();	return result;}

#line 108 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ*, topicStateIMPL__4Bg2gEv67raTzGCyJ5wDtw)(void) {	tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ* result;{	result = (tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ*)0;
#line 113 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"

#line 113 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"
	result = (&topic__o7qRjehDzHk49aKpNCVhDgw);	goto BeforeRet_;
	}BeforeRet_: ;
	return result;}

#line 108 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ*, topicStateIMPL__QuSnSlb6U8Axdh79aL32tFQ)(void) {	tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ* result;{	result = (tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ*)0;
#line 113 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"

#line 113 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"
	result = (&topic__o7qRjehDzHk49aKpNCVhDgw_2);	goto BeforeRet_;
	}BeforeRet_: ;
	return result;}

#line 108 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ*, topicStateIMPL__dea529bYjLp7pmpQ17ZEnvQ)(void) {	tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ* result;{	result = (tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ*)0;
#line 113 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"

#line 113 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"
	result = (&topic__o7qRjehDzHk49aKpNCVhDgw_3);	goto BeforeRet_;
	}BeforeRet_: ;
	return result;}

#line 108 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ*, topicStateIMPL__uqGJpssRlyuLIEGWxBeenw)(void) {	tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ* result;{	result = (tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ*)0;
#line 113 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"

#line 113 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"
	result = (&topic__o7qRjehDzHk49aKpNCVhDgw_4);	goto BeforeRet_;
	}BeforeRet_: ;
	return result;}

#line 108 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ*, topicStateIMPL__02pa9cy3jDqbW3ZxTkbNIGw)(void) {	tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ* result;{	result = (tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ*)0;
#line 113 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"

#line 113 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"
	result = (&topic__o7qRjehDzHk49aKpNCVhDgw_5);	goto BeforeRet_;
	}BeforeRet_: ;
	return result;}

#line 108 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ*, topicStateIMPL__gL8o5x9chIiHApte4K3eO8A)(void) {	tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ* result;{	result = (tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ*)0;
#line 113 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"

#line 113 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"
	result = (&topic__o7qRjehDzHk49aKpNCVhDgw_6);	goto BeforeRet_;
	}BeforeRet_: ;
	return result;}

#line 108 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ*, topicStateIMPL__Ohn70LKfwfB14GonPhISpg)(void) {	tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ* result;{	result = (tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ*)0;
#line 113 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"

#line 113 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"
	result = (&topic__o7qRjehDzHk49aKpNCVhDgw_7);	goto BeforeRet_;
	}BeforeRet_: ;
	return result;}

#line 108 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ*, topicStateIMPL__A9aGbMmlp9a9c9cPTkhgiOW10g)(void) {	tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ* result;{	result = (tyObject_TopicSettings__oHdFGV9aUkZXwZgwzeiU4oQ*)0;
#line 113 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"

#line 113 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"
	result = (&topic__o7qRjehDzHk49aKpNCVhDgw_8);	goto BeforeRet_;
	}BeforeRet_: ;
	return result;}
N_LIB_PRIVATE N_NIMCALL(void, chronicles_chroniclesInit000)(void) {

#line 999999 "generated_not_to_break_here"
{
	TFrame FR_; FR_.len = 0;

#line 112 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"

#line 112 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"
	dummy__dy7JA2cVyMqri1Htk7uBOQ = registerTopic__QRTEPyLUyONbnmZmExdRdg(((NimStringDesc*) &TM__3nvRSfcPoTpjFt9ams46ATA_2), (&topic__o7qRjehDzHk49aKpNCVhDgw));
#line 112 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"

#line 112 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"
	dummy__dy7JA2cVyMqri1Htk7uBOQ_2 = registerTopic__QRTEPyLUyONbnmZmExdRdg(((NimStringDesc*) &TM__3nvRSfcPoTpjFt9ams46ATA_3), (&topic__o7qRjehDzHk49aKpNCVhDgw_2));
#line 112 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"

#line 112 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"
	dummy__dy7JA2cVyMqri1Htk7uBOQ_3 = registerTopic__QRTEPyLUyONbnmZmExdRdg(((NimStringDesc*) &TM__3nvRSfcPoTpjFt9ams46ATA_4), (&topic__o7qRjehDzHk49aKpNCVhDgw_3));
#line 112 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"

#line 112 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"
	dummy__dy7JA2cVyMqri1Htk7uBOQ_4 = registerTopic__QRTEPyLUyONbnmZmExdRdg(((NimStringDesc*) &TM__3nvRSfcPoTpjFt9ams46ATA_5), (&topic__o7qRjehDzHk49aKpNCVhDgw_4));
#line 112 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"

#line 112 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"
	dummy__dy7JA2cVyMqri1Htk7uBOQ_5 = registerTopic__QRTEPyLUyONbnmZmExdRdg(((NimStringDesc*) &TM__3nvRSfcPoTpjFt9ams46ATA_6), (&topic__o7qRjehDzHk49aKpNCVhDgw_5));
#line 112 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"

#line 112 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"
	dummy__dy7JA2cVyMqri1Htk7uBOQ_6 = registerTopic__QRTEPyLUyONbnmZmExdRdg(((NimStringDesc*) &TM__3nvRSfcPoTpjFt9ams46ATA_7), (&topic__o7qRjehDzHk49aKpNCVhDgw_6));
#line 112 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"

#line 112 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"
	dummy__dy7JA2cVyMqri1Htk7uBOQ_7 = registerTopic__QRTEPyLUyONbnmZmExdRdg(((NimStringDesc*) &TM__3nvRSfcPoTpjFt9ams46ATA_8), (&topic__o7qRjehDzHk49aKpNCVhDgw_7));
#line 112 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"

#line 112 "/home/runner/work/nim-waku/nim-waku/vendor/nim-chronicles/chronicles.nim"
	dummy__dy7JA2cVyMqri1Htk7uBOQ_8 = registerTopic__QRTEPyLUyONbnmZmExdRdg(((NimStringDesc*) &TM__3nvRSfcPoTpjFt9ams46ATA_9), (&topic__o7qRjehDzHk49aKpNCVhDgw_8));}
{
}
}

