/* Generated by Nim Compiler v1.2.6 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -pthread -I/home/runner/work/nim-waku/nim-waku/vendor/nim-libbacktrace -I/home/runner/work/nim-waku/nim-waku/vendor/nim-libbacktrace/install/usr/include -I/home/runner/work/nim-waku/nim-waku/vendor/nim-secp256k1/secp256k1_wrapper -I/home/runner/work/nim-waku/nim-waku/vendor/nim-secp256k1/secp256k1_wrapper/secp256k1 -I/home/runner/work/nim-waku/nim-waku/vendor/nim-secp256k1/secp256k1_wrapper/secp256k1/src -DHAVE_CONFIG_H -DHAVE_BUILTIN_EXPECT -I/home/runner/work/nim-waku/nim-waku/vendor/nim-bearssl/bearssl/csources/src -I/home/runner/work/nim-waku/nim-waku/vendor/nim-bearssl/bearssl/csources/inc -I/home/runner/work/nim-waku/nim-waku/vendor/nim-bearssl/bearssl/csources/tools -DBR_USE_UNIX_TIME=1 -DBR_USE_URANDOM=1 -DBR_LE_UNALIGNED=1 -DBR_64=1  -DBR_amd64=1 -DBR_INT128=1 -I/home/runner/work/nim-waku/nim-waku/vendor/nim-bearssl/bearssl/certs -I/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/vendor/miniupnp/miniupnpc -I/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/vendor/libnatpmp-upstream -DENABLE_STRNATPMPERR -march=native -g3 -Og -O3 -fno-strict-aliasing -fno-ident  -I/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib -I/home/runner/work/nim-waku/nim-waku/examples/v2 -o nimcache/release/chat2/@m..@s..@svendor@snim-eth@seth@srlp@sobject_serialization.nim.c.o nimcache/release/chat2/@m..@s..@svendor@snim-eth@seth@srlp@sobject_serialization.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)

#line 21 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/rlp/object_serialization.nim"
N_LIB_PRIVATE N_NIMCALL(NI, rlpFieldsCount__W2y2aKBmAUL2WEeZZsRm9bA)(void) {	NI result;{	result = (NI)0;
#line 30 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/rlp/object_serialization.nim"

#line 30 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/rlp/object_serialization.nim"
	result = ((NI) 5);	goto BeforeRet_;
	}BeforeRet_: ;
	return result;}

#line 21 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/rlp/object_serialization.nim"
N_LIB_PRIVATE N_NIMCALL(NI, rlpFieldsCount__UKfTqk5QYAA4A6x3WOukfA)(void) {	NI result;{	result = (NI)0;
#line 30 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/rlp/object_serialization.nim"

#line 30 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/rlp/object_serialization.nim"
	result = ((NI) 1);	goto BeforeRet_;
	}BeforeRet_: ;
	return result;}

#line 21 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/rlp/object_serialization.nim"
N_LIB_PRIVATE N_NIMCALL(NI, rlpFieldsCount__oZX1KTanvSPkOt9aplULnoA)(void) {	NI result;{	result = (NI)0;
#line 30 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/rlp/object_serialization.nim"

#line 30 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/rlp/object_serialization.nim"
	result = ((NI) 1);	goto BeforeRet_;
	}BeforeRet_: ;
	return result;}

#line 21 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/rlp/object_serialization.nim"
N_LIB_PRIVATE N_NIMCALL(NI, rlpFieldsCount__V5xC9cmJl4e5O2oGS2MTQiw)(void) {	NI result;{	result = (NI)0;
#line 30 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/rlp/object_serialization.nim"

#line 30 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/rlp/object_serialization.nim"
	result = ((NI) 1);	goto BeforeRet_;
	}BeforeRet_: ;
	return result;}
