/* Generated by Nim Compiler v1.2.6 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -pthread -I/home/runner/work/nim-waku/nim-waku/vendor/nim-libbacktrace -I/home/runner/work/nim-waku/nim-waku/vendor/nim-libbacktrace/install/usr/include -I/home/runner/work/nim-waku/nim-waku/vendor/nim-secp256k1/secp256k1_wrapper -I/home/runner/work/nim-waku/nim-waku/vendor/nim-secp256k1/secp256k1_wrapper/secp256k1 -I/home/runner/work/nim-waku/nim-waku/vendor/nim-secp256k1/secp256k1_wrapper/secp256k1/src -DHAVE_CONFIG_H -DHAVE_BUILTIN_EXPECT -I/home/runner/work/nim-waku/nim-waku/vendor/nim-bearssl/bearssl/csources/src -I/home/runner/work/nim-waku/nim-waku/vendor/nim-bearssl/bearssl/csources/inc -I/home/runner/work/nim-waku/nim-waku/vendor/nim-bearssl/bearssl/csources/tools -DBR_USE_UNIX_TIME=1 -DBR_USE_URANDOM=1 -DBR_LE_UNALIGNED=1 -DBR_64=1  -DBR_amd64=1 -DBR_INT128=1 -I/home/runner/work/nim-waku/nim-waku/vendor/nim-bearssl/bearssl/certs -I/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/vendor/miniupnp/miniupnpc -I/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/vendor/libnatpmp-upstream -DENABLE_STRNATPMPERR -march=native -g3 -Og -O3 -fno-strict-aliasing -fno-ident  -I/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib -I/home/runner/work/nim-waku/nim-waku/examples/v2 -o nimcache/release/chat2/@m..@s..@svendor@snimcrypto@snimcrypto@spbkdf2.nim.c.o nimcache/release/chat2/@m..@s..@svendor@snimcrypto@snimcrypto@spbkdf2.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_HMAC__CxVfcs3qQxev4nVq3Txjyg tyObject_HMAC__CxVfcs3qQxev4nVq3Txjyg;
typedef struct tyObject_Sha2Context__5brAquljQjPUyNuIC4vV1w tyObject_Sha2Context__5brAquljQjPUyNuIC4vV1w;
typedef NU8 tyArray__H8qf9bpC2ziYA2earmO8m7w[4];
typedef NU8 tyArray__vEOa9c5qaE9ajWxR5R4zwfQg[32];
typedef NU32 tyArray__JlnxiR65D9cjJpwi6uBZRtA[2];
typedef NU32 tyArray__MpWsq9bBH14GsDQQ59cgyxAQ[8];
typedef NU8 tyArray__w5VB8h5K8DB3oWrO5U2wqg[64];
struct tyObject_Sha2Context__5brAquljQjPUyNuIC4vV1w {tyArray__JlnxiR65D9cjJpwi6uBZRtA count;
tyArray__MpWsq9bBH14GsDQQ59cgyxAQ state;
tyArray__w5VB8h5K8DB3oWrO5U2wqg buffer;
};
struct tyObject_HMAC__CxVfcs3qQxev4nVq3Txjyg {tyObject_Sha2Context__5brAquljQjPUyNuIC4vV1w mdctx;
tyObject_Sha2Context__5brAquljQjPUyNuIC4vV1w opadctx;
tyArray__w5VB8h5K8DB3oWrO5U2wqg ipad;
tyArray__w5VB8h5K8DB3oWrO5U2wqg opad;
};
typedef NU8 tyArray__cleXh9bMEnUU9aNvjKX8m6BA[32];
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(void, init__XO79cz0G5x9bYWx3NREUG23g)(tyObject_HMAC__CxVfcs3qQxev4nVq3Txjyg* hmctx, NU8* key_0, NI key_0Len_0);
static N_INLINE(void, update__JlxQJoHy4ZmcjsPUc3vq1ghmac)(tyObject_HMAC__CxVfcs3qQxev4nVq3Txjyg* hmctx, NIM_CHAR* data_0, NI data_0Len_0);
static N_INLINE(void, update__ac5kVNZW9auoLXYeatlPm9cgsha2)(tyObject_Sha2Context__5brAquljQjPUyNuIC4vV1w* ctx, NIM_CHAR* data_0, NI data_0Len_0);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, copyMem__i80o3k0SgEI5gTRCzYdyWAsystem)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(void, sha256Transform__BJNBQtWr9bJwzqbyfKXd38Q)(NU32* state_0, NU8* data_0, NI data_0Len_0);
static N_INLINE(void, update__JDQKL6F3d4BVGKvrNMc9bmghmac)(tyObject_HMAC__CxVfcs3qQxev4nVq3Txjyg* hmctx, NU8* data_0, NI data_0Len_0);
static N_INLINE(void, update__JVKV5lsc6z00iHHbNwyg9bAsha2)(tyObject_Sha2Context__5brAquljQjPUyNuIC4vV1w* ctx, NU8* data_0, NI data_0Len_0);
static N_INLINE(NU, finish__21C9bb9bs8ZSGFBr7oxmCmkghmac)(tyObject_HMAC__CxVfcs3qQxev4nVq3Txjyg* hmctx, NU8* data_0, NI data_0Len_0);
static N_INLINE(NU, finish__XWD9ckGqZzLMH9bax9c7RDdGgsha2)(tyObject_Sha2Context__5brAquljQjPUyNuIC4vV1w* ctx, NU8* data_0, NI data_0Len_0);
static N_INLINE(void, finalize256__C8fXqRtxb2ILgkwYRN3qiQ_2sha2)(tyObject_Sha2Context__5brAquljQjPUyNuIC4vV1w* ctx);
N_LIB_PRIVATE N_NIMCALL(void, clear__3PkHS3KRpSG9bEaZCBbhR4w_2)(tyObject_HMAC__CxVfcs3qQxev4nVq3Txjyg* hmctx);

#line 22 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size) {	void* T1_;
#line 24 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"

#line 24 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memset(a, v, ((size_t) (size)));}

#line 33 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
#line 34 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"

#line 34 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"
	nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory(p, ((int) 0), size);
}

#line 11 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {	void* T1_;
#line 13 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"

#line 13 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memcpy(dest, source, ((size_t) (size)));}

#line 2112 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system.nim"
static N_INLINE(void, copyMem__i80o3k0SgEI5gTRCzYdyWAsystem)(void* dest, void* source, NI size) {
#line 2113 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system.nim"

#line 2113 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system.nim"
	nimCopyMem(dest, source, size);
}

#line 459 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
static N_INLINE(void, update__ac5kVNZW9auoLXYeatlPm9cgsha2)(tyObject_Sha2Context__5brAquljQjPUyNuIC4vV1w* ctx, NIM_CHAR* data_0, NI data_0Len_0) {	NI pos;	NI length;
#line 460 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
	pos = ((NI) 0);
#line 461 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"

#line 461 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
	length = data_0Len_0;	{
#line 464 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
		while (1) {			NI offset;			NI size;			NI TM__0a29c9b3bMduzcVNZQPcw9bGg_2;			NI TM__0a29c9b3bMduzcVNZQPcw9bGg_3;			NI TM__0a29c9b3bMduzcVNZQPcw9bGg_4;			NI TM__0a29c9b3bMduzcVNZQPcw9bGg_5;
#line 464 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
			if (!(((NI) 0) < length)) goto LA2;

#line 465 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"

#line 465 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
			offset = ((NI) ((NU32)((*ctx).count[(((NI) 0))- 0] & ((NU32) 63))));
#line 466 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"

#line 466 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"

#line 466 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
			if (nimSubInt(((NI) 64), offset, &TM__0a29c9b3bMduzcVNZQPcw9bGg_2)) { raiseOverflow(); };			size = (((NI)(TM__0a29c9b3bMduzcVNZQPcw9bGg_2) <= length) ? (NI)(TM__0a29c9b3bMduzcVNZQPcw9bGg_2) : length);
#line 417 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/utils.nim"
			if ((NU)(offset) > (NU)(63)){ raiseIndexError2(offset, 63); }			if ((NU)(pos) >= (NU)(data_0Len_0)){ raiseIndexError2(pos,data_0Len_0-1); }
#line 417 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/utils.nim"
			if (nimMulInt(size, ((NI) 1), &TM__0a29c9b3bMduzcVNZQPcw9bGg_3)) { raiseOverflow(); };			if (((NI)(TM__0a29c9b3bMduzcVNZQPcw9bGg_3)) < ((NI) 0) || ((NI)(TM__0a29c9b3bMduzcVNZQPcw9bGg_3)) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__0a29c9b3bMduzcVNZQPcw9bGg_3), ((NI) 0), ((NI) IL64(9223372036854775807))); }
#line 417 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/utils.nim"
			copyMem__i80o3k0SgEI5gTRCzYdyWAsystem(((void*) ((&(*ctx).buffer[(offset)- 0]))), ((void*) ((&data_0[pos]))), ((NI) ((NI)(TM__0a29c9b3bMduzcVNZQPcw9bGg_3))));

#line 468 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"

#line 468 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
			if (nimAddInt(pos, size, &TM__0a29c9b3bMduzcVNZQPcw9bGg_4)) { raiseOverflow(); };			pos = (NI)(TM__0a29c9b3bMduzcVNZQPcw9bGg_4);
#line 469 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"

#line 469 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
			if (nimSubInt(length, size, &TM__0a29c9b3bMduzcVNZQPcw9bGg_5)) { raiseOverflow(); };			length = (NI)(TM__0a29c9b3bMduzcVNZQPcw9bGg_5);
#line 470 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"

#line 470 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
			(*ctx).count[(((NI) 0))- 0] = (NU32)((NU32)((*ctx).count[(((NI) 0))- 0]) + (NU32)(((NU32) (size))));
#line 471 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
			{
#line 471 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
				if (!((NU32)((*ctx).count[(((NI) 0))- 0]) < (NU32)(((NU32) (size))))) goto LA5_;

#line 472 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"

#line 472 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
				(*ctx).count[(((NI) 1))- 0] = (NU32)((NU32)((*ctx).count[(((NI) 1))- 0]) + (NU32)(((NU32) 1)));			}
			LA5_: ;

#line 473 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
			{
#line 473 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"

#line 473 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
				if (!((NU32)((*ctx).count[(((NI) 0))- 0] & ((NU32) 63)) == ((NU32) 0))) goto LA9_;

#line 474 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"

#line 474 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
				sha256Transform__BJNBQtWr9bJwzqbyfKXd38Q((*ctx).state, (*ctx).buffer, 64);
			}
			LA9_: ;
		} LA2: ;
	}
}

#line 158 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/hmac.nim"
static N_INLINE(void, update__JlxQJoHy4ZmcjsPUc3vq1ghmac)(tyObject_HMAC__CxVfcs3qQxev4nVq3Txjyg* hmctx, NIM_CHAR* data_0, NI data_0Len_0) {
#line 175 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/hmac.nim"

#line 175 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/hmac.nim"
	update__ac5kVNZW9auoLXYeatlPm9cgsha2((&(*hmctx).mdctx), data_0, data_0Len_0);
}

#line 459 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
static N_INLINE(void, update__JVKV5lsc6z00iHHbNwyg9bAsha2)(tyObject_Sha2Context__5brAquljQjPUyNuIC4vV1w* ctx, NU8* data_0, NI data_0Len_0) {	NI pos;	NI length;
#line 460 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
	pos = ((NI) 0);
#line 461 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"

#line 461 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
	length = data_0Len_0;	{
#line 464 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
		while (1) {			NI offset;			NI size;			NI TM__0a29c9b3bMduzcVNZQPcw9bGg_6;			NI TM__0a29c9b3bMduzcVNZQPcw9bGg_7;			NI TM__0a29c9b3bMduzcVNZQPcw9bGg_8;			NI TM__0a29c9b3bMduzcVNZQPcw9bGg_9;
#line 464 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
			if (!(((NI) 0) < length)) goto LA2;

#line 465 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"

#line 465 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
			offset = ((NI) ((NU32)((*ctx).count[(((NI) 0))- 0] & ((NU32) 63))));
#line 466 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"

#line 466 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"

#line 466 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
			if (nimSubInt(((NI) 64), offset, &TM__0a29c9b3bMduzcVNZQPcw9bGg_6)) { raiseOverflow(); };			size = (((NI)(TM__0a29c9b3bMduzcVNZQPcw9bGg_6) <= length) ? (NI)(TM__0a29c9b3bMduzcVNZQPcw9bGg_6) : length);
#line 417 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/utils.nim"
			if ((NU)(offset) > (NU)(63)){ raiseIndexError2(offset, 63); }			if ((NU)(pos) >= (NU)(data_0Len_0)){ raiseIndexError2(pos,data_0Len_0-1); }
#line 417 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/utils.nim"
			if (nimMulInt(size, ((NI) 1), &TM__0a29c9b3bMduzcVNZQPcw9bGg_7)) { raiseOverflow(); };			if (((NI)(TM__0a29c9b3bMduzcVNZQPcw9bGg_7)) < ((NI) 0) || ((NI)(TM__0a29c9b3bMduzcVNZQPcw9bGg_7)) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__0a29c9b3bMduzcVNZQPcw9bGg_7), ((NI) 0), ((NI) IL64(9223372036854775807))); }
#line 417 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/utils.nim"
			copyMem__i80o3k0SgEI5gTRCzYdyWAsystem(((void*) ((&(*ctx).buffer[(offset)- 0]))), ((void*) ((&data_0[pos]))), ((NI) ((NI)(TM__0a29c9b3bMduzcVNZQPcw9bGg_7))));

#line 468 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"

#line 468 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
			if (nimAddInt(pos, size, &TM__0a29c9b3bMduzcVNZQPcw9bGg_8)) { raiseOverflow(); };			pos = (NI)(TM__0a29c9b3bMduzcVNZQPcw9bGg_8);
#line 469 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"

#line 469 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
			if (nimSubInt(length, size, &TM__0a29c9b3bMduzcVNZQPcw9bGg_9)) { raiseOverflow(); };			length = (NI)(TM__0a29c9b3bMduzcVNZQPcw9bGg_9);
#line 470 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"

#line 470 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
			(*ctx).count[(((NI) 0))- 0] = (NU32)((NU32)((*ctx).count[(((NI) 0))- 0]) + (NU32)(((NU32) (size))));
#line 471 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
			{
#line 471 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
				if (!((NU32)((*ctx).count[(((NI) 0))- 0]) < (NU32)(((NU32) (size))))) goto LA5_;

#line 472 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"

#line 472 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
				(*ctx).count[(((NI) 1))- 0] = (NU32)((NU32)((*ctx).count[(((NI) 1))- 0]) + (NU32)(((NU32) 1)));			}
			LA5_: ;

#line 473 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
			{
#line 473 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"

#line 473 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
				if (!((NU32)((*ctx).count[(((NI) 0))- 0] & ((NU32) 63)) == ((NU32) 0))) goto LA9_;

#line 474 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"

#line 474 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
				sha256Transform__BJNBQtWr9bJwzqbyfKXd38Q((*ctx).state, (*ctx).buffer, 64);
			}
			LA9_: ;
		} LA2: ;
	}
}

#line 158 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/hmac.nim"
static N_INLINE(void, update__JDQKL6F3d4BVGKvrNMc9bmghmac)(tyObject_HMAC__CxVfcs3qQxev4nVq3Txjyg* hmctx, NU8* data_0, NI data_0Len_0) {
#line 175 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/hmac.nim"

#line 175 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/hmac.nim"
	update__JVKV5lsc6z00iHHbNwyg9bAsha2((&(*hmctx).mdctx), data_0, data_0Len_0);
}

#line 492 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
static N_INLINE(void, finalize256__C8fXqRtxb2ILgkwYRN3qiQ_2sha2)(tyObject_Sha2Context__5brAquljQjPUyNuIC4vV1w* ctx) {	NI j;	NI TM__0a29c9b3bMduzcVNZQPcw9bGg_10;
#line 493 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"

#line 493 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
	j = ((NI) ((NU32)((*ctx).count[(((NI) 0))- 0] & ((NU32) 63))));	if ((NU)(j) > (NU)(63)){ raiseIndexError2(j, 63); }
#line 494 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
	(*ctx).buffer[(j)- 0] = ((NU8) 128);
#line 495 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
	if (nimAddInt(j, ((NI) 1), &TM__0a29c9b3bMduzcVNZQPcw9bGg_10)) { raiseOverflow(); };	j = (NI)(TM__0a29c9b3bMduzcVNZQPcw9bGg_10);	{
#line 496 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
		while (1) {			NI TM__0a29c9b3bMduzcVNZQPcw9bGg_11;
#line 496 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"

#line 496 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
			if (!!((j == ((NI) 56)))) goto LA2;

#line 497 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
			{
#line 497 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
				if (!(j == ((NI) 64))) goto LA5_;

#line 498 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"

#line 498 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
				sha256Transform__BJNBQtWr9bJwzqbyfKXd38Q((*ctx).state, (*ctx).buffer, 64);

#line 499 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
				j = ((NI) 0);			}
			LA5_: ;
			if ((NU)(j) > (NU)(63)){ raiseIndexError2(j, 63); }
#line 500 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
			(*ctx).buffer[(j)- 0] = ((NU8) 0);
#line 501 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
			if (nimAddInt(j, ((NI) 1), &TM__0a29c9b3bMduzcVNZQPcw9bGg_11)) { raiseOverflow(); };			j = (NI)(TM__0a29c9b3bMduzcVNZQPcw9bGg_11);		} LA2: ;
	}

#line 502 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"

#line 502 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"

#line 502 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"

#line 502 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
	(*ctx).count[(((NI) 1))- 0] = (NU32)((NU32)((NU32)((NU64)((*ctx).count[(((NI) 1))- 0]) << (NU64)(((NI) 3)))) + (NU32)((NU32)((NU32)((*ctx).count[(((NI) 0))- 0]) >> (NU64)(((NI) 29)))));
#line 503 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"

#line 503 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
	(*ctx).count[(((NI) 0))- 0] = (NU32)((NU64)((*ctx).count[(((NI) 0))- 0]) << (NU64)(((NI) 3)));
#line 373 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/utils.nim"

#line 373 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/utils.nim"
	(*((NU32*) ((&(*ctx).buffer[(((NI) 56))- 0])))) = __builtin_bswap32((*ctx).count[(((NI) 1))- 0]);
#line 373 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/utils.nim"

#line 373 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/utils.nim"
	(*((NU32*) ((&(*ctx).buffer[(((NI) 60))- 0])))) = __builtin_bswap32((*ctx).count[(((NI) 0))- 0]);
#line 506 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"

#line 506 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
	sha256Transform__BJNBQtWr9bJwzqbyfKXd38Q((*ctx).state, (*ctx).buffer, 64);
}

#line 524 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
static N_INLINE(NU, finish__XWD9ckGqZzLMH9bax9c7RDdGgsha2)(tyObject_Sha2Context__5brAquljQjPUyNuIC4vV1w* ctx, NU8* data_0, NI data_0Len_0) {	NU result;	result = (NU)0;
#line 526 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
	result = ((NU) 0);
#line 539 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
	{
#line 539 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"

#line 539 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
		if (!(((NI) 32) <= data_0Len_0)) goto LA3_;

#line 540 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"

#line 540 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
		finalize256__C8fXqRtxb2ILgkwYRN3qiQ_2sha2(ctx);

#line 541 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/sha2.nim"
		result = ((NU) 32);		if ((NU)(((NI) 0)) >= (NU)(data_0Len_0)){ raiseIndexError2(((NI) 0),data_0Len_0-1); }
#line 373 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/utils.nim"

#line 373 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/utils.nim"
		(*((NU32*) ((&data_0[((NI) 0)])))) = __builtin_bswap32((*ctx).state[(((NI) 0))- 0]);		if ((NU)(((NI) 4)) >= (NU)(data_0Len_0)){ raiseIndexError2(((NI) 4),data_0Len_0-1); }
#line 373 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/utils.nim"

#line 373 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/utils.nim"
		(*((NU32*) ((&data_0[((NI) 4)])))) = __builtin_bswap32((*ctx).state[(((NI) 1))- 0]);		if ((NU)(((NI) 8)) >= (NU)(data_0Len_0)){ raiseIndexError2(((NI) 8),data_0Len_0-1); }
#line 373 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/utils.nim"

#line 373 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/utils.nim"
		(*((NU32*) ((&data_0[((NI) 8)])))) = __builtin_bswap32((*ctx).state[(((NI) 2))- 0]);		if ((NU)(((NI) 12)) >= (NU)(data_0Len_0)){ raiseIndexError2(((NI) 12),data_0Len_0-1); }
#line 373 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/utils.nim"

#line 373 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/utils.nim"
		(*((NU32*) ((&data_0[((NI) 12)])))) = __builtin_bswap32((*ctx).state[(((NI) 3))- 0]);		if ((NU)(((NI) 16)) >= (NU)(data_0Len_0)){ raiseIndexError2(((NI) 16),data_0Len_0-1); }
#line 373 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/utils.nim"

#line 373 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/utils.nim"
		(*((NU32*) ((&data_0[((NI) 16)])))) = __builtin_bswap32((*ctx).state[(((NI) 4))- 0]);		if ((NU)(((NI) 20)) >= (NU)(data_0Len_0)){ raiseIndexError2(((NI) 20),data_0Len_0-1); }
#line 373 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/utils.nim"

#line 373 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/utils.nim"
		(*((NU32*) ((&data_0[((NI) 20)])))) = __builtin_bswap32((*ctx).state[(((NI) 5))- 0]);		if ((NU)(((NI) 24)) >= (NU)(data_0Len_0)){ raiseIndexError2(((NI) 24),data_0Len_0-1); }
#line 373 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/utils.nim"

#line 373 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/utils.nim"
		(*((NU32*) ((&data_0[((NI) 24)])))) = __builtin_bswap32((*ctx).state[(((NI) 6))- 0]);		if ((NU)(((NI) 28)) >= (NU)(data_0Len_0)){ raiseIndexError2(((NI) 28),data_0Len_0-1); }
#line 373 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/utils.nim"

#line 373 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/utils.nim"
		(*((NU32*) ((&data_0[((NI) 28)])))) = __builtin_bswap32((*ctx).state[(((NI) 7))- 0]);	}
	LA3_: ;
	return result;}

#line 197 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/hmac.nim"
static N_INLINE(NU, finish__21C9bb9bs8ZSGFBr7oxmCmkghmac)(tyObject_HMAC__CxVfcs3qQxev4nVq3Txjyg* hmctx, NU8* data_0, NI data_0Len_0) {	NU result;	result = (NU)0;
#line 203 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/hmac.nim"
	{		tyArray__cleXh9bMEnUU9aNvjKX8m6BA buffer;		NU T5_;
#line 203 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/hmac.nim"

#line 203 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/hmac.nim"
		if (!(((NI) 32) <= data_0Len_0)) goto LA3_;
		nimZeroMem((void*)buffer, sizeof(tyArray__cleXh9bMEnUU9aNvjKX8m6BA));
#line 205 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/hmac.nim"

#line 205 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/hmac.nim"

#line 205 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/hmac.nim"
		T5_ = (NU)0;		T5_ = finish__XWD9ckGqZzLMH9bax9c7RDdGgsha2((&(*hmctx).mdctx), buffer, 32);		(void)(T5_);

#line 206 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/hmac.nim"

#line 206 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/hmac.nim"
		update__JVKV5lsc6z00iHHbNwyg9bAsha2((&(*hmctx).opadctx), buffer, 32);

#line 207 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/hmac.nim"

#line 207 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/hmac.nim"
		result = finish__XWD9ckGqZzLMH9bax9c7RDdGgsha2((&(*hmctx).opadctx), data_0, data_0Len_0);	}
	LA3_: ;
	return result;}

#line 18 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/pbkdf2.nim"
N_LIB_PRIVATE N_NIMCALL(NI, pbkdf2__6wklsCL9aWim43yDdPV9aFkQ)(tyObject_HMAC__CxVfcs3qQxev4nVq3Txjyg* ctx, NU8* password, NI passwordLen_0, NIM_CHAR* salt, NI saltLen_0, NI c, NU8* output, NI outputLen_0) {	NI result;	tyArray__H8qf9bpC2ziYA2earmO8m7w counter;	tyArray__vEOa9c5qaE9ajWxR5R4zwfQg work;	tyArray__vEOa9c5qaE9ajWxR5R4zwfQg md;	NU32 ctr_1;	NI glength;	NI bytesWrite;	NI olength;	result = (NI)0;
#line 21 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/pbkdf2.nim"
	nimZeroMem((void*)counter, sizeof(tyArray__H8qf9bpC2ziYA2earmO8m7w));	nimZeroMem((void*)work, sizeof(tyArray__vEOa9c5qaE9ajWxR5R4zwfQg));	nimZeroMem((void*)md, sizeof(tyArray__vEOa9c5qaE9ajWxR5R4zwfQg));	ctr_1 = (NU32)0;	glength = (NI)0;	bytesWrite = (NI)0;
#line 48 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/pbkdf2.nim"
	ctr_1 = ((NU32) 1);
#line 49 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/pbkdf2.nim"
	glength = ((NI) 0);
#line 50 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/pbkdf2.nim"

#line 52 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/pbkdf2.nim"

#line 52 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/pbkdf2.nim"
	olength = ((outputLen_0 <= ((NI) IL64(4294967295))) ? outputLen_0 : ((NI) IL64(4294967295)));	{
#line 56 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/pbkdf2.nim"
		while (1) {			NU T3_;			NI TM__0a29c9b3bMduzcVNZQPcw9bGg_14;			NI TM__0a29c9b3bMduzcVNZQPcw9bGg_15;			NI TM__0a29c9b3bMduzcVNZQPcw9bGg_16;
#line 56 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/pbkdf2.nim"
			if (!(glength < olength)) goto LA2;

#line 373 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/utils.nim"

#line 373 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/utils.nim"
			(*((NU32*) ((&counter[(((NI) 0))- 0])))) = __builtin_bswap32(ctr_1);
#line 58 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/pbkdf2.nim"

#line 58 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/pbkdf2.nim"
			init__XO79cz0G5x9bYWx3NREUG23g(ctx, password, passwordLen_0);

#line 59 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/pbkdf2.nim"

#line 59 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/pbkdf2.nim"
			update__JlxQJoHy4ZmcjsPUc3vq1ghmac(ctx, salt, saltLen_0);

#line 60 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/pbkdf2.nim"

#line 60 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/pbkdf2.nim"
			update__JDQKL6F3d4BVGKvrNMc9bmghmac(ctx, counter, 4);

#line 61 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/pbkdf2.nim"

#line 61 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/pbkdf2.nim"

#line 61 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/pbkdf2.nim"
			T3_ = (NU)0;			T3_ = finish__21C9bb9bs8ZSGFBr7oxmCmkghmac(ctx, md, 32);			(void)(T3_);

#line 62 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/pbkdf2.nim"
			nimCopyMem((void*)work, (NIM_CONST void*)md, sizeof(tyArray__vEOa9c5qaE9ajWxR5R4zwfQg));			{				NI i;				NI i_2;				i = (NI)0;
#line 106 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators_1.nim"
				i_2 = ((NI) 1);				{
#line 107 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators_1.nim"
					while (1) {						NU T7_;						NI TM__0a29c9b3bMduzcVNZQPcw9bGg_13;
#line 107 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators_1.nim"
						if (!(i_2 < c)) goto LA6;

#line 63 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/pbkdf2.nim"
						i = i_2;
#line 64 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/pbkdf2.nim"

#line 64 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/pbkdf2.nim"
						init__XO79cz0G5x9bYWx3NREUG23g(ctx, password, passwordLen_0);

#line 65 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/pbkdf2.nim"

#line 65 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/pbkdf2.nim"
						update__JDQKL6F3d4BVGKvrNMc9bmghmac(ctx, md, 32);

#line 66 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/pbkdf2.nim"

#line 66 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/pbkdf2.nim"

#line 66 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/pbkdf2.nim"
						T7_ = (NU)0;						T7_ = finish__21C9bb9bs8ZSGFBr7oxmCmkghmac(ctx, md, 32);						(void)(T7_);
						{							NI k;							NI i_3;							k = (NI)0;
#line 106 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators_1.nim"
							i_3 = ((NI) 0);							{
#line 107 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators_1.nim"
								while (1) {									NI TM__0a29c9b3bMduzcVNZQPcw9bGg_12;
#line 107 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators_1.nim"
									if (!(i_3 < ((NI) 32))) goto LA10;

#line 67 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/pbkdf2.nim"
									k = i_3;									if ((NU)(k) > (NU)(31)){ raiseIndexError2(k, 31); }
#line 68 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/pbkdf2.nim"

#line 68 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/pbkdf2.nim"
									if ((NU)(k) > (NU)(31)){ raiseIndexError2(k, 31); }									if ((NU)(k) > (NU)(31)){ raiseIndexError2(k, 31); }									work[(k)- 0] = (NU8)(work[(k)- 0] ^ md[(k)- 0]);
#line 109 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators_1.nim"
									if (nimAddInt(i_3, ((NI) 1), &TM__0a29c9b3bMduzcVNZQPcw9bGg_12)) { raiseOverflow(); };									i_3 = (NI)(TM__0a29c9b3bMduzcVNZQPcw9bGg_12);								} LA10: ;
							}
						}

#line 109 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators_1.nim"
						if (nimAddInt(i_2, ((NI) 1), &TM__0a29c9b3bMduzcVNZQPcw9bGg_13)) { raiseOverflow(); };						i_2 = (NI)(TM__0a29c9b3bMduzcVNZQPcw9bGg_13);					} LA6: ;
				}
			}

#line 70 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/pbkdf2.nim"

#line 70 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/pbkdf2.nim"

#line 70 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/pbkdf2.nim"
			if (nimSubInt(olength, glength, &TM__0a29c9b3bMduzcVNZQPcw9bGg_14)) { raiseOverflow(); };			bytesWrite = (((NI)(TM__0a29c9b3bMduzcVNZQPcw9bGg_14) <= ((NI) 32)) ? (NI)(TM__0a29c9b3bMduzcVNZQPcw9bGg_14) : ((NI) 32));
#line 417 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/utils.nim"
			if ((NU)(glength) >= (NU)(outputLen_0)){ raiseIndexError2(glength,outputLen_0-1); }
#line 417 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/utils.nim"
			if (nimMulInt(bytesWrite, ((NI) 1), &TM__0a29c9b3bMduzcVNZQPcw9bGg_15)) { raiseOverflow(); };			if (((NI)(TM__0a29c9b3bMduzcVNZQPcw9bGg_15)) < ((NI) 0) || ((NI)(TM__0a29c9b3bMduzcVNZQPcw9bGg_15)) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__0a29c9b3bMduzcVNZQPcw9bGg_15), ((NI) 0), ((NI) IL64(9223372036854775807))); }
#line 417 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/utils.nim"
			copyMem__i80o3k0SgEI5gTRCzYdyWAsystem(((void*) ((&output[glength]))), ((void*) ((&work[(((NI) 0))- 0]))), ((NI) ((NI)(TM__0a29c9b3bMduzcVNZQPcw9bGg_15))));

#line 72 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/pbkdf2.nim"

#line 72 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/pbkdf2.nim"
			if (nimAddInt(glength, bytesWrite, &TM__0a29c9b3bMduzcVNZQPcw9bGg_16)) { raiseOverflow(); };			glength = (NI)(TM__0a29c9b3bMduzcVNZQPcw9bGg_16);
#line 73 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/pbkdf2.nim"

#line 73 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/pbkdf2.nim"
			ctr_1 = (NU32)((NU32)(ctr_1) + (NU32)(((NU32) 1)));		} LA2: ;
	}

#line 74 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/pbkdf2.nim"

#line 74 "/home/runner/work/nim-waku/nim-waku/vendor/nimcrypto/nimcrypto/pbkdf2.nim"
	clear__3PkHS3KRpSG9bEaZCBbhR4w_2(ctx);
	result = glength;	return result;}
