/* Generated by Nim Compiler v1.2.6 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -pthread -I/home/runner/work/nim-waku/nim-waku/vendor/nim-libbacktrace -I/home/runner/work/nim-waku/nim-waku/vendor/nim-libbacktrace/install/usr/include -I/home/runner/work/nim-waku/nim-waku/vendor/nim-secp256k1/secp256k1_wrapper -I/home/runner/work/nim-waku/nim-waku/vendor/nim-secp256k1/secp256k1_wrapper/secp256k1 -I/home/runner/work/nim-waku/nim-waku/vendor/nim-secp256k1/secp256k1_wrapper/secp256k1/src -DHAVE_CONFIG_H -DHAVE_BUILTIN_EXPECT -I/home/runner/work/nim-waku/nim-waku/vendor/nim-bearssl/bearssl/csources/src -I/home/runner/work/nim-waku/nim-waku/vendor/nim-bearssl/bearssl/csources/inc -I/home/runner/work/nim-waku/nim-waku/vendor/nim-bearssl/bearssl/csources/tools -DBR_USE_UNIX_TIME=1 -DBR_USE_URANDOM=1 -DBR_LE_UNALIGNED=1 -DBR_64=1  -DBR_amd64=1 -DBR_INT128=1 -I/home/runner/work/nim-waku/nim-waku/vendor/nim-bearssl/bearssl/certs -I/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/vendor/miniupnp/miniupnpc -I/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/vendor/libnatpmp-upstream -DENABLE_STRNATPMPERR -march=native -g3 -Og -O3 -fno-strict-aliasing -fno-ident  -I/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib -I/home/runner/work/nim-waku/nim-waku/examples/v2 -o nimcache/release/chat2/@m..@s..@svendor@snim-libp2p@slibp2p@speerinfo.nim.c.o nimcache/release/chat2/@m..@s..@svendor@snim-libp2p@slibp2p@speerinfo.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <sys/types.h>
                          #include <pthread.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw;
typedef struct RootObj RootObj;
typedef struct tyObject_PeerID__Se8YyoPxzDpFnTeAyeCVCw tyObject_PeerID__Se8YyoPxzDpFnTeAyeCVCw;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ tySequence__6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct tySequence__pJDjdGjSf3HlAOELaHOmSA tySequence__pJDjdGjSf3HlAOELaHOmSA;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_PrivateKey__GSDbMQxBVd3KO4qBUjzPKQ tyObject_PrivateKey__GSDbMQxBVd3KO4qBUjzPKQ;
typedef struct tyObject_RsaPrivateKeycolonObjectType___xFWT9bk7KDVd9cMFfRtPM9c9bw tyObject_RsaPrivateKeycolonObjectType___xFWT9bk7KDVd9cMFfRtPM9c9bw;
typedef struct tyObject_EdPrivateKey__KumOofCUWyjlYLnvXlcIJA tyObject_EdPrivateKey__KumOofCUWyjlYLnvXlcIJA;
typedef struct tyObject_SkSecretKey__aKiBFtqo69b60sWLnM5A9c3w tyObject_SkSecretKey__aKiBFtqo69b60sWLnM5A9c3w;
typedef struct tyObject_EcPrivateKeycolonObjectType___OJbV39curmS5TCBXopR7itA tyObject_EcPrivateKeycolonObjectType___OJbV39curmS5TCBXopR7itA;
typedef struct tyObject_Option__Em5DpQtK80JNdy8nyXe6Kg tyObject_Option__Em5DpQtK80JNdy8nyXe6Kg;
typedef struct tyObject_PublicKey__mVKS59bRpscItosS0oN9a4zA tyObject_PublicKey__mVKS59bRpscItosS0oN9a4zA;
typedef struct tyObject_RsaPublicKeycolonObjectType___cEZIZ6MRRYNM7g7RvdoBpg tyObject_RsaPublicKeycolonObjectType___cEZIZ6MRRYNM7g7RvdoBpg;
typedef struct tyObject_EdPublicKey__fCTHNrLwOTcb1HatTDTAEA tyObject_EdPublicKey__fCTHNrLwOTcb1HatTDTAEA;
typedef struct tyObject_SkPublicKey__YxxaGK7KOKaWCOaZ44rHMA tyObject_SkPublicKey__YxxaGK7KOKaWCOaZ44rHMA;
typedef struct tyObject_secp256k1_pubkey__GYc9aFo1e2qOLdmAqUvIikQ tyObject_secp256k1_pubkey__GYc9aFo1e2qOLdmAqUvIikQ;
typedef struct tyObject_EcPublicKeycolonObjectType___2rc9bUkP8wBzp3UeWWgE9b5Q tyObject_EcPublicKeycolonObjectType___2rc9bUkP8wBzp3UeWWgE9b5Q;
typedef struct tyObject_MultiAddress__MntiKgxV52rXueBQXpXCJw tyObject_MultiAddress__MntiKgxV52rXueBQXpXCJw;
typedef struct tyObject_VBuffer__pgrKDkZLiJID3rDHrYm5UA tyObject_VBuffer__pgrKDkZLiJID3rDHrYm5UA;
typedef struct tyObject_Result__vwq6q8V74XCA8dzFvuzU1Q tyObject_Result__vwq6q8V74XCA8dzFvuzU1Q;
typedef struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack__7fytPA5bBsob6See21YMRA tyObject_GcStack__7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyTuple__ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw;
typedef struct tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg;
typedef struct tyTuple__NevGmcPz5FN13v9cZPsfRXw tyTuple__NevGmcPz5FN13v9cZPsfRXw;
typedef struct tyObject_Result__rRs2IHyL9cPDf0qPXyWd1oQ tyObject_Result__rRs2IHyL9cPDf0qPXyWd1oQ;
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {NI size;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
NCSTRING name;
TNimType* nextType;
NI instances;
NI sizes;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct RootObj {TNimType* m_type;};
struct tyObject_PeerID__Se8YyoPxzDpFnTeAyeCVCw {tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* data;
};
struct TGenericSeq {NI len;
NI reserved;
};
struct NimStringDesc {  TGenericSeq Sup;NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_KeyType__RX9cgRnEh9bnsWx9cuPhqOgtw;
typedef NU8 tyEnum_PKScheme__GeN4EiKxd9aXAvv5y1lfmHg;
typedef NU8 tyArray__w5VB8h5K8DB3oWrO5U2wqg[64];
struct tyObject_EdPrivateKey__KumOofCUWyjlYLnvXlcIJA {tyArray__w5VB8h5K8DB3oWrO5U2wqg data;
};
typedef NU8 tyArray__vEOa9c5qaE9ajWxR5R4zwfQg[32];
struct tyObject_SkSecretKey__aKiBFtqo69b60sWLnM5A9c3w {tyArray__vEOa9c5qaE9ajWxR5R4zwfQg data;
};
struct tyObject_PrivateKey__GSDbMQxBVd3KO4qBUjzPKQ {tyEnum_PKScheme__GeN4EiKxd9aXAvv5y1lfmHg scheme;
union{
struct {tyObject_RsaPrivateKeycolonObjectType___xFWT9bk7KDVd9cMFfRtPM9c9bw* rsakey;
} _scheme_1;
struct {tyObject_EdPrivateKey__KumOofCUWyjlYLnvXlcIJA edkey;
} _scheme_2;
struct {tyObject_SkSecretKey__aKiBFtqo69b60sWLnM5A9c3w skkey;
} _scheme_3;
struct {tyObject_EcPrivateKeycolonObjectType___OJbV39curmS5TCBXopR7itA* eckey;
} _scheme_4;
};
};
struct tyObject_EdPublicKey__fCTHNrLwOTcb1HatTDTAEA {tyArray__vEOa9c5qaE9ajWxR5R4zwfQg data;
};
struct tyObject_secp256k1_pubkey__GYc9aFo1e2qOLdmAqUvIikQ {tyArray__w5VB8h5K8DB3oWrO5U2wqg data;
};
struct tyObject_SkPublicKey__YxxaGK7KOKaWCOaZ44rHMA {tyObject_secp256k1_pubkey__GYc9aFo1e2qOLdmAqUvIikQ data;
};
struct tyObject_PublicKey__mVKS59bRpscItosS0oN9a4zA {tyEnum_PKScheme__GeN4EiKxd9aXAvv5y1lfmHg scheme;
union{
struct {tyObject_RsaPublicKeycolonObjectType___cEZIZ6MRRYNM7g7RvdoBpg* rsakey;
} _scheme_1;
struct {tyObject_EdPublicKey__fCTHNrLwOTcb1HatTDTAEA edkey;
} _scheme_2;
struct {tyObject_SkPublicKey__YxxaGK7KOKaWCOaZ44rHMA skkey;
} _scheme_3;
struct {tyObject_EcPublicKeycolonObjectType___2rc9bUkP8wBzp3UeWWgE9b5Q* eckey;
} _scheme_4;
};
};
struct tyObject_Option__Em5DpQtK80JNdy8nyXe6Kg {tyObject_PublicKey__mVKS59bRpscItosS0oN9a4zA val;
NIM_BOOL has;
};
struct tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw {  RootObj Sup;tyObject_PeerID__Se8YyoPxzDpFnTeAyeCVCw peerId;
tySequence__pJDjdGjSf3HlAOELaHOmSA* addrs;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* protocols;
NimStringDesc* protoVersion;
NimStringDesc* agentVersion;
NimStringDesc* secure;
tyEnum_KeyType__RX9cgRnEh9bnsWx9cuPhqOgtw keyType;
union{
struct {tyObject_PrivateKey__GSDbMQxBVd3KO4qBUjzPKQ privateKey;
} _keyType_1;
struct {tyObject_Option__Em5DpQtK80JNdy8nyXe6Kg key;
} _keyType_2;
};
};
struct tyObject_VBuffer__pgrKDkZLiJID3rDHrYm5UA {tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* buffer;
NI offset;
};
struct tyObject_MultiAddress__MntiKgxV52rXueBQXpXCJw {tyObject_VBuffer__pgrKDkZLiJID3rDHrYm5UA data;
};
typedef NU8 tyEnum_CryptoError__Z6S5YnPavFcXanJgC9cU1uw;
struct tyObject_Result__vwq6q8V74XCA8dzFvuzU1Q {NIM_BOOL o;
union{
struct {tyEnum_CryptoError__Z6S5YnPavFcXanJgC9cU1uw e;
} _o_1;
struct {tyObject_PublicKey__mVKS59bRpscItosS0oN9a4zA v;
} _o_2;
};
};
struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g {NI refcount;
TNimType* typ;
};
struct tyObject_GcStack__7fytPA5bBsob6See21YMRA {void* bottom;
};
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w {NI len;
NI cap;
tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ* tyArray__SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* tyArray__N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray__N1u1nqOgmuJN9cSZrnMHgOQ tyArray__B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw* tyArray__lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA {tyArray__lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* tyArray__0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw {tyArray__0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyArray__LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg {NI len;
tyArray__LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg {NI minLargeObj;
NI maxLargeObj;
tyArray__SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray__B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
NI allocCounter;
NI deallocCounter;
};
struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg {NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ {NI counter;
NI max;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg** data;
};
typedef long tyArray__xDUyu9aScDpt0JZLU6q9aEZQ[5];
struct tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw {tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg* head;
tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg* tail;
pthread_mutex_t lock;
};
struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ {tyObject_GcStack__7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w additionalRoots;
tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw toDispose;
NI gcThreadId;
};
struct tyTuple__NevGmcPz5FN13v9cZPsfRXw {
NimStringDesc* Field0;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* Field1;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* Field2;
NimStringDesc* Field3;
NimStringDesc* Field4;
};
struct tyObject_Result__rRs2IHyL9cPDf0qPXyWd1oQ {NIM_BOOL o;
union{
struct {NCSTRING e;
} _o_1;
struct {tyObject_PeerID__Se8YyoPxzDpFnTeAyeCVCw v;
} _o_2;
};
};
struct tySequence__pJDjdGjSf3HlAOELaHOmSA {  TGenericSeq Sup;  tyObject_MultiAddress__MntiKgxV52rXueBQXpXCJw data[SEQ_DECL_SIZE];};struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {  TGenericSeq Sup;  NimStringDesc* data[SEQ_DECL_SIZE];};struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ {  TGenericSeq Sup;  NU8 data[SEQ_DECL_SIZE];};N_LIB_PRIVATE N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence__pJDjdGjSf3HlAOELaHOmSA)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef__Ol4zKcKZGzrnu3Hvu9aLd4w)(void* p, NI op);
N_LIB_PRIVATE N_NOINLINE(void, chckNil)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasPublicKey__kmLkXiaxy8lRGzIsV2u6Kw)(tyObject_PeerID__Se8YyoPxzDpFnTeAyeCVCw pid);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, extractPublicKey__oFQyDfGKphQulEV9cuwMmxg)(tyObject_PeerID__Se8YyoPxzDpFnTeAyeCVCw pid, tyObject_PublicKey__mVKS59bRpscItosS0oN9a4zA* pubkey);
static N_INLINE(void, some__YlT9b9adM2MeSxLm8RgQSNmQoptions)(tyObject_PublicKey__mVKS59bRpscItosS0oN9a4zA* val_0, tyObject_Option__Em5DpQtK80JNdy8nyXe6Kg* Result);
N_LIB_PRIVATE N_NIMCALL(void, genericAssign)(void* dest_0, void* src, TNimType* mt);
static N_INLINE(NIM_BOOL, isSome__Bn3YxM1m1k5x4JHBlBTavg_2options)(tyObject_Option__Em5DpQtK80JNdy8nyXe6Kg* self);
N_LIB_PRIVATE N_NOINLINE(void, raiseFieldError)(NimStringDesc* f);
static N_INLINE(void, tryGet__VeMgo2Cp9aeBXhskxVN2WeAresults)(tyObject_Result__vwq6q8V74XCA8dzFvuzU1Q* self, tyObject_PublicKey__mVKS59bRpscItosS0oN9a4zA* Result);
N_LIB_PRIVATE N_NOINLINE(void, raiseResultError__d2pyGBpUxBG7xw7hcLOp0g)(tyObject_Result__vwq6q8V74XCA8dzFvuzU1Q* self) __attribute__((noreturn));
N_LIB_PRIVATE N_NIMCALL(void, getKey__BjB2ThDklmRLi5zxNp1MMg)(tyObject_PrivateKey__GSDbMQxBVd3KO4qBUjzPKQ* key_0, tyObject_Result__vwq6q8V74XCA8dzFvuzU1Q* Result);
N_LIB_PRIVATE N_NIMCALL(void, genericShallowAssign)(void* dest_0, void* src, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(void, genericSeqAssign)(void* dest_0, void* src, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(tySequence__pJDjdGjSf3HlAOELaHOmSA*, at___21kMoC1r79cndXPAdhT9b7Wg)(tyObject_MultiAddress__MntiKgxV52rXueBQXpXCJw* a, NI aLen_0);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef__AT1eRuflKWyTTBdLjEDZbg_3system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, pluspercent___dgYAo7RfdUVVpvkfKDym8wsystem)(NI x, NI y);
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem)(void* usr);
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8w_2system)(NI x, NI y);
static N_INLINE(void, decRef__AT1eRuflKWyTTBdLjEDZbgsystem)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NIM_BOOL, ltpercent___hPljn3JCDQ00ua1R07X9bxQsystem)(NI x, NI y);
static N_INLINE(void, rtlAddZCT__AT1eRuflKWyTTBdLjEDZbg_2system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__Y66tOYFjgwJ0k4aLz4bc0Q)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ*, at___9au1Hh5AAg9cMC8zv7hfdWBg)(NimStringDesc** a, NI aLen_0);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___YvhybdNIMaDdbU9cTJva0oQ_2)(tyObject_PeerID__Se8YyoPxzDpFnTeAyeCVCw pid);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ*, newSeq__q7W9bxIQ7BrFLngLO9cYelsA)(NI len_0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___9clTvx1x9boEUsy637oTVrWA)(tyObject_MultiAddress__MntiKgxV52rXueBQXpXCJw value_0);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A)(NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(void, tryGet__ME7aJ9cmvtfOzZSR3TgduCAresults)(tyObject_Result__rRs2IHyL9cPDf0qPXyWd1oQ self, tyObject_PeerID__Se8YyoPxzDpFnTeAyeCVCw* Result);
N_LIB_PRIVATE N_NOINLINE(void, raiseResultError__3mB4FvIEM5rjrsbjkbEISw)(tyObject_Result__rRs2IHyL9cPDf0qPXyWd1oQ self) __attribute__((noreturn));
N_LIB_PRIVATE N_NIMCALL(void, init__KPadYF1p4m3d6OsV2MZGYQ)(tyObject_PrivateKey__GSDbMQxBVd3KO4qBUjzPKQ* seckey, tyObject_Result__rRs2IHyL9cPDf0qPXyWd1oQ* Result);
N_LIB_PRIVATE N_NIMCALL(void, init__62yqKJpN4T5rhMXt9cfWICA)(tyObject_PublicKey__mVKS59bRpscItosS0oN9a4zA* pubkey, tyObject_Result__rRs2IHyL9cPDf0qPXyWd1oQ* Result);
N_LIB_PRIVATE N_NIMCALL(void, init__9cVMRbKcykqNIIPeD9aOhmYA)(NimStringDesc* data_0, tyObject_Result__rRs2IHyL9cPDf0qPXyWd1oQ* Result);
extern TNimType NTI__ytyiCJqK439aF9cIibuRVpAg_;
N_LIB_PRIVATE TNimType NTI__tniXhe3Zv7xQqYX3AOw9aQw_;
extern TNimType NTI__Se8YyoPxzDpFnTeAyeCVCw_;
extern TNimType NTI__MntiKgxV52rXueBQXpXCJw_;
N_LIB_PRIVATE TNimType NTI__pJDjdGjSf3HlAOELaHOmSA_;
extern TNimType NTI__sM4lkSb7zS6F7OVMvW9cffQ_;
extern TNimType NTI__77mFvmsOLKik79ci2hXkHEg_;
N_LIB_PRIVATE TNimType NTI__RX9cgRnEh9bnsWx9cuPhqOgtw_;
TNimNode* NimDT___tniXhe3Zv7xQqYX3AOw9aQw_keyType[3];
extern TNimType NTI__GSDbMQxBVd3KO4qBUjzPKQ_;
extern TNimType NTI__Em5DpQtK80JNdy8nyXe6Kg_;
N_LIB_PRIVATE TNimType NTI__Ol4zKcKZGzrnu3Hvu9aLd4w_;
extern TNimType NTI__mVKS59bRpscItosS0oN9a4zA_;
STRING_LITERAL(TM__3YpbmuYVI9cMPTLRuWDLclA_6, "\'key\' is not accessible using discriminant \'keyType\' of type \'P"
"eerInfo\'", 71);
STRING_LITERAL(TM__3YpbmuYVI9cMPTLRuWDLclA_7, "\'v\' is not accessible using discriminant \'o\' of type \'Result\'", 61);
STRING_LITERAL(TM__3YpbmuYVI9cMPTLRuWDLclA_8, "\'privateKey\' is not accessible using discriminant \'keyType\' of "
"type \'PeerInfo\'", 78);
extern TNimType NTI__6H5Oh5UUvVCLiakt9aTwtUQ_;
STRING_LITERAL(TM__3YpbmuYVI9cMPTLRuWDLclA_11, "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/"
"vendor/Nim/lib/system/iterators.nim(189, 11) `len(a) == L` the l"
"ength of the seq changed while iterating over it", 175);
extern TNimType* nimTypeRoot;
extern NIM_THREADVAR tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ gch__IcYaEuuWivYAS86vFMTS3Q;
static N_NIMCALL(void, Marker_tySequence__pJDjdGjSf3HlAOELaHOmSA)(void* p, NI op) {
	tySequence__pJDjdGjSf3HlAOELaHOmSA* a;
	NI T1_;	a = (tySequence__pJDjdGjSf3HlAOELaHOmSA*)p;
	T1_ = (NI)0;	for (T1_ = 0; T1_ < (a ? a->Sup.len : 0); T1_++) {
	nimGCvisit((void*)a->data[T1_].data.buffer, op);	}
}
static N_NIMCALL(void, Marker_tyRef__Ol4zKcKZGzrnu3Hvu9aLd4w)(void* p, NI op) {
	tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw* a;
	NI T1_;	NI T2_;	NI T3_;	NI T4_;	a = (tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw*)p;
	nimGCvisit((void*)(*a).peerId.data, op);	nimGCvisit((void*)(*a).addrs, op);	nimGCvisit((void*)(*a).protocols, op);	nimGCvisit((void*)(*a).protoVersion, op);	nimGCvisit((void*)(*a).agentVersion, op);	nimGCvisit((void*)(*a).secure, op);	switch ((*a).keyType) {
	case ((tyEnum_KeyType__RX9cgRnEh9bnsWx9cuPhqOgtw) 0):
	switch ((*a)._keyType_1.privateKey.scheme) {
	case ((tyEnum_PKScheme__GeN4EiKxd9aXAvv5y1lfmHg) 0):
	nimGCvisit((void*)(*a)._keyType_1.privateKey._scheme_1.rsakey, op);	break;
	case ((tyEnum_PKScheme__GeN4EiKxd9aXAvv5y1lfmHg) 1):
	T1_ = (NI)0;	break;
	case ((tyEnum_PKScheme__GeN4EiKxd9aXAvv5y1lfmHg) 2):
	T2_ = (NI)0;	break;
	case ((tyEnum_PKScheme__GeN4EiKxd9aXAvv5y1lfmHg) 3):
	nimGCvisit((void*)(*a)._keyType_1.privateKey._scheme_4.eckey, op);	break;
	} 
	break;
	case ((tyEnum_KeyType__RX9cgRnEh9bnsWx9cuPhqOgtw) 1):
	switch ((*a)._keyType_2.key.val.scheme) {
	case ((tyEnum_PKScheme__GeN4EiKxd9aXAvv5y1lfmHg) 0):
	nimGCvisit((void*)(*a)._keyType_2.key.val._scheme_1.rsakey, op);	break;
	case ((tyEnum_PKScheme__GeN4EiKxd9aXAvv5y1lfmHg) 1):
	T3_ = (NI)0;	break;
	case ((tyEnum_PKScheme__GeN4EiKxd9aXAvv5y1lfmHg) 2):
	T4_ = (NI)0;	break;
	case ((tyEnum_PKScheme__GeN4EiKxd9aXAvv5y1lfmHg) 3):
	nimGCvisit((void*)(*a)._keyType_2.key.val._scheme_4.eckey, op);	break;
	} 
	break;
	} 
}

#line 22 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size) {	void* T1_;
#line 24 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"

#line 24 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memset(a, v, ((size_t) (size)));}

#line 33 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
#line 34 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"

#line 34 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"
	nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory(p, ((int) 0), size);
}

#line 101 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/options.nim"
static N_INLINE(void, some__YlT9b9adM2MeSxLm8RgQSNmQoptions)(tyObject_PublicKey__mVKS59bRpscItosS0oN9a4zA* val_0, tyObject_Option__Em5DpQtK80JNdy8nyXe6Kg* Result) {	NI T1_;	NI T2_;	chckNil((void*)Result);	switch ((*Result).val.scheme) {
	case ((tyEnum_PKScheme__GeN4EiKxd9aXAvv5y1lfmHg) 0):
	unsureAsgnRef((void**)&(*Result).val._scheme_1.rsakey, NIM_NIL);	break;
	case ((tyEnum_PKScheme__GeN4EiKxd9aXAvv5y1lfmHg) 1):
	T1_ = (NI)0;	for (T1_ = 0; T1_ < 32; T1_++) {	(*Result).val._scheme_2.edkey.data[T1_] = 0;	}
	break;
	case ((tyEnum_PKScheme__GeN4EiKxd9aXAvv5y1lfmHg) 2):
	T2_ = (NI)0;	for (T2_ = 0; T2_ < 64; T2_++) {	(*Result).val._scheme_3.skkey.data.data[T2_] = 0;	}
	break;
	case ((tyEnum_PKScheme__GeN4EiKxd9aXAvv5y1lfmHg) 3):
	unsureAsgnRef((void**)&(*Result).val._scheme_4.eckey, NIM_NIL);	break;
	} 
	(*Result).val.scheme = 0;	(*Result).has = 0;
#line 121 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/options.nim"
	(*Result).has = NIM_TRUE;
#line 122 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/options.nim"
	genericAssign((void*)(&(*Result).val), (void*)val_0, (&NTI__mVKS59bRpscItosS0oN9a4zA_));}

#line 143 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/options.nim"
static N_INLINE(NIM_BOOL, isSome__Bn3YxM1m1k5x4JHBlBTavg_2options)(tyObject_Option__Em5DpQtK80JNdy8nyXe6Kg* self) {	NIM_BOOL result;	result = (NIM_BOOL)0;
#line 144 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/options.nim"
	result = (*self).has;	return result;}

#line 466 "/home/runner/work/nim-waku/nim-waku/vendor/nim-stew/stew/results.nim"
static N_INLINE(void, tryGet__VeMgo2Cp9aeBXhskxVN2WeAresults)(tyObject_Result__vwq6q8V74XCA8dzFvuzU1Q* self, tyObject_PublicKey__mVKS59bRpscItosS0oN9a4zA* Result) {
#line 467 "/home/runner/work/nim-waku/nim-waku/vendor/nim-stew/stew/results.nim"

#line 470 "/home/runner/work/nim-waku/nim-waku/vendor/nim-stew/stew/results.nim"
	{
#line 470 "/home/runner/work/nim-waku/nim-waku/vendor/nim-stew/stew/results.nim"
		if (!!((*self).o)) goto LA3_;

#line 470 "/home/runner/work/nim-waku/nim-waku/vendor/nim-stew/stew/results.nim"

#line 470 "/home/runner/work/nim-waku/nim-waku/vendor/nim-stew/stew/results.nim"
		raiseResultError__d2pyGBpUxBG7xw7hcLOp0g(self);
	}
	LA3_: ;
	if (!(((2 &(1U<<((NU)((*self).o)&7U)))!=0))){ raiseFieldError(((NimStringDesc*) &TM__3YpbmuYVI9cMPTLRuWDLclA_7)); }	genericAssign((void*)Result, (void*)(&(*self)._o_2.v), (&NTI__mVKS59bRpscItosS0oN9a4zA_));}

#line 97 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
N_LIB_PRIVATE N_NIMCALL(void, publicKey__L6OwfE68JciWVnUJkGdxOA)(tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw* p_0, tyObject_Option__Em5DpQtK80JNdy8nyXe6Kg* Result) {	NI T1_;	NI T2_;	chckNil((void*)Result);	switch ((*Result).val.scheme) {
	case ((tyEnum_PKScheme__GeN4EiKxd9aXAvv5y1lfmHg) 0):
	unsureAsgnRef((void**)&(*Result).val._scheme_1.rsakey, NIM_NIL);	break;
	case ((tyEnum_PKScheme__GeN4EiKxd9aXAvv5y1lfmHg) 1):
	T1_ = (NI)0;	for (T1_ = 0; T1_ < 32; T1_++) {	(*Result).val._scheme_2.edkey.data[T1_] = 0;	}
	break;
	case ((tyEnum_PKScheme__GeN4EiKxd9aXAvv5y1lfmHg) 2):
	T2_ = (NI)0;	for (T2_ = 0; T2_ < 64; T2_++) {	(*Result).val._scheme_3.skkey.data.data[T2_] = 0;	}
	break;
	case ((tyEnum_PKScheme__GeN4EiKxd9aXAvv5y1lfmHg) 3):
	unsureAsgnRef((void**)&(*Result).val._scheme_4.eckey, NIM_NIL);	break;
	} 
	(*Result).val.scheme = 0;	(*Result).has = 0;
#line 99 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
	{
#line 99 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
		if (!((*p_0).keyType == ((tyEnum_KeyType__RX9cgRnEh9bnsWx9cuPhqOgtw) 1))) goto LA5_;

#line 100 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
		{			NIM_BOOL T9_;			tyObject_PublicKey__mVKS59bRpscItosS0oN9a4zA pubKey;
#line 100 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"

#line 100 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
			T9_ = (NIM_BOOL)0;			T9_ = hasPublicKey__kmLkXiaxy8lRGzIsV2u6Kw((*p_0).peerId);			if (!T9_) goto LA10_;
			nimZeroMem((void*)(&pubKey), sizeof(tyObject_PublicKey__mVKS59bRpscItosS0oN9a4zA));
#line 102 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
			{				NIM_BOOL T14_;
#line 102 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"

#line 102 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
				T14_ = (NIM_BOOL)0;				T14_ = extractPublicKey__oFQyDfGKphQulEV9cuwMmxg((*p_0).peerId, (&pubKey));				if (!T14_) goto LA15_;

#line 103 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"

#line 103 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
				some__YlT9b9adM2MeSxLm8RgQSNmQoptions((&pubKey), Result);
			}
			LA15_: ;
		}
		goto LA7_;
		LA10_: ;
		{			NIM_BOOL T18_;
#line 104 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
			if (!(((2 &(1U<<((NU)((*p_0).keyType)&7U)))!=0))){ raiseFieldError(((NimStringDesc*) &TM__3YpbmuYVI9cMPTLRuWDLclA_6)); }
#line 104 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
			T18_ = (NIM_BOOL)0;			T18_ = isSome__Bn3YxM1m1k5x4JHBlBTavg_2options((&(*p_0)._keyType_2.key));			if (!T18_) goto LA19_;

#line 105 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
			if (!(((2 &(1U<<((NU)((*p_0).keyType)&7U)))!=0))){ raiseFieldError(((NimStringDesc*) &TM__3YpbmuYVI9cMPTLRuWDLclA_6)); }			genericAssign((void*)(&(*Result).val), (void*)(&(*p_0)._keyType_2.key.val), (&NTI__mVKS59bRpscItosS0oN9a4zA_));			(*Result).has = (*p_0)._keyType_2.key.has;		}
		goto LA7_;
		LA19_: ;
		LA7_: ;
	}
	goto LA3_;
	LA5_: ;
	{		tyObject_Result__vwq6q8V74XCA8dzFvuzU1Q T22_;		tyObject_PublicKey__mVKS59bRpscItosS0oN9a4zA T23_;		tyObject_Option__Em5DpQtK80JNdy8nyXe6Kg T24_;
#line 107 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"

#line 107 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"

#line 107 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
		if (!(((1 &(1U<<((NU)((*p_0).keyType)&7U)))!=0))){ raiseFieldError(((NimStringDesc*) &TM__3YpbmuYVI9cMPTLRuWDLclA_8)); }
#line 107 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
		nimZeroMem((void*)(&T22_), sizeof(tyObject_Result__vwq6q8V74XCA8dzFvuzU1Q));		getKey__BjB2ThDklmRLi5zxNp1MMg((&(*p_0)._keyType_1.privateKey), (&T22_));

#line 107 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
		nimZeroMem((void*)(&T23_), sizeof(tyObject_PublicKey__mVKS59bRpscItosS0oN9a4zA));		tryGet__VeMgo2Cp9aeBXhskxVN2WeAresults((&T22_), (&T23_));

#line 107 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
		nimZeroMem((void*)(&T24_), sizeof(tyObject_Option__Em5DpQtK80JNdy8nyXe6Kg));		some__YlT9b9adM2MeSxLm8RgQSNmQoptions((&T23_), (&T24_));
		genericShallowAssign((void*)(&(*Result).val), (void*)(&T24_.val), (&NTI__mVKS59bRpscItosS0oN9a4zA_));		(*Result).has = T24_.has;	}
	LA3_: ;
}

#line 425 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/arithmetics.nim"
static N_INLINE(NI, pluspercent___dgYAo7RfdUVVpvkfKDym8wsystem)(NI x, NI y) {	NI result;	result = (NI)0;
#line 426 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/arithmetics.nim"

#line 430 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/arithmetics.nim"
	result = ((NI) ((NU)((NU64)(((NU) (x))) + (NU64)(((NU) (y))))));	return result;}

#line 182 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
static N_INLINE(void, incRef__AT1eRuflKWyTTBdLjEDZbg_3system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
#line 184 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 184 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
	(*c).refcount = pluspercent___dgYAo7RfdUVVpvkfKDym8wsystem((*c).refcount, ((NI) 8));}

#line 436 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/arithmetics.nim"
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8w_2system)(NI x, NI y) {	NI result;	result = (NI)0;
#line 437 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/arithmetics.nim"

#line 441 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/arithmetics.nim"
	result = ((NI) ((NU)((NU64)(((NU) (x))) - (NU64)(((NU) (y))))));	return result;}

#line 128 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem)(void* usr) {	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* result;	NI T1_;	result = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
#line 130 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 130 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 130 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
	T1_ = (NI)0;	T1_ = minuspercent___dgYAo7RfdUVVpvkfKDym8w_2system(((NI) (ptrdiff_t) (usr)), ((NI) 16));	result = ((tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*) (T1_));	return result;}

#line 187 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/comparisons.nim"
static N_INLINE(NIM_BOOL, ltpercent___hPljn3JCDQ00ua1R07X9bxQsystem)(NI x, NI y) {	NIM_BOOL result;	result = (NIM_BOOL)0;
#line 188 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/comparisons.nim"

#line 190 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/comparisons.nim"
	result = ((NU64)(((NU) (x))) < (NU64)(((NU) (y))));	return result;}

#line 194 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
static N_INLINE(void, rtlAddZCT__AT1eRuflKWyTTBdLjEDZbg_2system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
#line 196 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 196 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
	addZCT__Y66tOYFjgwJ0k4aLz4bc0Q((&gch__IcYaEuuWivYAS86vFMTS3Q.zct), c);
}

#line 198 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
static N_INLINE(void, decRef__AT1eRuflKWyTTBdLjEDZbgsystem)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
#line 201 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 201 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
	(*c).refcount = minuspercent___dgYAo7RfdUVVpvkfKDym8w_2system((*c).refcount, ((NI) 8));
#line 202 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
	{		NIM_BOOL T3_;
#line 202 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 202 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
		T3_ = (NIM_BOOL)0;		T3_ = ltpercent___hPljn3JCDQ00ua1R07X9bxQsystem((*c).refcount, ((NI) 8));		if (!T3_) goto LA4_;

#line 203 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 203 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
		rtlAddZCT__AT1eRuflKWyTTBdLjEDZbg_2system(c);
	}
	LA4_: ;
}

#line 235 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
static N_INLINE(void, asgnRef)(void** dest, void* src) {
#line 239 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
	{		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T5_;
#line 239 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 239 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
		if (!!((src == NIM_NIL))) goto LA3_;

#line 239 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 239 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 239 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
		T5_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;		T5_ = usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem(src);
#line 239 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
		incRef__AT1eRuflKWyTTBdLjEDZbg_3system(T5_);
	}
	LA3_: ;

#line 240 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
	{		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T10_;
#line 240 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 240 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
		if (!!(((*dest) == NIM_NIL))) goto LA8_;

#line 240 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 240 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 240 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
		T10_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;		T10_ = usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem((*dest));
#line 240 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
		decRef__AT1eRuflKWyTTBdLjEDZbgsystem(T10_);
	}
	LA8_: ;

#line 241 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
	(*dest) = src;}

#line 71 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw*, init__TUPt4n8JhXOdckFHlV7m8A)(tyObject_PeerID__Se8YyoPxzDpFnTeAyeCVCw peerId, tyObject_MultiAddress__MntiKgxV52rXueBQXpXCJw* addrs, NI addrsLen_0, NimStringDesc** protocols, NI protocolsLen_0) {	tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw* result;	tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw* T1_;	result = (tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw*)0;
#line 75 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
	T1_ = (tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw*)0;	T1_ = (tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw*) newObj((&NTI__Ol4zKcKZGzrnu3Hvu9aLd4w_), sizeof(tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw));	(*T1_).Sup.m_type = (&NTI__tniXhe3Zv7xQqYX3AOw9aQw_);	(*T1_).keyType = ((tyEnum_KeyType__RX9cgRnEh9bnsWx9cuPhqOgtw) 1);	genericSeqAssign((&(*T1_).peerId.data), peerId.data, (&NTI__6H5Oh5UUvVCLiakt9aTwtUQ_));	result = T1_;
#line 57 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
	{
#line 57 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"

#line 57 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
		if (!(((NI) 0) < addrsLen_0)) goto LA4_;

#line 58 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"

#line 58 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
		asgnRef((void**) (&(*result).addrs), at___21kMoC1r79cndXPAdhT9b7Wg(addrs, addrsLen_0));	}
	LA4_: ;

#line 76 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
	{
#line 59 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"

#line 59 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
		if (!(((NI) 0) < protocolsLen_0)) goto LA8_;

#line 60 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"

#line 60 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
		asgnRef((void**) (&(*result).protocols), at___9au1Hh5AAg9cMC8zv7hfdWBg(protocols, protocolsLen_0));	}
	LA8_: ;
	return result;}

#line 227 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
static N_INLINE(void, nimGCunrefNoCycle)(void* p) {	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T1_;
#line 229 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 229 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 229 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
	T1_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;	T1_ = usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem(p);
#line 229 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
	decRef__AT1eRuflKWyTTBdLjEDZbgsystem(T1_);
}

#line 44 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
N_LIB_PRIVATE N_NIMCALL(void, shortLog__NrFxHSKgrFj3RYz5I6yAGg)(tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw* p_0, tyTuple__NevGmcPz5FN13v9cZPsfRXw* Result) {	NimStringDesc* colontmp_;	tySequence__sM4lkSb7zS6F7OVMvW9cffQ* colontmp__2;	tySequence__sM4lkSb7zS6F7OVMvW9cffQ* colontmp__4;	NimStringDesc* colontmp__6;	NimStringDesc* colontmp__7;
#line 46 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"

#line 46 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
	colontmp_ = dollar___YvhybdNIMaDdbU9cTJva0oQ_2((*p_0).peerId);
#line 47 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
	{		tySequence__pJDjdGjSf3HlAOELaHOmSA* colontmp__3;		NI iX60gensym72721086_;		tySequence__sM4lkSb7zS6F7OVMvW9cffQ* resultX60gensym72721087_;		NI T2_;
#line 99 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/collections/sequtils.nim"
		colontmp__3 = (*p_0).addrs;
#line 934 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/collections/sequtils.nim"
		iX60gensym72721086_ = ((NI) 0);
#line 935 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/collections/sequtils.nim"

#line 935 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/collections/sequtils.nim"
		T2_ = (colontmp__3 ? colontmp__3->Sup.len : 0);		if ((T2_) < ((NI) 0) || (T2_) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(T2_, ((NI) 0), ((NI) IL64(9223372036854775807))); }
#line 935 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/collections/sequtils.nim"
		resultX60gensym72721087_ = newSeq__q7W9bxIQ7BrFLngLO9cYelsA(((NI) (T2_)));		{			tyObject_MultiAddress__MntiKgxV52rXueBQXpXCJw it;			NI i;			NI L;			NI T4_;			nimZeroMem((void*)(&it), sizeof(tyObject_MultiAddress__MntiKgxV52rXueBQXpXCJw));
#line 184 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators.nim"
			i = ((NI) 0);
#line 185 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators.nim"

#line 185 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators.nim"
			T4_ = (colontmp__3 ? colontmp__3->Sup.len : 0);			L = T4_;			{
#line 186 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators.nim"
				while (1) {					NI TM__3YpbmuYVI9cMPTLRuWDLclA_9;					NI TM__3YpbmuYVI9cMPTLRuWDLclA_10;
#line 186 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators.nim"
					if (!(i < L)) goto LA6;

#line 936 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/collections/sequtils.nim"
					if ((NU)(i) >= (NU)(colontmp__3 ? colontmp__3->Sup.len : 0)){ raiseIndexError2(i,(colontmp__3 ? colontmp__3->Sup.len : 0)-1); }					it.data.buffer = colontmp__3->data[i].data.buffer;					it.data.offset = colontmp__3->data[i].data.offset;					if ((NU)(iX60gensym72721086_) >= (NU)(resultX60gensym72721087_ ? resultX60gensym72721087_->Sup.len : 0)){ raiseIndexError2(iX60gensym72721086_,(resultX60gensym72721087_ ? resultX60gensym72721087_->Sup.len : 0)-1); }
#line 47 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"

#line 47 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
					asgnRef((void**) (&resultX60gensym72721087_->data[iX60gensym72721086_]), dollar___9clTvx1x9boEUsy637oTVrWA(it));
#line 938 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/collections/sequtils.nim"
					if (nimAddInt(iX60gensym72721086_, ((NI) 1), &TM__3YpbmuYVI9cMPTLRuWDLclA_9)) { raiseOverflow(); };					iX60gensym72721086_ = (NI)(TM__3YpbmuYVI9cMPTLRuWDLclA_9);
#line 188 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators.nim"
					if (nimAddInt(i, ((NI) 1), &TM__3YpbmuYVI9cMPTLRuWDLclA_10)) { raiseOverflow(); };					i = (NI)(TM__3YpbmuYVI9cMPTLRuWDLclA_10);
#line 189 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators.nim"
					{						NI T9_;
#line 189 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators.nim"

#line 189 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators.nim"

#line 189 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators.nim"
						T9_ = (colontmp__3 ? colontmp__3->Sup.len : 0);						if (!!((T9_ == L))) goto LA10_;

#line 189 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators.nim"

#line 189 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators.nim"
						failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(((NimStringDesc*) &TM__3YpbmuYVI9cMPTLRuWDLclA_11));
					}
					LA10_: ;
				} LA6: ;
			}
		}
		genericSeqAssign((&colontmp__2), resultX60gensym72721087_, (&NTI__sM4lkSb7zS6F7OVMvW9cffQ_));	}

#line 48 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
	{		tySequence__sM4lkSb7zS6F7OVMvW9cffQ* colontmp__5;		NI iX60gensym72750019_;		tySequence__sM4lkSb7zS6F7OVMvW9cffQ* resultX60gensym72750020_;		NI T13_;
#line 99 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/collections/sequtils.nim"
		colontmp__5 = (*p_0).protocols;
#line 934 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/collections/sequtils.nim"
		iX60gensym72750019_ = ((NI) 0);
#line 935 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/collections/sequtils.nim"

#line 935 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/collections/sequtils.nim"
		T13_ = (colontmp__5 ? colontmp__5->Sup.len : 0);		if ((T13_) < ((NI) 0) || (T13_) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(T13_, ((NI) 0), ((NI) IL64(9223372036854775807))); }
#line 935 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/collections/sequtils.nim"
		resultX60gensym72750020_ = newSeq__q7W9bxIQ7BrFLngLO9cYelsA(((NI) (T13_)));		{			NimStringDesc* it_2;			NI i_2;			NI L_2;			NI T15_;			it_2 = (NimStringDesc*)0;
#line 184 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators.nim"
			i_2 = ((NI) 0);
#line 185 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators.nim"

#line 185 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators.nim"
			T15_ = (colontmp__5 ? colontmp__5->Sup.len : 0);			L_2 = T15_;			{
#line 186 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators.nim"
				while (1) {					NimStringDesc* T18_;					NI TM__3YpbmuYVI9cMPTLRuWDLclA_12;					NI TM__3YpbmuYVI9cMPTLRuWDLclA_13;
#line 186 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators.nim"
					if (!(i_2 < L_2)) goto LA17;

#line 936 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/collections/sequtils.nim"
					if ((NU)(i_2) >= (NU)(colontmp__5 ? colontmp__5->Sup.len : 0)){ raiseIndexError2(i_2,(colontmp__5 ? colontmp__5->Sup.len : 0)-1); }					it_2 = colontmp__5->data[i_2];					if ((NU)(iX60gensym72750019_) >= (NU)(resultX60gensym72750020_ ? resultX60gensym72750020_->Sup.len : 0)){ raiseIndexError2(iX60gensym72750019_,(resultX60gensym72750020_ ? resultX60gensym72750020_->Sup.len : 0)-1); }
#line 48 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
					T18_ = (NimStringDesc*)0;					T18_ = resultX60gensym72750020_->data[iX60gensym72750019_]; resultX60gensym72750020_->data[iX60gensym72750019_] = copyStringRC1(it_2);					if (T18_) nimGCunrefNoCycle(T18_);
#line 938 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/collections/sequtils.nim"
					if (nimAddInt(iX60gensym72750019_, ((NI) 1), &TM__3YpbmuYVI9cMPTLRuWDLclA_12)) { raiseOverflow(); };					iX60gensym72750019_ = (NI)(TM__3YpbmuYVI9cMPTLRuWDLclA_12);
#line 188 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators.nim"
					if (nimAddInt(i_2, ((NI) 1), &TM__3YpbmuYVI9cMPTLRuWDLclA_13)) { raiseOverflow(); };					i_2 = (NI)(TM__3YpbmuYVI9cMPTLRuWDLclA_13);
#line 189 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators.nim"
					{						NI T21_;
#line 189 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators.nim"

#line 189 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators.nim"

#line 189 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators.nim"
						T21_ = (colontmp__5 ? colontmp__5->Sup.len : 0);						if (!!((T21_ == L_2))) goto LA22_;

#line 189 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators.nim"

#line 189 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators.nim"
						failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(((NimStringDesc*) &TM__3YpbmuYVI9cMPTLRuWDLclA_11));
					}
					LA22_: ;
				} LA17: ;
			}
		}
		genericSeqAssign((&colontmp__4), resultX60gensym72750020_, (&NTI__sM4lkSb7zS6F7OVMvW9cffQ_));	}

#line 49 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
	colontmp__6 = copyString((*p_0).protoVersion);
#line 50 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
	colontmp__7 = copyString((*p_0).agentVersion);
#line 45 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
	unsureAsgnRef((void**) (&(*Result).Field0), copyString(colontmp_));	genericSeqAssign((&(*Result).Field1), colontmp__2, (&NTI__sM4lkSb7zS6F7OVMvW9cffQ_));	genericSeqAssign((&(*Result).Field2), colontmp__4, (&NTI__sM4lkSb7zS6F7OVMvW9cffQ_));	unsureAsgnRef((void**) (&(*Result).Field3), copyString(colontmp__6));	unsureAsgnRef((void**) (&(*Result).Field4), copyString(colontmp__7));}

#line 466 "/home/runner/work/nim-waku/nim-waku/vendor/nim-stew/stew/results.nim"
static N_INLINE(void, tryGet__ME7aJ9cmvtfOzZSR3TgduCAresults)(tyObject_Result__rRs2IHyL9cPDf0qPXyWd1oQ self, tyObject_PeerID__Se8YyoPxzDpFnTeAyeCVCw* Result) {
#line 467 "/home/runner/work/nim-waku/nim-waku/vendor/nim-stew/stew/results.nim"

#line 470 "/home/runner/work/nim-waku/nim-waku/vendor/nim-stew/stew/results.nim"
	{
#line 470 "/home/runner/work/nim-waku/nim-waku/vendor/nim-stew/stew/results.nim"
		if (!!(self.o)) goto LA3_;

#line 470 "/home/runner/work/nim-waku/nim-waku/vendor/nim-stew/stew/results.nim"

#line 470 "/home/runner/work/nim-waku/nim-waku/vendor/nim-stew/stew/results.nim"
		raiseResultError__3mB4FvIEM5rjrsbjkbEISw(self);
	}
	LA3_: ;
	if (!(((2 &(1U<<((NU)(self.o)&7U)))!=0))){ raiseFieldError(((NimStringDesc*) &TM__3YpbmuYVI9cMPTLRuWDLclA_7)); }	genericSeqAssign((&(*Result).data), self._o_2.v.data, (&NTI__6H5Oh5UUvVCLiakt9aTwtUQ_));}

#line 62 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw*, init__PB59cyqPenhYDSnuVdTWYAg)(tyObject_PrivateKey__GSDbMQxBVd3KO4qBUjzPKQ* key_0, tyObject_MultiAddress__MntiKgxV52rXueBQXpXCJw* addrs, NI addrsLen_0, NimStringDesc** protocols, NI protocolsLen_0) {	tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw* result;	tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw* T1_;	tyObject_Result__rRs2IHyL9cPDf0qPXyWd1oQ T2_;	result = (tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw*)0;
#line 67 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
	T1_ = (tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw*)0;	T1_ = (tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw*) newObj((&NTI__Ol4zKcKZGzrnu3Hvu9aLd4w_), sizeof(tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw));	(*T1_).Sup.m_type = (&NTI__tniXhe3Zv7xQqYX3AOw9aQw_);	(*T1_).keyType = ((tyEnum_KeyType__RX9cgRnEh9bnsWx9cuPhqOgtw) 0);
#line 67 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"

#line 67 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"

#line 67 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
	nimZeroMem((void*)(&T2_), sizeof(tyObject_Result__rRs2IHyL9cPDf0qPXyWd1oQ));	init__KPadYF1p4m3d6OsV2MZGYQ(key_0, (&T2_));

#line 67 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
	tryGet__ME7aJ9cmvtfOzZSR3TgduCAresults(T2_, (&(*T1_).peerId));
	genericAssign((void*)(&(*T1_)._keyType_1.privateKey), (void*)key_0, (&NTI__GSDbMQxBVd3KO4qBUjzPKQ_));	result = T1_;
#line 57 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
	{
#line 57 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"

#line 57 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
		if (!(((NI) 0) < addrsLen_0)) goto LA5_;

#line 58 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"

#line 58 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
		asgnRef((void**) (&(*result).addrs), at___21kMoC1r79cndXPAdhT9b7Wg(addrs, addrsLen_0));	}
	LA5_: ;

#line 69 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
	{
#line 59 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"

#line 59 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
		if (!(((NI) 0) < protocolsLen_0)) goto LA9_;

#line 60 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"

#line 60 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
		asgnRef((void**) (&(*result).protocols), at___9au1Hh5AAg9cMC8zv7hfdWBg(protocols, protocolsLen_0));	}
	LA9_: ;
	return result;}

#line 86 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw*, init__BL9b9bBxnfSdvi2cVMSvTf7Q)(tyObject_PublicKey__mVKS59bRpscItosS0oN9a4zA* key_0, tyObject_MultiAddress__MntiKgxV52rXueBQXpXCJw* addrs, NI addrsLen_0, NimStringDesc** protocols, NI protocolsLen_0) {	tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw* result;	tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw* T1_;	tyObject_Result__rRs2IHyL9cPDf0qPXyWd1oQ T2_;	result = (tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw*)0;
#line 91 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
	T1_ = (tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw*)0;	T1_ = (tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw*) newObj((&NTI__Ol4zKcKZGzrnu3Hvu9aLd4w_), sizeof(tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw));	(*T1_).Sup.m_type = (&NTI__tniXhe3Zv7xQqYX3AOw9aQw_);	(*T1_).keyType = ((tyEnum_KeyType__RX9cgRnEh9bnsWx9cuPhqOgtw) 1);
#line 92 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"

#line 92 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"

#line 92 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
	nimZeroMem((void*)(&T2_), sizeof(tyObject_Result__rRs2IHyL9cPDf0qPXyWd1oQ));	init__62yqKJpN4T5rhMXt9cfWICA(key_0, (&T2_));

#line 92 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
	tryGet__ME7aJ9cmvtfOzZSR3TgduCAresults(T2_, (&(*T1_).peerId));

#line 93 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"

#line 93 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
	some__YlT9b9adM2MeSxLm8RgQSNmQoptions(key_0, (&(*T1_)._keyType_2.key));
	result = T1_;
#line 57 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
	{
#line 57 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"

#line 57 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
		if (!(((NI) 0) < addrsLen_0)) goto LA5_;

#line 58 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"

#line 58 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
		asgnRef((void**) (&(*result).addrs), at___21kMoC1r79cndXPAdhT9b7Wg(addrs, addrsLen_0));	}
	LA5_: ;

#line 95 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
	{
#line 59 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"

#line 59 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
		if (!(((NI) 0) < protocolsLen_0)) goto LA9_;

#line 60 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"

#line 60 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
		asgnRef((void**) (&(*result).protocols), at___9au1Hh5AAg9cMC8zv7hfdWBg(protocols, protocolsLen_0));	}
	LA9_: ;
	return result;}

#line 78 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw*, init__05wj2M9aqChEsORKqJNujYA)(NimStringDesc* peerId, tyObject_MultiAddress__MntiKgxV52rXueBQXpXCJw* addrs, NI addrsLen_0, NimStringDesc** protocols, NI protocolsLen_0) {	tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw* result;	tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw* T1_;	tyObject_Result__rRs2IHyL9cPDf0qPXyWd1oQ T2_;	result = (tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw*)0;
#line 83 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
	T1_ = (tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw*)0;	T1_ = (tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw*) newObj((&NTI__Ol4zKcKZGzrnu3Hvu9aLd4w_), sizeof(tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw));	(*T1_).Sup.m_type = (&NTI__tniXhe3Zv7xQqYX3AOw9aQw_);	(*T1_).keyType = ((tyEnum_KeyType__RX9cgRnEh9bnsWx9cuPhqOgtw) 1);
#line 83 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"

#line 83 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"

#line 83 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
	nimZeroMem((void*)(&T2_), sizeof(tyObject_Result__rRs2IHyL9cPDf0qPXyWd1oQ));	init__9cVMRbKcykqNIIPeD9aOhmYA(peerId, (&T2_));

#line 83 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
	tryGet__ME7aJ9cmvtfOzZSR3TgduCAresults(T2_, (&(*T1_).peerId));
	result = T1_;
#line 57 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
	{
#line 57 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"

#line 57 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
		if (!(((NI) 0) < addrsLen_0)) goto LA5_;

#line 58 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"

#line 58 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
		asgnRef((void**) (&(*result).addrs), at___21kMoC1r79cndXPAdhT9b7Wg(addrs, addrsLen_0));	}
	LA5_: ;

#line 84 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
	{
#line 59 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"

#line 59 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
		if (!(((NI) 0) < protocolsLen_0)) goto LA9_;

#line 60 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"

#line 60 "/home/runner/work/nim-waku/nim-waku/vendor/nim-libp2p/libp2p/peerinfo.nim"
		asgnRef((void**) (&(*result).protocols), at___9au1Hh5AAg9cMC8zv7hfdWBg(protocols, protocolsLen_0));	}
	LA9_: ;
	return result;}
N_LIB_PRIVATE N_NIMCALL(void, libp2p_peerinfoDatInit000)(void) {

#line 999999 "generated_not_to_break_here"
static TNimNode* TM__3YpbmuYVI9cMPTLRuWDLclA_2_7[7];
static TNimNode* TM__3YpbmuYVI9cMPTLRuWDLclA_3_2[2];
NI TM__3YpbmuYVI9cMPTLRuWDLclA_5;
static char* NIM_CONST TM__3YpbmuYVI9cMPTLRuWDLclA_4[2] = {
"HasPrivate", 
"HasPublic"};
static TNimNode TM__3YpbmuYVI9cMPTLRuWDLclA_0[13];NTI__tniXhe3Zv7xQqYX3AOw9aQw_.size = sizeof(tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw);
NTI__tniXhe3Zv7xQqYX3AOw9aQw_.kind = 17;
NTI__tniXhe3Zv7xQqYX3AOw9aQw_.base = (&NTI__ytyiCJqK439aF9cIibuRVpAg_);
NTI__tniXhe3Zv7xQqYX3AOw9aQw_.name = "PeerInfo:ObjectType";
NTI__tniXhe3Zv7xQqYX3AOw9aQw_.nextType = nimTypeRoot; nimTypeRoot=&NTI__tniXhe3Zv7xQqYX3AOw9aQw_;
TM__3YpbmuYVI9cMPTLRuWDLclA_2_7[0] = &TM__3YpbmuYVI9cMPTLRuWDLclA_0[1];
TM__3YpbmuYVI9cMPTLRuWDLclA_0[1].kind = 1;
TM__3YpbmuYVI9cMPTLRuWDLclA_0[1].offset = offsetof(tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw, peerId);
TM__3YpbmuYVI9cMPTLRuWDLclA_0[1].typ = (&NTI__Se8YyoPxzDpFnTeAyeCVCw_);
TM__3YpbmuYVI9cMPTLRuWDLclA_0[1].name = "peerId";
TM__3YpbmuYVI9cMPTLRuWDLclA_2_7[1] = &TM__3YpbmuYVI9cMPTLRuWDLclA_0[2];
NTI__pJDjdGjSf3HlAOELaHOmSA_.size = sizeof(tySequence__pJDjdGjSf3HlAOELaHOmSA*);
NTI__pJDjdGjSf3HlAOELaHOmSA_.kind = 24;
NTI__pJDjdGjSf3HlAOELaHOmSA_.base = (&NTI__MntiKgxV52rXueBQXpXCJw_);
NTI__pJDjdGjSf3HlAOELaHOmSA_.flags = 2;
NTI__pJDjdGjSf3HlAOELaHOmSA_.name = "seq[MultiAddress]";
NTI__pJDjdGjSf3HlAOELaHOmSA_.nextType = nimTypeRoot; nimTypeRoot=&NTI__pJDjdGjSf3HlAOELaHOmSA_;
NTI__pJDjdGjSf3HlAOELaHOmSA_.marker = Marker_tySequence__pJDjdGjSf3HlAOELaHOmSA;
TM__3YpbmuYVI9cMPTLRuWDLclA_0[2].kind = 1;
TM__3YpbmuYVI9cMPTLRuWDLclA_0[2].offset = offsetof(tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw, addrs);
TM__3YpbmuYVI9cMPTLRuWDLclA_0[2].typ = (&NTI__pJDjdGjSf3HlAOELaHOmSA_);
TM__3YpbmuYVI9cMPTLRuWDLclA_0[2].name = "addrs";
TM__3YpbmuYVI9cMPTLRuWDLclA_2_7[2] = &TM__3YpbmuYVI9cMPTLRuWDLclA_0[3];
TM__3YpbmuYVI9cMPTLRuWDLclA_0[3].kind = 1;
TM__3YpbmuYVI9cMPTLRuWDLclA_0[3].offset = offsetof(tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw, protocols);
TM__3YpbmuYVI9cMPTLRuWDLclA_0[3].typ = (&NTI__sM4lkSb7zS6F7OVMvW9cffQ_);
TM__3YpbmuYVI9cMPTLRuWDLclA_0[3].name = "protocols";
TM__3YpbmuYVI9cMPTLRuWDLclA_2_7[3] = &TM__3YpbmuYVI9cMPTLRuWDLclA_0[4];
TM__3YpbmuYVI9cMPTLRuWDLclA_0[4].kind = 1;
TM__3YpbmuYVI9cMPTLRuWDLclA_0[4].offset = offsetof(tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw, protoVersion);
TM__3YpbmuYVI9cMPTLRuWDLclA_0[4].typ = (&NTI__77mFvmsOLKik79ci2hXkHEg_);
TM__3YpbmuYVI9cMPTLRuWDLclA_0[4].name = "protoVersion";
TM__3YpbmuYVI9cMPTLRuWDLclA_2_7[4] = &TM__3YpbmuYVI9cMPTLRuWDLclA_0[5];
TM__3YpbmuYVI9cMPTLRuWDLclA_0[5].kind = 1;
TM__3YpbmuYVI9cMPTLRuWDLclA_0[5].offset = offsetof(tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw, agentVersion);
TM__3YpbmuYVI9cMPTLRuWDLclA_0[5].typ = (&NTI__77mFvmsOLKik79ci2hXkHEg_);
TM__3YpbmuYVI9cMPTLRuWDLclA_0[5].name = "agentVersion";
TM__3YpbmuYVI9cMPTLRuWDLclA_2_7[5] = &TM__3YpbmuYVI9cMPTLRuWDLclA_0[6];
TM__3YpbmuYVI9cMPTLRuWDLclA_0[6].kind = 1;
TM__3YpbmuYVI9cMPTLRuWDLclA_0[6].offset = offsetof(tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw, secure);
TM__3YpbmuYVI9cMPTLRuWDLclA_0[6].typ = (&NTI__77mFvmsOLKik79ci2hXkHEg_);
TM__3YpbmuYVI9cMPTLRuWDLclA_0[6].name = "secure";
TM__3YpbmuYVI9cMPTLRuWDLclA_2_7[6] = &TM__3YpbmuYVI9cMPTLRuWDLclA_0[7];
NTI__RX9cgRnEh9bnsWx9cuPhqOgtw_.size = sizeof(tyEnum_KeyType__RX9cgRnEh9bnsWx9cuPhqOgtw);
NTI__RX9cgRnEh9bnsWx9cuPhqOgtw_.kind = 14;
NTI__RX9cgRnEh9bnsWx9cuPhqOgtw_.base = 0;
NTI__RX9cgRnEh9bnsWx9cuPhqOgtw_.flags = 3;
NTI__RX9cgRnEh9bnsWx9cuPhqOgtw_.name = "KeyType";
NTI__RX9cgRnEh9bnsWx9cuPhqOgtw_.nextType = nimTypeRoot; nimTypeRoot=&NTI__RX9cgRnEh9bnsWx9cuPhqOgtw_;
for (TM__3YpbmuYVI9cMPTLRuWDLclA_5 = 0; TM__3YpbmuYVI9cMPTLRuWDLclA_5 < 2; TM__3YpbmuYVI9cMPTLRuWDLclA_5++) {
TM__3YpbmuYVI9cMPTLRuWDLclA_0[TM__3YpbmuYVI9cMPTLRuWDLclA_5+8].kind = 1;
TM__3YpbmuYVI9cMPTLRuWDLclA_0[TM__3YpbmuYVI9cMPTLRuWDLclA_5+8].offset = TM__3YpbmuYVI9cMPTLRuWDLclA_5;
TM__3YpbmuYVI9cMPTLRuWDLclA_0[TM__3YpbmuYVI9cMPTLRuWDLclA_5+8].name = TM__3YpbmuYVI9cMPTLRuWDLclA_4[TM__3YpbmuYVI9cMPTLRuWDLclA_5];
TM__3YpbmuYVI9cMPTLRuWDLclA_3_2[TM__3YpbmuYVI9cMPTLRuWDLclA_5] = &TM__3YpbmuYVI9cMPTLRuWDLclA_0[TM__3YpbmuYVI9cMPTLRuWDLclA_5+8];
}
TM__3YpbmuYVI9cMPTLRuWDLclA_0[10].len = 2; TM__3YpbmuYVI9cMPTLRuWDLclA_0[10].kind = 2; TM__3YpbmuYVI9cMPTLRuWDLclA_0[10].sons = &TM__3YpbmuYVI9cMPTLRuWDLclA_3_2[0];
NTI__RX9cgRnEh9bnsWx9cuPhqOgtw_.node = &TM__3YpbmuYVI9cMPTLRuWDLclA_0[10];
TM__3YpbmuYVI9cMPTLRuWDLclA_0[7].kind = 3;
TM__3YpbmuYVI9cMPTLRuWDLclA_0[7].offset = offsetof(tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw, keyType);
TM__3YpbmuYVI9cMPTLRuWDLclA_0[7].typ = (&NTI__RX9cgRnEh9bnsWx9cuPhqOgtw_);
TM__3YpbmuYVI9cMPTLRuWDLclA_0[7].name = "keyType";
TM__3YpbmuYVI9cMPTLRuWDLclA_0[7].sons = &NimDT___tniXhe3Zv7xQqYX3AOw9aQw_keyType[0];
TM__3YpbmuYVI9cMPTLRuWDLclA_0[7].len = 2;
TM__3YpbmuYVI9cMPTLRuWDLclA_0[11].kind = 1;
TM__3YpbmuYVI9cMPTLRuWDLclA_0[11].offset = offsetof(tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw, _keyType_1.privateKey);
TM__3YpbmuYVI9cMPTLRuWDLclA_0[11].typ = (&NTI__GSDbMQxBVd3KO4qBUjzPKQ_);
TM__3YpbmuYVI9cMPTLRuWDLclA_0[11].name = "privateKey";
NimDT___tniXhe3Zv7xQqYX3AOw9aQw_keyType[0] = &TM__3YpbmuYVI9cMPTLRuWDLclA_0[11];
TM__3YpbmuYVI9cMPTLRuWDLclA_0[12].kind = 1;
TM__3YpbmuYVI9cMPTLRuWDLclA_0[12].offset = offsetof(tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw, _keyType_2.key);
TM__3YpbmuYVI9cMPTLRuWDLclA_0[12].typ = (&NTI__Em5DpQtK80JNdy8nyXe6Kg_);
TM__3YpbmuYVI9cMPTLRuWDLclA_0[12].name = "key";
NimDT___tniXhe3Zv7xQqYX3AOw9aQw_keyType[1] = &TM__3YpbmuYVI9cMPTLRuWDLclA_0[12];
TM__3YpbmuYVI9cMPTLRuWDLclA_0[0].len = 7; TM__3YpbmuYVI9cMPTLRuWDLclA_0[0].kind = 2; TM__3YpbmuYVI9cMPTLRuWDLclA_0[0].sons = &TM__3YpbmuYVI9cMPTLRuWDLclA_2_7[0];
NTI__tniXhe3Zv7xQqYX3AOw9aQw_.node = &TM__3YpbmuYVI9cMPTLRuWDLclA_0[0];
NTI__Ol4zKcKZGzrnu3Hvu9aLd4w_.size = sizeof(tyObject_PeerInfocolonObjectType___tniXhe3Zv7xQqYX3AOw9aQw*);
NTI__Ol4zKcKZGzrnu3Hvu9aLd4w_.kind = 22;
NTI__Ol4zKcKZGzrnu3Hvu9aLd4w_.base = (&NTI__tniXhe3Zv7xQqYX3AOw9aQw_);
NTI__Ol4zKcKZGzrnu3Hvu9aLd4w_.name = "PeerInfo";
NTI__Ol4zKcKZGzrnu3Hvu9aLd4w_.nextType = nimTypeRoot; nimTypeRoot=&NTI__Ol4zKcKZGzrnu3Hvu9aLd4w_;
NTI__Ol4zKcKZGzrnu3Hvu9aLd4w_.marker = Marker_tyRef__Ol4zKcKZGzrnu3Hvu9aLd4w;
}

