/* Generated by Nim Compiler v1.2.6 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -pthread -I/home/runner/work/nim-waku/nim-waku/vendor/nim-libbacktrace -I/home/runner/work/nim-waku/nim-waku/vendor/nim-libbacktrace/install/usr/include -I/home/runner/work/nim-waku/nim-waku/vendor/nim-secp256k1/secp256k1_wrapper -I/home/runner/work/nim-waku/nim-waku/vendor/nim-secp256k1/secp256k1_wrapper/secp256k1 -I/home/runner/work/nim-waku/nim-waku/vendor/nim-secp256k1/secp256k1_wrapper/secp256k1/src -DHAVE_CONFIG_H -DHAVE_BUILTIN_EXPECT -I/home/runner/work/nim-waku/nim-waku/vendor/nim-bearssl/bearssl/csources/src -I/home/runner/work/nim-waku/nim-waku/vendor/nim-bearssl/bearssl/csources/inc -I/home/runner/work/nim-waku/nim-waku/vendor/nim-bearssl/bearssl/csources/tools -DBR_USE_UNIX_TIME=1 -DBR_USE_URANDOM=1 -DBR_LE_UNALIGNED=1 -DBR_64=1  -DBR_amd64=1 -DBR_INT128=1 -I/home/runner/work/nim-waku/nim-waku/vendor/nim-bearssl/bearssl/certs -I/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/vendor/miniupnp/miniupnpc -I/home/runner/work/nim-waku/nim-waku/vendor/nim-nat-traversal/vendor/libnatpmp-upstream -DENABLE_STRNATPMPERR -march=native -g3 -Og -O3 -fno-strict-aliasing -fno-ident  -I/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib -I/home/runner/work/nim-waku/nim-waku/waku/v2/node -o nimcache/release/wakunode2/@m..@s..@s..@svendor@snim-json-rpc@sjson_rpc@sjsonmarshal.nim.c.o nimcache/release/wakunode2/@m..@s..@s..@svendor@snim-json-rpc@sjson_rpc@sjsonmarshal.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <sys/types.h>
                          #include <pthread.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg;
typedef struct tySequence__MlAD6nAPq9bHKla9cWiIZP0g tySequence__MlAD6nAPq9bHKla9cWiIZP0g;
typedef struct tySequence__oLpBKXzW3hF9aCVMo5EymfQ tySequence__oLpBKXzW3hF9aCVMo5EymfQ;
typedef struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw;
typedef struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack__7fytPA5bBsob6See21YMRA tyObject_GcStack__7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyTuple__ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw;
typedef struct tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg;
typedef struct tyObject_WakuRelayMessage__jLO9cyS189bZS4ql8DPZJevw tyObject_WakuRelayMessage__jLO9cyS189bZS4ql8DPZJevw;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ tySequence__6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct tyObject_Option__rVkI1RILdi0akg69brivmzg tyObject_Option__rVkI1RILdi0akg69brivmzg;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__xNHF59br19a2ddRDpm49b8z3A tySequence__xNHF59br19a2ddRDpm49b8z3A;
typedef struct tyObject_ContentFilter__zmS3UuJydVs2xUezA1n9akA tyObject_ContentFilter__zmS3UuJydVs2xUezA1n9akA;
typedef struct tySequence__9bAGqSvkAaFL9bWjsEPslrFA tySequence__9bAGqSvkAaFL9bWjsEPslrFA;
typedef struct tyObject_StorePagingOptions__gOYu9bLiJN6GFHM9bfNsoUBg tyObject_StorePagingOptions__gOYu9bLiJN6GFHM9bfNsoUBg;
typedef struct tyObject_Option__QZVOEjCvFvdMOcWYv3UMWg tyObject_Option__QZVOEjCvFvdMOcWYv3UMWg;
typedef struct tyObject_Index__lOZ7xaSDQuG6u4WFzCveFQ tyObject_Index__lOZ7xaSDQuG6u4WFzCveFQ;
typedef struct tyObject_MDigest__law9ct65KplMYBvtmjCQxbw tyObject_MDigest__law9ct65KplMYBvtmjCQxbw;
typedef struct tyTuple__awOivLjlO76sGdHY7nQUjQ tyTuple__awOivLjlO76sGdHY7nQUjQ;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
struct TGenericSeq {NI len;
NI reserved;
};
struct NimStringDesc {  TGenericSeq Sup;NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg;
struct tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg {tySequence__MlAD6nAPq9bHKla9cWiIZP0g* data;
NI counter;
NI first;
NI last;
};
struct tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q {tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg kind;
union{
struct {NimStringDesc* str;
} _kind_1;
struct {NI64 num;
} _kind_2;
struct {NF fnum;
} _kind_3;
struct {NIM_BOOL bval;
} _kind_4;
struct {tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg fields;
} _kind_6;
struct {tySequence__oLpBKXzW3hF9aCVMo5EymfQ* elems;
} _kind_7;
};
};
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {NI size;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
NCSTRING name;
TNimType* nextType;
NI instances;
NI sizes;
};
struct RootObj {TNimType* m_type;};
struct Exception {  RootObj Sup;Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence__uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA {  Exception Sup;};
struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw {  tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA Sup;};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g {NI refcount;
TNimType* typ;
};
struct tyObject_GcStack__7fytPA5bBsob6See21YMRA {void* bottom;
};
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w {NI len;
NI cap;
tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ* tyArray__SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* tyArray__N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray__N1u1nqOgmuJN9cSZrnMHgOQ tyArray__B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw* tyArray__lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA {tyArray__lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* tyArray__0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw {tyArray__0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyArray__LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg {NI len;
tyArray__LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg {NI minLargeObj;
NI maxLargeObj;
tyArray__SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray__B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
NI allocCounter;
NI deallocCounter;
};
struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg {NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ {NI counter;
NI max;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg** data;
};
typedef long tyArray__xDUyu9aScDpt0JZLU6q9aEZQ[5];
struct tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw {tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg* head;
tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg* tail;
pthread_mutex_t lock;
};
struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ {tyObject_GcStack__7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w additionalRoots;
tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw toDispose;
NI gcThreadId;
};
typedef NU8 tyArray__vEOa9c5qaE9ajWxR5R4zwfQg[32];
struct tyObject_Option__rVkI1RILdi0akg69brivmzg {NU32 val;
NIM_BOOL has;
};
struct tyObject_WakuRelayMessage__jLO9cyS189bZS4ql8DPZJevw {tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* payload;
tyObject_Option__rVkI1RILdi0akg69brivmzg contentTopic;
};
struct tyObject_ContentFilter__zmS3UuJydVs2xUezA1n9akA {tySequence__9bAGqSvkAaFL9bWjsEPslrFA* topics;
};
struct tyObject_MDigest__law9ct65KplMYBvtmjCQxbw {tyArray__vEOa9c5qaE9ajWxR5R4zwfQg data;
};
struct tyObject_Index__lOZ7xaSDQuG6u4WFzCveFQ {tyObject_MDigest__law9ct65KplMYBvtmjCQxbw digest;
NF receivedTime;
};
struct tyObject_Option__QZVOEjCvFvdMOcWYv3UMWg {tyObject_Index__lOZ7xaSDQuG6u4WFzCveFQ val;
NIM_BOOL has;
};
struct tyObject_StorePagingOptions__gOYu9bLiJN6GFHM9bfNsoUBg {NU64 pageSize;
tyObject_Option__QZVOEjCvFvdMOcWYv3UMWg cursor;
NIM_BOOL forward;
};
struct tyTuple__awOivLjlO76sGdHY7nQUjQ {
NI Field0;
NI Field1;
NimStringDesc* Field2;
tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* Field3;
};
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {  TGenericSeq Sup;  NimStringDesc* data[SEQ_DECL_SIZE];};struct tySequence__xNHF59br19a2ddRDpm49b8z3A {  TGenericSeq Sup;  tyObject_ContentFilter__zmS3UuJydVs2xUezA1n9akA data[SEQ_DECL_SIZE];};struct tySequence__9bAGqSvkAaFL9bWjsEPslrFA {  TGenericSeq Sup;  NU32 data[SEQ_DECL_SIZE];};struct tySequence__MlAD6nAPq9bHKla9cWiIZP0g {  TGenericSeq Sup;  tyTuple__awOivLjlO76sGdHY7nQUjQ data[SEQ_DECL_SIZE];};struct tySequence__oLpBKXzW3hF9aCVMo5EymfQ {  TGenericSeq Sup;  tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* data[SEQ_DECL_SIZE];};struct tySequence__uB9b75OUPRENsBAu4AnoePA {  TGenericSeq Sup;  tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];};struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ {  TGenericSeq Sup;  NU8 data[SEQ_DECL_SIZE];};static N_INLINE(void, fromJson__B3MpHSypnqLEU8fkNuDmSAconversions)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0, NimStringDesc* argName, NU64* result);
N_LIB_PRIVATE N_NIMCALL(NI64, getBiggestInt__PqGEbz7TZWJYF9aMChcCbPw)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0, NI64 default_0);
N_LIB_PRIVATE N_NIMCALL(void, expect__vt4akIm2aAJMf4kfqmrlbw)(tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg actual, tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg expected, NimStringDesc* argName);
N_LIB_PRIVATE N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem__i80o3k0SgEI5gTRCzYdyWAsystem)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, reprEnum)(NI e_0, TNimType* typ);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef__AT1eRuflKWyTTBdLjEDZbg_3system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, pluspercent___dgYAo7RfdUVVpvkfKDym8wsystem)(NI x, NI y);
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem)(void* usr);
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8w_2system)(NI x, NI y);
static N_INLINE(void, decRef__AT1eRuflKWyTTBdLjEDZbgsystem)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NIM_BOOL, ltpercent___hPljn3JCDQ00ua1R07X9bxQsystem)(NI x, NI y);
static N_INLINE(void, rtlAddZCT__AT1eRuflKWyTTBdLjEDZbg_2system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__Y66tOYFjgwJ0k4aLz4bc0Q)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
N_LIB_PRIVATE N_NIMCALL(NI, nsuParseHexInt)(NimStringDesc* s_0);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getStr__QeJX1ptVmfOrOg9cwOVpcAA)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0, NimStringDesc* default_0);
N_LIB_PRIVATE N_NOINLINE(void, chckNil)(void* p);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size);
static N_INLINE(void, fromJson__oq3MeWmWhDgAvP66RcNfkwconversions)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0, NimStringDesc* argName, NU8* result);
N_LIB_PRIVATE N_NIMCALL(void, bytesFromJson__3U9cUaaE8g9aZKvP09bWzgcXw)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0, NimStringDesc* argName, NU8* result, NI resultLen_0);
N_LIB_PRIVATE N_NIMCALL(void, fromJson__X9cjMnjMEmWu5c9a8SUD1Jxg)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0, NimStringDesc* argName, NimStringDesc** result);
N_LIB_PRIVATE N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_LIB_PRIVATE N_NIMCALL(void, fromJson__2gjcjrVVc6rLiin5CkarRg)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0, NimStringDesc* argName, tyObject_WakuRelayMessage__jLO9cyS189bZS4ql8DPZJevw* result);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__zrDHfVBiQiPv9bNJ29c1ZINg_2)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* node, NimStringDesc* key_0);
N_LIB_PRIVATE N_NIMCALL(void, fromJson__lZoyfH55Wzpb8bL1TaXbyw)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0, NimStringDesc* argName, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ** result);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*, newJNull__nXwnFPu9beTnGPwglrr7ztA_3)(void);
static N_INLINE(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*, X5BX5D___277k8m8OstpfbY4dHQex6wjson)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* node, NimStringDesc* name_0);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A)(NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q**, X5BX5D___l9atGRY9bA25fn4p5uueZfUQ)(tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg* t, NimStringDesc* key_0);
N_LIB_PRIVATE N_NOINLINE(void, raiseFieldError)(NimStringDesc* f);
N_LIB_PRIVATE N_NIMCALL(void, fromJson__NOuIM3H7iyiPvYQLWHFxPw)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0, NimStringDesc* argName, tyObject_Option__rVkI1RILdi0akg69brivmzg* result);
N_LIB_PRIVATE N_NIMCALL(void, fromJson__5DLVKi5Cs89aEKkcHkq1HGw)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0, NimStringDesc* argName, NU32* result);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Option__rVkI1RILdi0akg69brivmzg, some__3uXaIMXFnDdgZxwHKhW7igoptions)(NU32 val_0);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*, newJInt__kuRQ9bONMtpC9bToqIhX9cETA_2)(NI64 n_0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(void, fromJson__3LJCfR9aw1ZjNE8C0pCrinQ)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0, NimStringDesc* argName, tySequence__sM4lkSb7zS6F7OVMvW9cffQ** result);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ*, newSeq__q7W9bxIQ7BrFLngLO9cYelsA)(NI len_0);
N_LIB_PRIVATE N_NIMCALL(NI, len__Og3BmQpaL5V6gYg5JnWK3Q)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0);
static N_INLINE(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*, X5BX5D___iGpexJJNbY5V0TEMs9aHjwQjson)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* node, NI index);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, fromJson__4qb89coqZq3XBvazA173pGA)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0, NimStringDesc* argName, tySequence__xNHF59br19a2ddRDpm49b8z3A** result);
N_LIB_PRIVATE N_NIMCALL(tySequence__xNHF59br19a2ddRDpm49b8z3A*, newSeq__ulssHs3qvX9a2WFQd3HH1aA)(NI len_0);
N_LIB_PRIVATE N_NIMCALL(void, fromJson__4JjKJcmNTX9btU71Xok2MzQ)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0, NimStringDesc* argName, tyObject_ContentFilter__zmS3UuJydVs2xUezA1n9akA* result);
N_LIB_PRIVATE N_NIMCALL(void, fromJson__Rqs8fR2oyGbE9bx2hG7ALpg)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0, NimStringDesc* argName, tySequence__9bAGqSvkAaFL9bWjsEPslrFA** result);
N_LIB_PRIVATE N_NIMCALL(tySequence__9bAGqSvkAaFL9bWjsEPslrFA*, newSeq__4g9cmvwewbrdtpBMV5P3thg)(NI len_0);
N_LIB_PRIVATE N_NIMCALL(void, fromJson__IsUEA2R2B4wBR5DoBXoRUg)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0, NimStringDesc* argName, tyObject_StorePagingOptions__gOYu9bLiJN6GFHM9bfNsoUBg* result);
N_LIB_PRIVATE N_NIMCALL(void, fromJson__iWHxnLNKA767Xc5zx9b7o0w)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0, NimStringDesc* argName, NU64* result);
N_LIB_PRIVATE N_NIMCALL(NI, getInt__1efdasyP68nDQg4BeLHzGQ)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0, NI default_0);
N_LIB_PRIVATE N_NIMCALL(void, fromJson__pGdfGL0puujyixjN9cz0rlw)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0, NimStringDesc* argName, tyObject_Option__QZVOEjCvFvdMOcWYv3UMWg* result);
N_LIB_PRIVATE N_NIMCALL(void, fromJson__89aLJpLBkv36ftYPufTBHwg)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0, NimStringDesc* argName, tyObject_Index__lOZ7xaSDQuG6u4WFzCveFQ* result);
N_LIB_PRIVATE N_NIMCALL(void, fromJson__aXqydplDjMIZGfO9b47bWng)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0, NimStringDesc* argName, tyObject_MDigest__law9ct65KplMYBvtmjCQxbw* result);
N_LIB_PRIVATE N_NIMCALL(void, fromJson__M4IEVBcoOoODCVrboQ9cZfg)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0, NimStringDesc* argName, NF* result);
N_LIB_PRIVATE N_NIMCALL(NF, getFloat__llZz76LOmvR0qTBY4kY9cFg)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0, NF default_0);
static N_INLINE(tyObject_Option__QZVOEjCvFvdMOcWYv3UMWg, some__cDTM0qv3zc9ckbyfeCmQDngoptions)(tyObject_Index__lOZ7xaSDQuG6u4WFzCveFQ* val_0);
N_LIB_PRIVATE N_NIMCALL(void, fromJson__IUlrvPKZ7DCHL75kpCVUmA)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0, NimStringDesc* argName, NIM_BOOL* result);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, getBool__WLYG2J5rvQY8w8vO47RYig)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0, NIM_BOOL default_0);
extern TNimType NTI__Ie1m0dv1ZHg72IgPRr1cDw_;
extern TNimType NTI__yoNlBGx0D2tRizIdhQuENw_;
STRING_LITERAL(TM__BnC9avUv8ny2yMv6NSfv9cQw_2, "Parameter [", 11);
STRING_LITERAL(TM__BnC9avUv8ny2yMv6NSfv9cQw_3, "] expected ", 11);
extern TNimType NTI__RUngo7nCHe6O8aBGIcrhtg_;
STRING_LITERAL(TM__BnC9avUv8ny2yMv6NSfv9cQw_4, " but got ", 9);
STRING_LITERAL(TM__BnC9avUv8ny2yMv6NSfv9cQw_5, "payload", 7);
STRING_LITERAL(TM__BnC9avUv8ny2yMv6NSfv9cQw_6, "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/"
"vendor/Nim/lib/pure/json.nim(464, 9) `not isNil(node)` ", 118);
STRING_LITERAL(TM__BnC9avUv8ny2yMv6NSfv9cQw_7, "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/"
"vendor/Nim/lib/pure/json.nim(465, 9) `node.kind == JObject` ", 123);
STRING_LITERAL(TM__BnC9avUv8ny2yMv6NSfv9cQw_8, "\'fields\' is not accessible using discriminant \'kind\' of type \'J"
"sonNodeObj\'", 74);
STRING_LITERAL(TM__BnC9avUv8ny2yMv6NSfv9cQw_9, "contentTopic", 12);
STRING_LITERAL(TM__BnC9avUv8ny2yMv6NSfv9cQw_10, "JSON-RPC input is an unexpected negative value", 46);
STRING_LITERAL(TM__BnC9avUv8ny2yMv6NSfv9cQw_11, "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/"
"vendor/Nim/lib/pure/json.nim(474, 9) `not isNil(node)` ", 118);
STRING_LITERAL(TM__BnC9avUv8ny2yMv6NSfv9cQw_12, "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/"
"vendor/Nim/lib/pure/json.nim(475, 9) `node.kind == JArray` ", 122);
STRING_LITERAL(TM__BnC9avUv8ny2yMv6NSfv9cQw_13, "\'elems\' is not accessible using discriminant \'kind\' of type \'Js"
"onNodeObj\'", 73);
STRING_LITERAL(TM__BnC9avUv8ny2yMv6NSfv9cQw_15, "topics", 6);
STRING_LITERAL(TM__BnC9avUv8ny2yMv6NSfv9cQw_18, "pageSize", 8);
STRING_LITERAL(TM__BnC9avUv8ny2yMv6NSfv9cQw_19, "cursor", 6);
STRING_LITERAL(TM__BnC9avUv8ny2yMv6NSfv9cQw_20, "digest", 6);
STRING_LITERAL(TM__BnC9avUv8ny2yMv6NSfv9cQw_21, "receivedTime", 12);
STRING_LITERAL(TM__BnC9avUv8ny2yMv6NSfv9cQw_22, "forward", 7);
extern NIM_THREADVAR tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ gch__IcYaEuuWivYAS86vFMTS3Q;

#line 11 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {	void* T1_;
#line 13 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"

#line 13 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memcpy(dest, source, ((size_t) (size)));}

#line 2112 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system.nim"
static N_INLINE(void, copyMem__i80o3k0SgEI5gTRCzYdyWAsystem)(void* dest, void* source, NI size) {
#line 2113 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system.nim"

#line 2113 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system.nim"
	nimCopyMem(dest, source, size);
}

#line 217 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/sysstr.nim"
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
#line 218 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/sysstr.nim"
	{
#line 218 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/sysstr.nim"

#line 218 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/sysstr.nim"
		if (!!((src == NIM_NIL))) goto LA3_;

#line 219 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/sysstr.nim"

#line 219 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/sysstr.nim"

#line 219 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/sysstr.nim"
		copyMem__i80o3k0SgEI5gTRCzYdyWAsystem(((void*) ((&(*dest).data[(*dest).Sup.len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));

#line 220 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/sysstr.nim"
		(*dest).Sup.len += (*src).Sup.len;	}
	LA3_: ;
}

#line 425 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/arithmetics.nim"
static N_INLINE(NI, pluspercent___dgYAo7RfdUVVpvkfKDym8wsystem)(NI x, NI y) {	NI result;	result = (NI)0;
#line 426 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/arithmetics.nim"

#line 430 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/arithmetics.nim"
	result = ((NI) ((NU)((NU64)(((NU) (x))) + (NU64)(((NU) (y))))));	return result;}

#line 182 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
static N_INLINE(void, incRef__AT1eRuflKWyTTBdLjEDZbg_3system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
#line 184 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 184 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
	(*c).refcount = pluspercent___dgYAo7RfdUVVpvkfKDym8wsystem((*c).refcount, ((NI) 8));}

#line 436 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/arithmetics.nim"
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8w_2system)(NI x, NI y) {	NI result;	result = (NI)0;
#line 437 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/arithmetics.nim"

#line 441 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/arithmetics.nim"
	result = ((NI) ((NU)((NU64)(((NU) (x))) - (NU64)(((NU) (y))))));	return result;}

#line 128 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem)(void* usr) {	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* result;	NI T1_;	result = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
#line 130 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 130 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 130 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
	T1_ = (NI)0;	T1_ = minuspercent___dgYAo7RfdUVVpvkfKDym8w_2system(((NI) (ptrdiff_t) (usr)), ((NI) 16));	result = ((tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*) (T1_));	return result;}

#line 187 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/comparisons.nim"
static N_INLINE(NIM_BOOL, ltpercent___hPljn3JCDQ00ua1R07X9bxQsystem)(NI x, NI y) {	NIM_BOOL result;	result = (NIM_BOOL)0;
#line 188 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/comparisons.nim"

#line 190 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/comparisons.nim"
	result = ((NU64)(((NU) (x))) < (NU64)(((NU) (y))));	return result;}

#line 194 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
static N_INLINE(void, rtlAddZCT__AT1eRuflKWyTTBdLjEDZbg_2system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
#line 196 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 196 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
	addZCT__Y66tOYFjgwJ0k4aLz4bc0Q((&gch__IcYaEuuWivYAS86vFMTS3Q.zct), c);
}

#line 198 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
static N_INLINE(void, decRef__AT1eRuflKWyTTBdLjEDZbgsystem)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
#line 201 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 201 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
	(*c).refcount = minuspercent___dgYAo7RfdUVVpvkfKDym8w_2system((*c).refcount, ((NI) 8));
#line 202 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
	{		NIM_BOOL T3_;
#line 202 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 202 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
		T3_ = (NIM_BOOL)0;		T3_ = ltpercent___hPljn3JCDQ00ua1R07X9bxQsystem((*c).refcount, ((NI) 8));		if (!T3_) goto LA4_;

#line 203 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 203 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
		rtlAddZCT__AT1eRuflKWyTTBdLjEDZbg_2system(c);
	}
	LA4_: ;
}

#line 235 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
static N_INLINE(void, asgnRef)(void** dest, void* src) {
#line 239 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
	{		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T5_;
#line 239 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 239 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
		if (!!((src == NIM_NIL))) goto LA3_;

#line 239 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 239 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 239 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
		T5_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;		T5_ = usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem(src);
#line 239 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
		incRef__AT1eRuflKWyTTBdLjEDZbg_3system(T5_);
	}
	LA3_: ;

#line 240 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
	{		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T10_;
#line 240 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 240 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
		if (!!(((*dest) == NIM_NIL))) goto LA8_;

#line 240 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 240 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 240 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
		T10_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;		T10_ = usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem((*dest));
#line 240 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
		decRef__AT1eRuflKWyTTBdLjEDZbgsystem(T10_);
	}
	LA8_: ;

#line 241 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
	(*dest) = src;}

#line 5 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
N_LIB_PRIVATE N_NIMCALL(void, expect__vt4akIm2aAJMf4kfqmrlbw)(tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg actual, tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg expected, NimStringDesc* argName) {
#line 6 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	{		tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw* T5_;		NimStringDesc* T6_;
#line 6 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 6 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		if (!!((actual == expected))) goto LA3_;
		T5_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*)0;		T5_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*) newObj((&NTI__Ie1m0dv1ZHg72IgPRr1cDw_), sizeof(tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw));		(*T5_).Sup.Sup.Sup.m_type = (&NTI__yoNlBGx0D2tRizIdhQuENw_);		(*T5_).Sup.Sup.name = "ValueError";
#line 6 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		T6_ = (NimStringDesc*)0;
#line 6 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 6 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		T6_ = rawNewString((argName ? argName->Sup.len : 0) + (reprEnum((NI)expected, (&NTI__RUngo7nCHe6O8aBGIcrhtg_)) ? reprEnum((NI)expected, (&NTI__RUngo7nCHe6O8aBGIcrhtg_))->Sup.len : 0) + (reprEnum((NI)actual, (&NTI__RUngo7nCHe6O8aBGIcrhtg_)) ? reprEnum((NI)actual, (&NTI__RUngo7nCHe6O8aBGIcrhtg_))->Sup.len : 0) + 31);appendString(T6_, ((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_2));appendString(T6_, argName);appendString(T6_, ((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_3));appendString(T6_, reprEnum((NI)expected, (&NTI__RUngo7nCHe6O8aBGIcrhtg_)));appendString(T6_, ((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_4));appendString(T6_, reprEnum((NI)actual, (&NTI__RUngo7nCHe6O8aBGIcrhtg_)));		asgnRef((void**) (&(*T5_).Sup.Sup.message), T6_);		asgnRef((void**) (&(*T5_).Sup.Sup.parent), NIM_NIL);
#line 6 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		raiseExceptionEx((Exception*)T5_, "ValueError", "expect", "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rp"
"c/jsonmarshal.nim", 6);	}
	LA3_: ;
}

#line 44 "/home/runner/work/nim-waku/nim-waku/vendor/nim-web3/web3/conversions.nim"
static N_INLINE(void, fromJson__B3MpHSypnqLEU8fkNuDmSAconversions)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0, NimStringDesc* argName, NU64* result) {
#line 45 "/home/runner/work/nim-waku/nim-waku/vendor/nim-web3/web3/conversions.nim"
	{		NI64 T5_;
#line 45 "/home/runner/work/nim-waku/nim-waku/vendor/nim-web3/web3/conversions.nim"
		if (!((*n_0).kind == ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 2))) goto LA3_;

#line 46 "/home/runner/work/nim-waku/nim-waku/vendor/nim-web3/web3/conversions.nim"

#line 46 "/home/runner/work/nim-waku/nim-waku/vendor/nim-web3/web3/conversions.nim"

#line 46 "/home/runner/work/nim-waku/nim-waku/vendor/nim-web3/web3/conversions.nim"
		T5_ = (NI64)0;		T5_ = getBiggestInt__PqGEbz7TZWJYF9aMChcCbPw(n_0, IL64(0));		(*result) = ((NU64) (T5_));	}
	goto LA1_;
	LA3_: ;
	{		NimStringDesc* T7_;		NI T8_;
#line 48 "/home/runner/work/nim-waku/nim-waku/vendor/nim-web3/web3/conversions.nim"

#line 48 "/home/runner/work/nim-waku/nim-waku/vendor/nim-web3/web3/conversions.nim"
		expect__vt4akIm2aAJMf4kfqmrlbw((*n_0).kind, ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 4), argName);

#line 49 "/home/runner/work/nim-waku/nim-waku/vendor/nim-web3/web3/conversions.nim"

#line 49 "/home/runner/work/nim-waku/nim-waku/vendor/nim-web3/web3/conversions.nim"

#line 49 "/home/runner/work/nim-waku/nim-waku/vendor/nim-web3/web3/conversions.nim"

#line 49 "/home/runner/work/nim-waku/nim-waku/vendor/nim-web3/web3/conversions.nim"
		T7_ = (NimStringDesc*)0;		T7_ = getStr__QeJX1ptVmfOrOg9cwOVpcAA(n_0, ((NimStringDesc*) NIM_NIL));
#line 49 "/home/runner/work/nim-waku/nim-waku/vendor/nim-web3/web3/conversions.nim"
		T8_ = (NI)0;		T8_ = nsuParseHexInt(T7_);		(*result) = ((NU64) (T8_));	}
	LA1_: ;
}

#line 149 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
N_LIB_PRIVATE N_NIMCALL(NU64, unpackArg__FrLftaWQ5cmioEpEV8XBLQ)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* args, NimStringDesc* argName) {	NU64 result;	result = (NU64)0;
#line 151 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 151 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	fromJson__B3MpHSypnqLEU8fkNuDmSAconversions(args, argName, (&result));
	return result;}

#line 22 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size) {	void* T1_;
#line 24 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"

#line 24 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memset(a, v, ((size_t) (size)));}

#line 33 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
#line 34 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"

#line 34 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"
	nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory(p, ((int) 0), size);
}

#line 36 "/home/runner/work/nim-waku/nim-waku/vendor/nim-web3/web3/conversions.nim"
static N_INLINE(void, fromJson__oq3MeWmWhDgAvP66RcNfkwconversions)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0, NimStringDesc* argName, NU8* result) {
#line 38 "/home/runner/work/nim-waku/nim-waku/vendor/nim-web3/web3/conversions.nim"

#line 38 "/home/runner/work/nim-waku/nim-waku/vendor/nim-web3/web3/conversions.nim"
	bytesFromJson__3U9cUaaE8g9aZKvP09bWzgcXw(n_0, argName, ((NU8*) (result)), 32);
}

#line 149 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
N_LIB_PRIVATE N_NIMCALL(void, unpackArg__Astb6eHtfklUza2j7TK7cw)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* args, NimStringDesc* argName, tyArray__vEOa9c5qaE9ajWxR5R4zwfQg Result) {	chckNil((void*)Result);	nimZeroMem((void*)Result, sizeof(tyArray__vEOa9c5qaE9ajWxR5R4zwfQg));
#line 151 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 151 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	fromJson__oq3MeWmWhDgAvP66RcNfkwconversions(args, argName, Result);
}

#line 128 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
N_LIB_PRIVATE N_NIMCALL(void, fromJson__X9cjMnjMEmWu5c9a8SUD1Jxg)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0, NimStringDesc* argName, NimStringDesc** result) {
#line 129 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 129 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	expect__vt4akIm2aAJMf4kfqmrlbw((*n_0).kind, ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 4), argName);

#line 130 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 130 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	unsureAsgnRef((void**) (&(*result)), getStr__QeJX1ptVmfOrOg9cwOVpcAA(n_0, ((NimStringDesc*) NIM_NIL)));}

#line 149 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, unpackArg__LKaxiWzT6jQBMbS8bbmQcg)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* args, NimStringDesc* argName) {	NimStringDesc* result;	result = (NimStringDesc*)0;
#line 151 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 151 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	fromJson__X9cjMnjMEmWu5c9a8SUD1Jxg(args, argName, (&result));
	return result;}

#line 461 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/json.nim"
static N_INLINE(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*, X5BX5D___277k8m8OstpfbY4dHQex6wjson)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* node, NimStringDesc* name_0) {	tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* result;	tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q** T9_;	result = (tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*)0;
#line 464 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/json.nim"
	{
#line 464 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/json.nim"

#line 464 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/json.nim"

#line 464 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/json.nim"
		if (!!(!((node == 0)))) goto LA3_;

#line 464 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/json.nim"

#line 464 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/json.nim"
		failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_6));
	}
	LA3_: ;

#line 465 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/json.nim"
	{
#line 465 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/json.nim"

#line 465 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/json.nim"
		if (!!(((*node).kind == ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 5)))) goto LA7_;

#line 465 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/json.nim"

#line 465 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/json.nim"
		failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_7));
	}
	LA7_: ;

#line 468 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/json.nim"

#line 468 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/json.nim"
	if (!(((32 &(1U<<((NU)((*node).kind)&7U)))!=0))){ raiseFieldError(((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_8)); }
#line 468 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/json.nim"
	T9_ = (tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q**)0;	T9_ = X5BX5D___l9atGRY9bA25fn4p5uueZfUQ((&(*node)._kind_6.fields), name_0);	result = (*T9_);	return result;}

#line 227 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
static N_INLINE(void, nimGCunrefNoCycle)(void* p) {	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T1_;
#line 229 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 229 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"

#line 229 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
	T1_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;	T1_ = usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem(p);
#line 229 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim"
	decRef__AT1eRuflKWyTTBdLjEDZbgsystem(T1_);
}

#line 98 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
N_LIB_PRIVATE N_NIMCALL(void, fromJson__5DLVKi5Cs89aEKkcHkq1HGw)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0, NimStringDesc* argName, NU32* result) {	NI64 asInt;
#line 99 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 99 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	expect__vt4akIm2aAJMf4kfqmrlbw((*n_0).kind, ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 2), argName);

#line 100 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 100 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	asInt = getBiggestInt__PqGEbz7TZWJYF9aMChcCbPw(n_0, IL64(0));
#line 103 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	{		tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw* T5_;		NimStringDesc* T6_;
#line 103 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		if (!(asInt < IL64(0))) goto LA3_;
		T5_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*)0;		T5_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*) newObj((&NTI__Ie1m0dv1ZHg72IgPRr1cDw_), sizeof(tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw));		(*T5_).Sup.Sup.Sup.m_type = (&NTI__yoNlBGx0D2tRizIdhQuENw_);		(*T5_).Sup.Sup.name = "ValueError";		T6_ = (NimStringDesc*)0;		T6_ = (*T5_).Sup.Sup.message; (*T5_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_10));		if (T6_) nimGCunrefNoCycle(T6_);		asgnRef((void**) (&(*T5_).Sup.Sup.parent), NIM_NIL);
#line 104 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		raiseExceptionEx((Exception*)T5_, "ValueError", "fromJson", "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rp"
"c/jsonmarshal.nim", 104);	}
	LA3_: ;

#line 106 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	(*result) = ((NU32) (asInt));}

#line 101 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/options.nim"
static N_INLINE(tyObject_Option__rVkI1RILdi0akg69brivmzg, some__3uXaIMXFnDdgZxwHKhW7igoptions)(NU32 val_0) {	tyObject_Option__rVkI1RILdi0akg69brivmzg result;	nimZeroMem((void*)(&result), sizeof(tyObject_Option__rVkI1RILdi0akg69brivmzg));
#line 121 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/options.nim"
	result.has = NIM_TRUE;
#line 122 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/options.nim"
	result.val = val_0;	return result;}

#line 63 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
N_LIB_PRIVATE N_NIMCALL(void, fromJson__NOuIM3H7iyiPvYQLWHFxPw)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0, NimStringDesc* argName, tyObject_Option__rVkI1RILdi0akg69brivmzg* result) {
#line 65 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	{		NU32 val_1;
#line 65 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 65 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		if (!!(((*n_0).kind == ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 0)))) goto LA3_;
		val_1 = (NU32)0;
#line 67 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 67 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		fromJson__5DLVKi5Cs89aEKkcHkq1HGw(n_0, argName, (&val_1));

#line 68 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 68 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		(*result) = some__3uXaIMXFnDdgZxwHKhW7igoptions(val_1);	}
	LA3_: ;
}

#line 48 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
N_LIB_PRIVATE N_NIMCALL(void, fromJson__2gjcjrVVc6rLiin5CkarRg)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0, NimStringDesc* argName, tyObject_WakuRelayMessage__jLO9cyS189bZS4ql8DPZJevw* result) {
#line 49 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 49 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	expect__vt4akIm2aAJMf4kfqmrlbw((*n_0).kind, ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 5), argName);

#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	{		NIM_BOOL T3_;		NIM_BOOL T5_;		tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* T8_;
#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		T3_ = (NIM_BOOL)0;		T3_ = NIM_FALSE;		if (!(T3_)) goto LA4_;

#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		T5_ = (NIM_BOOL)0;		T5_ = hasKey__zrDHfVBiQiPv9bNJ29c1ZINg_2(n_0, ((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_5));		T3_ = !(T5_);		LA4_: ;
		if (!T3_) goto LA6_;

#line 52 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 52 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 52 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		T8_ = (tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*)0;		T8_ = newJNull__nXwnFPu9beTnGPwglrr7ztA_3();
#line 52 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		fromJson__lZoyfH55Wzpb8bL1TaXbyw(T8_, ((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_5), (&(*result).payload));
	}
	goto LA1_;
	LA6_: ;
	{		tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* T10_;
#line 54 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 54 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 54 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		T10_ = (tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*)0;		T10_ = X5BX5D___277k8m8OstpfbY4dHQex6wjson(n_0, ((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_5));
#line 54 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		fromJson__lZoyfH55Wzpb8bL1TaXbyw(T10_, ((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_5), (&(*result).payload));
	}
	LA1_: ;

#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	{		NIM_BOOL T13_;		NIM_BOOL T15_;		tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* T18_;
#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		T13_ = (NIM_BOOL)0;		T13_ = NIM_TRUE;		if (!(T13_)) goto LA14_;

#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		T15_ = (NIM_BOOL)0;		T15_ = hasKey__zrDHfVBiQiPv9bNJ29c1ZINg_2(n_0, ((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_9));		T13_ = !(T15_);		LA14_: ;
		if (!T13_) goto LA16_;

#line 52 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 52 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 52 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		T18_ = (tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*)0;		T18_ = newJNull__nXwnFPu9beTnGPwglrr7ztA_3();
#line 52 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		fromJson__NOuIM3H7iyiPvYQLWHFxPw(T18_, ((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_9), (&(*result).contentTopic));
	}
	goto LA11_;
	LA16_: ;
	{		tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* T20_;
#line 54 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 54 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 54 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		T20_ = (tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*)0;		T20_ = X5BX5D___277k8m8OstpfbY4dHQex6wjson(n_0, ((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_9));
#line 54 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		fromJson__NOuIM3H7iyiPvYQLWHFxPw(T20_, ((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_9), (&(*result).contentTopic));
	}
	LA11_: ;
}

#line 149 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
N_LIB_PRIVATE N_NIMCALL(void, unpackArg__DU9aL5kAwhAld7UHknb6W6A)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* args, NimStringDesc* argName, tyObject_WakuRelayMessage__jLO9cyS189bZS4ql8DPZJevw* Result) {	chckNil((void*)Result);	unsureAsgnRef((void**)&(*Result).payload, NIM_NIL);	(*Result).contentTopic.val = 0;	(*Result).contentTopic.has = 0;
#line 151 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 151 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	fromJson__2gjcjrVVc6rLiin5CkarRg(args, argName, Result);
}

#line 8 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*, percent___1pPfA7lIcakPONTZF8pXBA)(NU8 n_0) {	tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* result;	result = (tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*)0;
#line 9 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 9 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	result = newJInt__kuRQ9bONMtpC9bToqIhX9cETA_2(((NI64) (((NI) (n_0)))));	return result;}

#line 11 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*, percent___eYSqk7toszsHj8yE1ryODA)(NU64 n_0) {	tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* result;	result = (tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*)0;
#line 12 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	if ((NI64)(n_0) < ((NI) (IL64(-9223372036854775807) - IL64(1))) || (NI64)(n_0) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(n_0, ((NI) (IL64(-9223372036854775807) - IL64(1))), ((NI) IL64(9223372036854775807))); }
#line 12 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	result = newJInt__kuRQ9bONMtpC9bToqIhX9cETA_2(((NI64) (((NI) (n_0)))));	return result;}

#line 470 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/json.nim"
static N_INLINE(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*, X5BX5D___iGpexJJNbY5V0TEMs9aHjwQjson)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* node, NI index) {	tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* result;{	result = (tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*)0;
#line 474 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/json.nim"
	{
#line 474 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/json.nim"

#line 474 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/json.nim"

#line 474 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/json.nim"
		if (!!(!((node == 0)))) goto LA3_;

#line 474 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/json.nim"

#line 474 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/json.nim"
		failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_11));
	}
	LA3_: ;

#line 475 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/json.nim"
	{
#line 475 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/json.nim"

#line 475 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/json.nim"
		if (!!(((*node).kind == ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 6)))) goto LA7_;

#line 475 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/json.nim"

#line 475 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/json.nim"
		failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_12));
	}
	LA7_: ;

#line 476 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/json.nim"

#line 476 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/json.nim"
	if (!(((64 &(1U<<((NU)((*node).kind)&7U)))!=0))){ raiseFieldError(((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_13)); }	if ((NU)(index) >= (NU)((*node)._kind_7.elems ? (*node)._kind_7.elems->Sup.len : 0)){ raiseIndexError2(index,((*node)._kind_7.elems ? (*node)._kind_7.elems->Sup.len : 0)-1); }	result = (*node)._kind_7.elems->data[index];	goto BeforeRet_;
	}BeforeRet_: ;
	return result;}

#line 132 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
N_LIB_PRIVATE N_NIMCALL(void, fromJson__3LJCfR9aw1ZjNE8C0pCrinQ)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0, NimStringDesc* argName, tySequence__sM4lkSb7zS6F7OVMvW9cffQ** result) {	NI T1_;
#line 138 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 138 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	expect__vt4akIm2aAJMf4kfqmrlbw((*n_0).kind, ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 6), argName);

#line 139 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 139 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 139 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	T1_ = (NI)0;	T1_ = len__Og3BmQpaL5V6gYg5JnWK3Q(n_0);	if ((T1_) < ((NI) 0) || (T1_) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(T1_, ((NI) 0), ((NI) IL64(9223372036854775807))); }
#line 139 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	unsureAsgnRef((void**) (&(*result)), newSeq__q7W9bxIQ7BrFLngLO9cYelsA(((NI) (T1_))));	{		NI i;		NI colontmp_;		NI i_2;		i = (NI)0;		colontmp_ = (NI)0;
#line 140 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 140 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		colontmp_ = len__Og3BmQpaL5V6gYg5JnWK3Q(n_0);
#line 106 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators_1.nim"
		i_2 = ((NI) 0);		{
#line 107 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators_1.nim"
			while (1) {				tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* T5_;				NI TM__BnC9avUv8ny2yMv6NSfv9cQw_14;
#line 107 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators_1.nim"
				if (!(i_2 < colontmp_)) goto LA4;

#line 140 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
				i = i_2;
#line 141 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 141 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 141 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
				T5_ = (tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*)0;				T5_ = X5BX5D___iGpexJJNbY5V0TEMs9aHjwQjson(n_0, i);				if ((NU)(i) >= (NU)((*result) ? (*result)->Sup.len : 0)){ raiseIndexError2(i,((*result) ? (*result)->Sup.len : 0)-1); }
#line 141 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
				fromJson__X9cjMnjMEmWu5c9a8SUD1Jxg(T5_, argName, (&(*result)->data[i]));

#line 109 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators_1.nim"
				if (nimAddInt(i_2, ((NI) 1), &TM__BnC9avUv8ny2yMv6NSfv9cQw_14)) { raiseOverflow(); };				i_2 = (NI)(TM__BnC9avUv8ny2yMv6NSfv9cQw_14);			} LA4: ;
		}
	}
}

#line 149 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ*, unpackArg__oH2zJFV49aHb9aKnd5PLY25A)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* args, NimStringDesc* argName) {	tySequence__sM4lkSb7zS6F7OVMvW9cffQ* result;	result = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ*)0;
#line 151 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 151 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	fromJson__3LJCfR9aw1ZjNE8C0pCrinQ(args, argName, (&result));
	return result;}

#line 149 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
N_LIB_PRIVATE N_NIMCALL(NU32, unpackArg__ceWfSCHRbD1OVKyhr305FQ)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* args, NimStringDesc* argName) {	NU32 result;	result = (NU32)0;
#line 151 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 151 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	fromJson__5DLVKi5Cs89aEKkcHkq1HGw(args, argName, (&result));
	return result;}

#line 132 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
N_LIB_PRIVATE N_NIMCALL(void, fromJson__Rqs8fR2oyGbE9bx2hG7ALpg)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0, NimStringDesc* argName, tySequence__9bAGqSvkAaFL9bWjsEPslrFA** result) {	NI T1_;
#line 138 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 138 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	expect__vt4akIm2aAJMf4kfqmrlbw((*n_0).kind, ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 6), argName);

#line 139 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 139 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 139 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	T1_ = (NI)0;	T1_ = len__Og3BmQpaL5V6gYg5JnWK3Q(n_0);	if ((T1_) < ((NI) 0) || (T1_) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(T1_, ((NI) 0), ((NI) IL64(9223372036854775807))); }
#line 139 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	unsureAsgnRef((void**) (&(*result)), newSeq__4g9cmvwewbrdtpBMV5P3thg(((NI) (T1_))));	{		NI i;		NI colontmp_;		NI i_2;		i = (NI)0;		colontmp_ = (NI)0;
#line 140 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 140 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		colontmp_ = len__Og3BmQpaL5V6gYg5JnWK3Q(n_0);
#line 106 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators_1.nim"
		i_2 = ((NI) 0);		{
#line 107 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators_1.nim"
			while (1) {				tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* T5_;				NI TM__BnC9avUv8ny2yMv6NSfv9cQw_16;
#line 107 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators_1.nim"
				if (!(i_2 < colontmp_)) goto LA4;

#line 140 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
				i = i_2;
#line 141 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 141 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 141 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
				T5_ = (tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*)0;				T5_ = X5BX5D___iGpexJJNbY5V0TEMs9aHjwQjson(n_0, i);				if ((NU)(i) >= (NU)((*result) ? (*result)->Sup.len : 0)){ raiseIndexError2(i,((*result) ? (*result)->Sup.len : 0)-1); }
#line 141 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
				fromJson__5DLVKi5Cs89aEKkcHkq1HGw(T5_, argName, (&(*result)->data[i]));

#line 109 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators_1.nim"
				if (nimAddInt(i_2, ((NI) 1), &TM__BnC9avUv8ny2yMv6NSfv9cQw_16)) { raiseOverflow(); };				i_2 = (NI)(TM__BnC9avUv8ny2yMv6NSfv9cQw_16);			} LA4: ;
		}
	}
}

#line 48 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
N_LIB_PRIVATE N_NIMCALL(void, fromJson__4JjKJcmNTX9btU71Xok2MzQ)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0, NimStringDesc* argName, tyObject_ContentFilter__zmS3UuJydVs2xUezA1n9akA* result) {
#line 49 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 49 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	expect__vt4akIm2aAJMf4kfqmrlbw((*n_0).kind, ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 5), argName);

#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	{		NIM_BOOL T3_;		NIM_BOOL T5_;		tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* T8_;
#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		T3_ = (NIM_BOOL)0;		T3_ = NIM_FALSE;		if (!(T3_)) goto LA4_;

#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		T5_ = (NIM_BOOL)0;		T5_ = hasKey__zrDHfVBiQiPv9bNJ29c1ZINg_2(n_0, ((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_15));		T3_ = !(T5_);		LA4_: ;
		if (!T3_) goto LA6_;

#line 52 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 52 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 52 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		T8_ = (tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*)0;		T8_ = newJNull__nXwnFPu9beTnGPwglrr7ztA_3();
#line 52 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		fromJson__Rqs8fR2oyGbE9bx2hG7ALpg(T8_, ((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_15), (&(*result).topics));
	}
	goto LA1_;
	LA6_: ;
	{		tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* T10_;
#line 54 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 54 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 54 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		T10_ = (tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*)0;		T10_ = X5BX5D___277k8m8OstpfbY4dHQex6wjson(n_0, ((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_15));
#line 54 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		fromJson__Rqs8fR2oyGbE9bx2hG7ALpg(T10_, ((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_15), (&(*result).topics));
	}
	LA1_: ;
}

#line 132 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
N_LIB_PRIVATE N_NIMCALL(void, fromJson__4qb89coqZq3XBvazA173pGA)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0, NimStringDesc* argName, tySequence__xNHF59br19a2ddRDpm49b8z3A** result) {	NI T1_;
#line 138 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 138 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	expect__vt4akIm2aAJMf4kfqmrlbw((*n_0).kind, ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 6), argName);

#line 139 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 139 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 139 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	T1_ = (NI)0;	T1_ = len__Og3BmQpaL5V6gYg5JnWK3Q(n_0);	if ((T1_) < ((NI) 0) || (T1_) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(T1_, ((NI) 0), ((NI) IL64(9223372036854775807))); }
#line 139 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	unsureAsgnRef((void**) (&(*result)), newSeq__ulssHs3qvX9a2WFQd3HH1aA(((NI) (T1_))));	{		NI i;		NI colontmp_;		NI i_2;		i = (NI)0;		colontmp_ = (NI)0;
#line 140 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 140 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		colontmp_ = len__Og3BmQpaL5V6gYg5JnWK3Q(n_0);
#line 106 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators_1.nim"
		i_2 = ((NI) 0);		{
#line 107 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators_1.nim"
			while (1) {				tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* T5_;				NI TM__BnC9avUv8ny2yMv6NSfv9cQw_17;
#line 107 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators_1.nim"
				if (!(i_2 < colontmp_)) goto LA4;

#line 140 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
				i = i_2;
#line 141 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 141 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 141 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
				T5_ = (tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*)0;				T5_ = X5BX5D___iGpexJJNbY5V0TEMs9aHjwQjson(n_0, i);				if ((NU)(i) >= (NU)((*result) ? (*result)->Sup.len : 0)){ raiseIndexError2(i,((*result) ? (*result)->Sup.len : 0)-1); }
#line 141 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
				fromJson__4JjKJcmNTX9btU71Xok2MzQ(T5_, argName, (&(*result)->data[i]));

#line 109 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/iterators_1.nim"
				if (nimAddInt(i_2, ((NI) 1), &TM__BnC9avUv8ny2yMv6NSfv9cQw_17)) { raiseOverflow(); };				i_2 = (NI)(TM__BnC9avUv8ny2yMv6NSfv9cQw_17);			} LA4: ;
		}
	}
}

#line 149 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
N_LIB_PRIVATE N_NIMCALL(tySequence__xNHF59br19a2ddRDpm49b8z3A*, unpackArg__0hggNUEMu08yE9aymOU8pvw)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* args, NimStringDesc* argName) {	tySequence__xNHF59br19a2ddRDpm49b8z3A* result;	result = (tySequence__xNHF59br19a2ddRDpm49b8z3A*)0;
#line 151 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 151 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	fromJson__4qb89coqZq3XBvazA173pGA(args, argName, (&result));
	return result;}

#line 149 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
N_LIB_PRIVATE N_NIMCALL(tySequence__9bAGqSvkAaFL9bWjsEPslrFA*, unpackArg__AszvVUQyOTOM5sREWMHrKg)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* args, NimStringDesc* argName) {	tySequence__9bAGqSvkAaFL9bWjsEPslrFA* result;	result = (tySequence__9bAGqSvkAaFL9bWjsEPslrFA*)0;
#line 151 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 151 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	fromJson__Rqs8fR2oyGbE9bx2hG7ALpg(args, argName, (&result));
	return result;}

#line 88 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
N_LIB_PRIVATE N_NIMCALL(void, fromJson__iWHxnLNKA767Xc5zx9b7o0w)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0, NimStringDesc* argName, NU64* result) {	NI asInt;
#line 89 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 89 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	expect__vt4akIm2aAJMf4kfqmrlbw((*n_0).kind, ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 2), argName);

#line 90 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 90 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	asInt = getInt__1efdasyP68nDQg4BeLHzGQ(n_0, ((NI) 0));
#line 93 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	{		tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw* T5_;		NimStringDesc* T6_;
#line 93 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		if (!(asInt < ((NI) 0))) goto LA3_;
		T5_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*)0;		T5_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*) newObj((&NTI__Ie1m0dv1ZHg72IgPRr1cDw_), sizeof(tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw));		(*T5_).Sup.Sup.Sup.m_type = (&NTI__yoNlBGx0D2tRizIdhQuENw_);		(*T5_).Sup.Sup.name = "ValueError";		T6_ = (NimStringDesc*)0;		T6_ = (*T5_).Sup.Sup.message; (*T5_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_10));		if (T6_) nimGCunrefNoCycle(T6_);		asgnRef((void**) (&(*T5_).Sup.Sup.parent), NIM_NIL);
#line 94 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		raiseExceptionEx((Exception*)T5_, "ValueError", "fromJson", "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rp"
"c/jsonmarshal.nim", 94);	}
	LA3_: ;

#line 96 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	(*result) = ((NU64) (asInt));}

#line 124 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
N_LIB_PRIVATE N_NIMCALL(void, fromJson__M4IEVBcoOoODCVrboQ9cZfg)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0, NimStringDesc* argName, NF* result) {
#line 125 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 125 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	expect__vt4akIm2aAJMf4kfqmrlbw((*n_0).kind, ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 3), argName);

#line 126 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 126 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	(*result) = getFloat__llZz76LOmvR0qTBY4kY9cFg(n_0, 0.0);}

#line 48 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
N_LIB_PRIVATE N_NIMCALL(void, fromJson__89aLJpLBkv36ftYPufTBHwg)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0, NimStringDesc* argName, tyObject_Index__lOZ7xaSDQuG6u4WFzCveFQ* result) {
#line 49 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 49 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	expect__vt4akIm2aAJMf4kfqmrlbw((*n_0).kind, ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 5), argName);

#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	{		NIM_BOOL T3_;		NIM_BOOL T5_;		tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* T8_;
#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		T3_ = (NIM_BOOL)0;		T3_ = NIM_FALSE;		if (!(T3_)) goto LA4_;

#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		T5_ = (NIM_BOOL)0;		T5_ = hasKey__zrDHfVBiQiPv9bNJ29c1ZINg_2(n_0, ((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_20));		T3_ = !(T5_);		LA4_: ;
		if (!T3_) goto LA6_;

#line 52 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 52 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 52 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		T8_ = (tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*)0;		T8_ = newJNull__nXwnFPu9beTnGPwglrr7ztA_3();
#line 52 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		fromJson__aXqydplDjMIZGfO9b47bWng(T8_, ((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_20), (&(*result).digest));
	}
	goto LA1_;
	LA6_: ;
	{		tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* T10_;
#line 54 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 54 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 54 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		T10_ = (tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*)0;		T10_ = X5BX5D___277k8m8OstpfbY4dHQex6wjson(n_0, ((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_20));
#line 54 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		fromJson__aXqydplDjMIZGfO9b47bWng(T10_, ((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_20), (&(*result).digest));
	}
	LA1_: ;

#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	{		NIM_BOOL T13_;		NIM_BOOL T15_;		tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* T18_;
#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		T13_ = (NIM_BOOL)0;		T13_ = NIM_FALSE;		if (!(T13_)) goto LA14_;

#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		T15_ = (NIM_BOOL)0;		T15_ = hasKey__zrDHfVBiQiPv9bNJ29c1ZINg_2(n_0, ((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_21));		T13_ = !(T15_);		LA14_: ;
		if (!T13_) goto LA16_;

#line 52 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 52 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 52 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		T18_ = (tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*)0;		T18_ = newJNull__nXwnFPu9beTnGPwglrr7ztA_3();
#line 52 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		fromJson__M4IEVBcoOoODCVrboQ9cZfg(T18_, ((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_21), (&(*result).receivedTime));
	}
	goto LA11_;
	LA16_: ;
	{		tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* T20_;
#line 54 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 54 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 54 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		T20_ = (tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*)0;		T20_ = X5BX5D___277k8m8OstpfbY4dHQex6wjson(n_0, ((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_21));
#line 54 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		fromJson__M4IEVBcoOoODCVrboQ9cZfg(T20_, ((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_21), (&(*result).receivedTime));
	}
	LA11_: ;
}

#line 101 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/options.nim"
static N_INLINE(tyObject_Option__QZVOEjCvFvdMOcWYv3UMWg, some__cDTM0qv3zc9ckbyfeCmQDngoptions)(tyObject_Index__lOZ7xaSDQuG6u4WFzCveFQ* val_0) {	tyObject_Option__QZVOEjCvFvdMOcWYv3UMWg result;	nimZeroMem((void*)(&result), sizeof(tyObject_Option__QZVOEjCvFvdMOcWYv3UMWg));
#line 121 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/options.nim"
	result.has = NIM_TRUE;
#line 122 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/options.nim"
	result.val = (*val_0);	return result;}

#line 63 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
N_LIB_PRIVATE N_NIMCALL(void, fromJson__pGdfGL0puujyixjN9cz0rlw)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0, NimStringDesc* argName, tyObject_Option__QZVOEjCvFvdMOcWYv3UMWg* result) {
#line 65 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	{		tyObject_Index__lOZ7xaSDQuG6u4WFzCveFQ val_1;
#line 65 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 65 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		if (!!(((*n_0).kind == ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 0)))) goto LA3_;
		nimZeroMem((void*)(&val_1), sizeof(tyObject_Index__lOZ7xaSDQuG6u4WFzCveFQ));
#line 67 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 67 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		fromJson__89aLJpLBkv36ftYPufTBHwg(n_0, argName, (&val_1));

#line 68 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 68 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		(*result) = some__cDTM0qv3zc9ckbyfeCmQDngoptions((&val_1));	}
	LA3_: ;
}

#line 70 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
N_LIB_PRIVATE N_NIMCALL(void, fromJson__IUlrvPKZ7DCHL75kpCVUmA)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0, NimStringDesc* argName, NIM_BOOL* result) {
#line 71 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 71 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	expect__vt4akIm2aAJMf4kfqmrlbw((*n_0).kind, ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 1), argName);

#line 72 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 72 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	(*result) = getBool__WLYG2J5rvQY8w8vO47RYig(n_0, NIM_FALSE);}

#line 48 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
N_LIB_PRIVATE N_NIMCALL(void, fromJson__IsUEA2R2B4wBR5DoBXoRUg)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n_0, NimStringDesc* argName, tyObject_StorePagingOptions__gOYu9bLiJN6GFHM9bfNsoUBg* result) {
#line 49 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 49 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	expect__vt4akIm2aAJMf4kfqmrlbw((*n_0).kind, ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 5), argName);

#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	{		NIM_BOOL T3_;		NIM_BOOL T5_;		tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* T8_;
#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		T3_ = (NIM_BOOL)0;		T3_ = NIM_FALSE;		if (!(T3_)) goto LA4_;

#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		T5_ = (NIM_BOOL)0;		T5_ = hasKey__zrDHfVBiQiPv9bNJ29c1ZINg_2(n_0, ((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_18));		T3_ = !(T5_);		LA4_: ;
		if (!T3_) goto LA6_;

#line 52 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 52 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 52 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		T8_ = (tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*)0;		T8_ = newJNull__nXwnFPu9beTnGPwglrr7ztA_3();
#line 52 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		fromJson__iWHxnLNKA767Xc5zx9b7o0w(T8_, ((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_18), (&(*result).pageSize));
	}
	goto LA1_;
	LA6_: ;
	{		tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* T10_;
#line 54 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 54 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 54 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		T10_ = (tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*)0;		T10_ = X5BX5D___277k8m8OstpfbY4dHQex6wjson(n_0, ((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_18));
#line 54 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		fromJson__iWHxnLNKA767Xc5zx9b7o0w(T10_, ((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_18), (&(*result).pageSize));
	}
	LA1_: ;

#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	{		NIM_BOOL T13_;		NIM_BOOL T15_;		tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* T18_;
#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		T13_ = (NIM_BOOL)0;		T13_ = NIM_TRUE;		if (!(T13_)) goto LA14_;

#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		T15_ = (NIM_BOOL)0;		T15_ = hasKey__zrDHfVBiQiPv9bNJ29c1ZINg_2(n_0, ((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_19));		T13_ = !(T15_);		LA14_: ;
		if (!T13_) goto LA16_;

#line 52 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 52 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 52 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		T18_ = (tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*)0;		T18_ = newJNull__nXwnFPu9beTnGPwglrr7ztA_3();
#line 52 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		fromJson__pGdfGL0puujyixjN9cz0rlw(T18_, ((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_19), (&(*result).cursor));
	}
	goto LA11_;
	LA16_: ;
	{		tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* T20_;
#line 54 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 54 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 54 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		T20_ = (tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*)0;		T20_ = X5BX5D___277k8m8OstpfbY4dHQex6wjson(n_0, ((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_19));
#line 54 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		fromJson__pGdfGL0puujyixjN9cz0rlw(T20_, ((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_19), (&(*result).cursor));
	}
	LA11_: ;

#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	{		NIM_BOOL T23_;		NIM_BOOL T25_;		tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* T28_;
#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		T23_ = (NIM_BOOL)0;		T23_ = NIM_FALSE;		if (!(T23_)) goto LA24_;

#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 51 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		T25_ = (NIM_BOOL)0;		T25_ = hasKey__zrDHfVBiQiPv9bNJ29c1ZINg_2(n_0, ((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_22));		T23_ = !(T25_);		LA24_: ;
		if (!T23_) goto LA26_;

#line 52 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 52 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 52 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		T28_ = (tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*)0;		T28_ = newJNull__nXwnFPu9beTnGPwglrr7ztA_3();
#line 52 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		fromJson__IUlrvPKZ7DCHL75kpCVUmA(T28_, ((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_22), (&(*result).forward));
	}
	goto LA21_;
	LA26_: ;
	{		tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* T30_;
#line 54 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 54 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 54 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		T30_ = (tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*)0;		T30_ = X5BX5D___277k8m8OstpfbY4dHQex6wjson(n_0, ((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_22));
#line 54 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
		fromJson__IUlrvPKZ7DCHL75kpCVUmA(T30_, ((NimStringDesc*) &TM__BnC9avUv8ny2yMv6NSfv9cQw_22), (&(*result).forward));
	}
	LA21_: ;
}

#line 149 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_StorePagingOptions__gOYu9bLiJN6GFHM9bfNsoUBg, unpackArg__ooY0R33pZbeUDfUKGYe4aA)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* args, NimStringDesc* argName) {	tyObject_StorePagingOptions__gOYu9bLiJN6GFHM9bfNsoUBg result;	nimZeroMem((void*)(&result), sizeof(tyObject_StorePagingOptions__gOYu9bLiJN6GFHM9bfNsoUBg));
#line 151 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"

#line 151 "/home/runner/work/nim-waku/nim-waku/vendor/nim-json-rpc/json_rpc/jsonmarshal.nim"
	fromJson__IsUEA2R2B4wBR5DoBXoRUg(args, argName, (&result));
	return result;}
