/* Generated by Nim Compiler v1.2.6 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -pthread -I/home/runner/work/nim-waku/nim-waku/vendor/nim-libbacktrace -I/home/runner/work/nim-waku/nim-waku/vendor/nim-libbacktrace/install/usr/include -I/home/runner/work/nim-waku/nim-waku/vendor/nim-secp256k1/secp256k1_wrapper -I/home/runner/work/nim-waku/nim-waku/vendor/nim-secp256k1/secp256k1_wrapper/secp256k1 -I/home/runner/work/nim-waku/nim-waku/vendor/nim-secp256k1/secp256k1_wrapper/secp256k1/src -DHAVE_CONFIG_H -DHAVE_BUILTIN_EXPECT -I/home/runner/work/nim-waku/nim-waku/vendor/nim-bearssl/bearssl/csources/src -I/home/runner/work/nim-waku/nim-waku/vendor/nim-bearssl/bearssl/csources/inc -I/home/runner/work/nim-waku/nim-waku/vendor/nim-bearssl/bearssl/csources/tools -DBR_USE_UNIX_TIME=1 -DBR_USE_URANDOM=1 -DBR_LE_UNALIGNED=1 -DBR_64=1  -DBR_amd64=1 -DBR_INT128=1 -march=native -g3 -Og -O3 -fno-strict-aliasing -fno-ident  -I/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib -I/home/runner/work/nim-waku/nim-waku/waku/v1/node -o nimcache/release/start_network/@m..@s..@s..@svendor@snim-eth@seth@skeys.nim.c.o nimcache/release/start_network/@m..@s..@s..@svendor@snim-eth@seth@skeys.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include "bearssl_rand.h"
#include "bearssl_hash.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_SkKeyPair__11md6PDL9c3Ydro9bo69avH7g tyObject_SkKeyPair__11md6PDL9c3Ydro9bo69avH7g;
typedef struct tyObject_SkSecretKey__aKiBFtqo69b60sWLnM5A9c3w tyObject_SkSecretKey__aKiBFtqo69b60sWLnM5A9c3w;
typedef struct tyObject_SkPublicKey__YxxaGK7KOKaWCOaZ44rHMA tyObject_SkPublicKey__YxxaGK7KOKaWCOaZ44rHMA;
typedef struct tyObject_secp256k1_pubkey__GYc9aFo1e2qOLdmAqUvIikQ tyObject_secp256k1_pubkey__GYc9aFo1e2qOLdmAqUvIikQ;
typedef struct tyObject_Env_keysdotnim___tHzJDR2mlN9ayrQ3Mg5BW5Q tyObject_Env_keysdotnim___tHzJDR2mlN9ayrQ3Mg5BW5Q;
typedef struct RootObj RootObj;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef unsigned char tyArray__A1SHJCPZVISPTujoygIPEQ[64];
typedef N_CDECL_PTR(int, tyProc__8515EaYVeX8ph3fGJmTq3w) (br_prng_class** ctx);
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {NI size;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
NCSTRING name;
TNimType* nextType;
NI instances;
NI sizes;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NU8 tyArray__vEOa9c5qaE9ajWxR5R4zwfQg[32];
struct tyObject_SkSecretKey__aKiBFtqo69b60sWLnM5A9c3w {tyArray__vEOa9c5qaE9ajWxR5R4zwfQg data;
};
typedef NU8 tyArray__w5VB8h5K8DB3oWrO5U2wqg[64];
struct tyObject_secp256k1_pubkey__GYc9aFo1e2qOLdmAqUvIikQ {tyArray__w5VB8h5K8DB3oWrO5U2wqg data;
};
struct tyObject_SkPublicKey__YxxaGK7KOKaWCOaZ44rHMA {tyObject_secp256k1_pubkey__GYc9aFo1e2qOLdmAqUvIikQ data;
};
struct tyObject_SkKeyPair__11md6PDL9c3Ydro9bo69avH7g {tyObject_SkSecretKey__aKiBFtqo69b60sWLnM5A9c3w seckey;
tyObject_SkPublicKey__YxxaGK7KOKaWCOaZ44rHMA pubkey;
};
struct RootObj {TNimType* m_type;};
struct tyObject_Env_keysdotnim___tHzJDR2mlN9ayrQ3Mg5BW5Q {  RootObj Sup;NI colonstate_;
br_hmac_drbg_context* rngPtr1;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (NU8* data_0, NI data_0Len_0, void* ClE_0);
void* ClE_0;
} tyProc__2eQPaS8XIidfzb11dDC4nw;
struct TGenericSeq {NI len;
NI reserved;
};
struct NimStringDesc {  TGenericSeq Sup;NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyArray__DqM3b17bbm0d9bCZr9c2fLDQ[65];
typedef N_CDECL_PTR(void, tyProc__3qI9bVHqiq07sTQRU9bkkkYQ) (br_prng_class** ctx, void* params, void* seed, NI seedLen);
typedef N_CDECL_PTR(void, tyProc__hquUwNr88w4T5ldt8BqLLQ) (br_prng_class** ctx, void* out_0, NI len_0);
typedef N_CDECL_PTR(void, tyProc__bF2JFxTs1q6Lq365NU79a2Q) (br_hash_class** ctx);
typedef N_CDECL_PTR(void, tyProc__Dc9br5a6SHw9cxie3cas0KTA) (br_hash_class** ctx, void* data_0, NI len_0);
typedef N_CDECL_PTR(void, tyProc__JETfgzvEnx6Tz9bYRct9a51g) (br_hash_class** ctx, void* dst);
typedef N_CDECL_PTR(NU64, tyProc__e9bd9aJH2sCZh75q9aAcv7ylg) (br_hash_class** ctx, void* dst);
typedef N_CDECL_PTR(void, tyProc__g9c2vH2tlPaPmvfTZ3PeWQQ) (br_hash_class** ctx, void* stb, NU64 count_0);
N_LIB_PRIVATE N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(tyObject_SkSecretKey__aKiBFtqo69b60sWLnM5A9c3w, random__pJ2doYDmdqPuNiIuwUmJ4w)(br_hmac_drbg_context* rng_0);
static N_NIMCALL(void, Marker_tyRef__KHHquxSoY3JWz0nX5DbfmQ)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(tyObject_SkSecretKey__aKiBFtqo69b60sWLnM5A9c3w, random__0zyuItkuaHgarDWONXkbnQ)(tyProc__2eQPaS8XIidfzb11dDC4nw rng_0);
N_LIB_PRIVATE N_CLOSURE(void, callRng__ZB19agXKjnWjgtU9chW9bidfw)(NU8* data_0, NI data_0Len_0, void* ClE_0);
N_LIB_PRIVATE N_NIMCALL(void, brHmacDrbgGenerate__jb39atYOOGTT2cdYx6onnSw)(br_hmac_drbg_context* ctx, NU8* outp, NI outpLen_0);
N_LIB_PRIVATE N_NOINLINE(void, chckNil)(void* p);
N_LIB_PRIVATE N_NIMCALL(tyObject_SkPublicKey__YxxaGK7KOKaWCOaZ44rHMA, toPublicKey__dZX6pG1PJuze9ctWTRA1ENw)(tyObject_SkSecretKey__aKiBFtqo69b60sWLnM5A9c3w* key_0);
static N_INLINE(NimStringDesc*, toHex__8S8gmm9b1kIYuNI7oeA9arYQbyteutils)(tyArray__vEOa9c5qaE9ajWxR5R4zwfQg ba);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, toHexAux__mTF3iGytPXR76nCDQ9aqz9cw)(NU8* ba, NI baLen_0);
N_LIB_PRIVATE N_NIMCALL(void, toRaw__A1jy5RjxYg9aCVFRbqZKqvA)(tyObject_SkSecretKey__aKiBFtqo69b60sWLnM5A9c3w* seckey, tyArray__vEOa9c5qaE9ajWxR5R4zwfQg Result);
N_LIB_PRIVATE N_NIMCALL(void, toRaw__QU8um79aWTK6cAEMtJp8d7g)(tyObject_SkSecretKey__aKiBFtqo69b60sWLnM5A9c3w* seckey, tyArray__vEOa9c5qaE9ajWxR5R4zwfQg Result);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
static N_INLINE(NimStringDesc*, toHex__WZR7PQRd3CyFIbwX5SDWPAbyteutils)(tyArray__w5VB8h5K8DB3oWrO5U2wqg ba);
N_LIB_PRIVATE N_NIMCALL(void, toRaw__W9bYIkOOHQ8dZSTz9aIjEPEQ)(tyObject_SkPublicKey__YxxaGK7KOKaWCOaZ44rHMA* pubkey, tyArray__w5VB8h5K8DB3oWrO5U2wqg Result);
N_LIB_PRIVATE N_NIMCALL(void, toRaw__bCgy0bI8LIRIvVpAjgBPMg)(tyObject_SkPublicKey__YxxaGK7KOKaWCOaZ44rHMA* pubkey, tyArray__DqM3b17bbm0d9bCZr9c2fLDQ Result);
static N_INLINE(void, copyMem__i80o3k0SgEI5gTRCzYdyWAsystem)(void* dest, void* source, NI size);
extern TNimType NTI__RuNvFuo5ptASsihINNteSw_;
extern TNimType NTI__ytyiCJqK439aF9cIibuRVpAg_;
N_LIB_PRIVATE TNimType NTI__tHzJDR2mlN9ayrQ3Mg5BW5Q_;
extern TNimType NTI__xHTZrq9aYs6boc9bCba0JbpQ_;
extern TNimType NTI__P862mCDAUrlG5aF5HvxacQ_;
N_LIB_PRIVATE TNimType NTI__KHHquxSoY3JWz0nX5DbfmQ_;
extern TNimType* nimTypeRoot;

#line 54 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"
N_LIB_PRIVATE N_NIMCALL(br_hmac_drbg_context*, newRng__9cKaYUOzNpI6Cw7CIYoErTQ)(void) {	br_hmac_drbg_context* result;	tyProc__8515EaYVeX8ph3fGJmTq3w seeder;	br_hmac_drbg_context* rng_1;	br_hmac_drbg_context* T5_;{	result = (br_hmac_drbg_context*)0;
#line 58 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"

#line 58 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"

#line 58 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"
	seeder = br_prng_seeder_system(NIM_NIL);
#line 59 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"
	{
#line 59 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"
		if (!(seeder == NIM_NIL)) goto LA3_;

#line 60 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"

#line 60 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"
		result = NIM_NIL;		goto BeforeRet_;
	}
	LA3_: ;

#line 62 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"
	T5_ = (br_hmac_drbg_context*)0;	T5_ = (br_hmac_drbg_context*) newObj((&NTI__RuNvFuo5ptASsihINNteSw_), sizeof(br_hmac_drbg_context));	rng_1 = T5_;
#line 63 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"

#line 63 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"
	br_hmac_drbg_init(rng_1, (&br_sha256_vtable), NIM_NIL, ((NI) 0));

#line 64 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"
	{		int T8_;
#line 64 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"

#line 64 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"

#line 64 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"
		T8_ = (int)0;		T8_ = seeder(&(*rng_1).vtable);		if (!(T8_ == ((NI32) 0))) goto LA9_;

#line 65 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"

#line 65 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"
		result = NIM_NIL;		goto BeforeRet_;
	}
	LA9_: ;
	result = rng_1;	}BeforeRet_: ;
	return result;}

#line 22 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size) {	void* T1_;
#line 24 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"

#line 24 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memset(a, v, ((size_t) (size)));}

#line 33 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
#line 34 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"

#line 34 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"
	nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory(p, ((int) 0), size);
}
static N_NIMCALL(void, Marker_tyRef__KHHquxSoY3JWz0nX5DbfmQ)(void* p, NI op) {
	tyObject_Env_keysdotnim___tHzJDR2mlN9ayrQ3Mg5BW5Q* a;
	a = (tyObject_Env_keysdotnim___tHzJDR2mlN9ayrQ3Mg5BW5Q*)p;
}

#line 70 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"
N_LIB_PRIVATE N_CLOSURE(void, callRng__ZB19agXKjnWjgtU9chW9bidfw)(NU8* data_0, NI data_0Len_0, void* ClE_0) {	tyObject_Env_keysdotnim___tHzJDR2mlN9ayrQ3Mg5BW5Q* colonenvP_;	colonenvP_ = (tyObject_Env_keysdotnim___tHzJDR2mlN9ayrQ3Mg5BW5Q*) ClE_0;
#line 71 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"

#line 71 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"
	brHmacDrbgGenerate__jb39atYOOGTT2cdYx6onnSw((*colonenvP_).rngPtr1, data_0, data_0Len_0);
}

#line 68 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_SkSecretKey__aKiBFtqo69b60sWLnM5A9c3w, random__pJ2doYDmdqPuNiIuwUmJ4w)(br_hmac_drbg_context* rng_0) {	tyObject_SkSecretKey__aKiBFtqo69b60sWLnM5A9c3w result;	tyObject_Env_keysdotnim___tHzJDR2mlN9ayrQ3Mg5BW5Q* colonenv_;	tyProc__2eQPaS8XIidfzb11dDC4nw T1_;	nimZeroMem((void*)(&result), sizeof(tyObject_SkSecretKey__aKiBFtqo69b60sWLnM5A9c3w));	colonenv_ = (tyObject_Env_keysdotnim___tHzJDR2mlN9ayrQ3Mg5BW5Q*)0;
#line 230 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system.nim"
	colonenv_ = (tyObject_Env_keysdotnim___tHzJDR2mlN9ayrQ3Mg5BW5Q*) newObj((&NTI__KHHquxSoY3JWz0nX5DbfmQ_), sizeof(tyObject_Env_keysdotnim___tHzJDR2mlN9ayrQ3Mg5BW5Q));	(*colonenv_).Sup.m_type = (&NTI__tHzJDR2mlN9ayrQ3Mg5BW5Q_);
#line 69 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"

#line 69 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"
	(*colonenv_).rngPtr1 = rng_0;
#line 73 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"
	nimZeroMem((void*)(&T1_), sizeof(tyProc__2eQPaS8XIidfzb11dDC4nw));	T1_.ClP_0 = callRng__ZB19agXKjnWjgtU9chW9bidfw; T1_.ClE_0 = colonenv_;
#line 73 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"
	result = random__0zyuItkuaHgarDWONXkbnQ(T1_);	return result;}

#line 109 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_SkKeyPair__11md6PDL9c3Ydro9bo69avH7g, random__HS5tU9cyelo6UXEHvWOYUFg)(br_hmac_drbg_context* rng_0) {	tyObject_SkKeyPair__11md6PDL9c3Ydro9bo69avH7g result;	tyObject_SkSecretKey__aKiBFtqo69b60sWLnM5A9c3w seckey;	nimZeroMem((void*)(&result), sizeof(tyObject_SkKeyPair__11md6PDL9c3Ydro9bo69avH7g));
#line 110 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"

#line 110 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"

#line 110 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"
	seckey = random__pJ2doYDmdqPuNiIuwUmJ4w(rng_0);	chckNil((void*)(&result));	nimZeroMem((void*)(&result), sizeof(tyObject_SkKeyPair__11md6PDL9c3Ydro9bo69avH7g));	result.seckey = seckey;
#line 113 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"

#line 113 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"
	result.pubkey = toPublicKey__dZX6pG1PJuze9ctWTRA1ENw((&seckey));	return result;}

#line 131 "/home/runner/work/nim-waku/nim-waku/vendor/nim-stew/stew/byteutils.nim"
static N_INLINE(NimStringDesc*, toHex__8S8gmm9b1kIYuNI7oeA9arYQbyteutils)(tyArray__vEOa9c5qaE9ajWxR5R4zwfQg ba) {	NimStringDesc* result;	result = (NimStringDesc*)0;
#line 132 "/home/runner/work/nim-waku/nim-waku/vendor/nim-stew/stew/byteutils.nim"

#line 135 "/home/runner/work/nim-waku/nim-waku/vendor/nim-stew/stew/byteutils.nim"

#line 135 "/home/runner/work/nim-waku/nim-waku/vendor/nim-stew/stew/byteutils.nim"
	result = toHexAux__mTF3iGytPXR76nCDQ9aqz9cw(ba, 32);	return result;}

#line 11 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {	void* T1_;
#line 13 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"

#line 13 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memcpy(dest, source, ((size_t) (size)));}

#line 81 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"
N_LIB_PRIVATE N_NIMCALL(void, toRaw__A1jy5RjxYg9aCVFRbqZKqvA)(tyObject_SkSecretKey__aKiBFtqo69b60sWLnM5A9c3w* seckey, tyArray__vEOa9c5qaE9ajWxR5R4zwfQg Result) {	tyArray__vEOa9c5qaE9ajWxR5R4zwfQg T1_;
#line 82 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"

#line 82 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"
	nimZeroMem((void*)T1_, sizeof(tyArray__vEOa9c5qaE9ajWxR5R4zwfQg));	toRaw__QU8um79aWTK6cAEMtJp8d7g(seckey, T1_);
	nimCopyMem((void*)Result, (NIM_CONST void*)T1_, sizeof(tyArray__vEOa9c5qaE9ajWxR5R4zwfQg));}

#line 198 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___3DNipDnN4A79aliwn9a5d9bQA)(tyObject_SkSecretKey__aKiBFtqo69b60sWLnM5A9c3w* seckey) {	NimStringDesc* result;	tyArray__vEOa9c5qaE9ajWxR5R4zwfQg T1_;	result = (NimStringDesc*)0;
#line 199 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"

#line 200 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"

#line 200 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"

#line 200 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"
	nimZeroMem((void*)T1_, sizeof(tyArray__vEOa9c5qaE9ajWxR5R4zwfQg));	toRaw__A1jy5RjxYg9aCVFRbqZKqvA(seckey, T1_);

#line 200 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"
	result = toHex__8S8gmm9b1kIYuNI7oeA9arYQbyteutils(T1_);	return result;}

#line 131 "/home/runner/work/nim-waku/nim-waku/vendor/nim-stew/stew/byteutils.nim"
static N_INLINE(NimStringDesc*, toHex__WZR7PQRd3CyFIbwX5SDWPAbyteutils)(tyArray__w5VB8h5K8DB3oWrO5U2wqg ba) {	NimStringDesc* result;	result = (NimStringDesc*)0;
#line 132 "/home/runner/work/nim-waku/nim-waku/vendor/nim-stew/stew/byteutils.nim"

#line 135 "/home/runner/work/nim-waku/nim-waku/vendor/nim-stew/stew/byteutils.nim"

#line 135 "/home/runner/work/nim-waku/nim-waku/vendor/nim-stew/stew/byteutils.nim"
	result = toHexAux__mTF3iGytPXR76nCDQ9aqz9cw(ba, 64);	return result;}

#line 2112 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system.nim"
static N_INLINE(void, copyMem__i80o3k0SgEI5gTRCzYdyWAsystem)(void* dest, void* source, NI size) {
#line 2113 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system.nim"

#line 2113 "/home/runner/work/nim-waku/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system.nim"
	nimCopyMem(dest, source, size);
}

#line 103 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"
N_LIB_PRIVATE N_NIMCALL(void, toRaw__W9bYIkOOHQ8dZSTz9aIjEPEQ)(tyObject_SkPublicKey__YxxaGK7KOKaWCOaZ44rHMA* pubkey, tyArray__w5VB8h5K8DB3oWrO5U2wqg Result) {	tyArray__DqM3b17bbm0d9bCZr9c2fLDQ tmp;	chckNil((void*)Result);	nimZeroMem((void*)Result, sizeof(tyArray__w5VB8h5K8DB3oWrO5U2wqg));	nimZeroMem((void*)tmp, sizeof(tyArray__DqM3b17bbm0d9bCZr9c2fLDQ));
#line 104 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"

#line 104 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"
	toRaw__bCgy0bI8LIRIvVpAjgBPMg(pubkey, tmp);

#line 105 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"

#line 105 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"
	copyMem__i80o3k0SgEI5gTRCzYdyWAsystem(((void*) ((&Result[(((NI) 0))- 0]))), ((void*) ((&tmp[(((NI) 1))- 0]))), ((NI) 64));
}

#line 190 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___sCk67mWMaXubq9aFhJ4e9cXw)(tyObject_SkPublicKey__YxxaGK7KOKaWCOaZ44rHMA* pubkey) {	NimStringDesc* result;	tyArray__w5VB8h5K8DB3oWrO5U2wqg T1_;	result = (NimStringDesc*)0;
#line 191 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"

#line 192 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"

#line 192 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"

#line 192 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"
	nimZeroMem((void*)T1_, sizeof(tyArray__w5VB8h5K8DB3oWrO5U2wqg));	toRaw__W9bYIkOOHQ8dZSTz9aIjEPEQ(pubkey, T1_);

#line 192 "/home/runner/work/nim-waku/nim-waku/vendor/nim-eth/eth/keys.nim"
	result = toHex__WZR7PQRd3CyFIbwX5SDWPAbyteutils(T1_);	return result;}
N_LIB_PRIVATE N_NIMCALL(void, eth_keysDatInit000)(void) {

#line 999999 "generated_not_to_break_here"
static TNimNode* TM__M68nGWgBGfdRpIiz8SqAwg_2_2[2];
static TNimNode TM__M68nGWgBGfdRpIiz8SqAwg_0[3];NTI__tHzJDR2mlN9ayrQ3Mg5BW5Q_.size = sizeof(tyObject_Env_keysdotnim___tHzJDR2mlN9ayrQ3Mg5BW5Q);
NTI__tHzJDR2mlN9ayrQ3Mg5BW5Q_.kind = 17;
NTI__tHzJDR2mlN9ayrQ3Mg5BW5Q_.base = (&NTI__ytyiCJqK439aF9cIibuRVpAg_);
NTI__tHzJDR2mlN9ayrQ3Mg5BW5Q_.flags = 1;
NTI__tHzJDR2mlN9ayrQ3Mg5BW5Q_.name = "object";
NTI__tHzJDR2mlN9ayrQ3Mg5BW5Q_.nextType = nimTypeRoot; nimTypeRoot=&NTI__tHzJDR2mlN9ayrQ3Mg5BW5Q_;
TM__M68nGWgBGfdRpIiz8SqAwg_2_2[0] = &TM__M68nGWgBGfdRpIiz8SqAwg_0[1];
TM__M68nGWgBGfdRpIiz8SqAwg_0[1].kind = 1;
TM__M68nGWgBGfdRpIiz8SqAwg_0[1].offset = offsetof(tyObject_Env_keysdotnim___tHzJDR2mlN9ayrQ3Mg5BW5Q, colonstate_);
TM__M68nGWgBGfdRpIiz8SqAwg_0[1].typ = (&NTI__xHTZrq9aYs6boc9bCba0JbpQ_);
TM__M68nGWgBGfdRpIiz8SqAwg_0[1].name = ":state";
TM__M68nGWgBGfdRpIiz8SqAwg_2_2[1] = &TM__M68nGWgBGfdRpIiz8SqAwg_0[2];
TM__M68nGWgBGfdRpIiz8SqAwg_0[2].kind = 1;
TM__M68nGWgBGfdRpIiz8SqAwg_0[2].offset = offsetof(tyObject_Env_keysdotnim___tHzJDR2mlN9ayrQ3Mg5BW5Q, rngPtr1);
TM__M68nGWgBGfdRpIiz8SqAwg_0[2].typ = (&NTI__P862mCDAUrlG5aF5HvxacQ_);
TM__M68nGWgBGfdRpIiz8SqAwg_0[2].name = "rngPtr1";
TM__M68nGWgBGfdRpIiz8SqAwg_0[0].len = 2; TM__M68nGWgBGfdRpIiz8SqAwg_0[0].kind = 2; TM__M68nGWgBGfdRpIiz8SqAwg_0[0].sons = &TM__M68nGWgBGfdRpIiz8SqAwg_2_2[0];
NTI__tHzJDR2mlN9ayrQ3Mg5BW5Q_.node = &TM__M68nGWgBGfdRpIiz8SqAwg_0[0];
NTI__KHHquxSoY3JWz0nX5DbfmQ_.size = sizeof(tyObject_Env_keysdotnim___tHzJDR2mlN9ayrQ3Mg5BW5Q*);
NTI__KHHquxSoY3JWz0nX5DbfmQ_.kind = 22;
NTI__KHHquxSoY3JWz0nX5DbfmQ_.base = (&NTI__tHzJDR2mlN9ayrQ3Mg5BW5Q_);
NTI__KHHquxSoY3JWz0nX5DbfmQ_.name = "anon ref object from /home/runner/work/nim-waku/nim-waku/vendor"
"/nim-eth/eth/keys.nim(73, 24)";
NTI__KHHquxSoY3JWz0nX5DbfmQ_.nextType = nimTypeRoot; nimTypeRoot=&NTI__KHHquxSoY3JWz0nX5DbfmQ_;
NTI__KHHquxSoY3JWz0nX5DbfmQ_.marker = Marker_tyRef__KHHquxSoY3JWz0nX5DbfmQ;
}

